### ISSUE TITLE
表情会显示[收到了一个表情，请在手机上查看]

### ISSUE THREAD

**Issue by gaocegege** [geeeeeeeeek/electronic-wechat#10]
#### Description

表情会显示`[收到了一个表情，请在手机上查看]`

#### Steps to Reproduce Issue

不知道哪些表情可以复现，目前是在接收别人发的官方表情，比如Bilibili表情时会出现这样的问题， :heart: 里的表情是正常的。也有可能是统计样本小，偶尔发生的问题也说不定。。

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.4.1`
- Version of Node.js (run `$ node --version`): `v0.10.33`
- OS: `OS X 10.11.3`
- Architecture `X86(Architecture是指处理器架构么)`
- Stack trace from the error message (if any)

``` 
Nothing
```

#### 表现

Electron Wechat:

<figure>
	<img src="https://cloud.githubusercontent.com/assets/5100735/13314055/de55e590-dbdd-11e5-87f3-01b4d0a9b1e2.png" width="300">
</figure>

Wechat in iPhone:

<figure>
	<img src="https://cloud.githubusercontent.com/assets/5100735/13314072/fddf64cc-dbdd-11e5-8cb4-7d84544a5992.jpg" height="500">
</figure>

**Comment by geeeeeeeeek** [comment]
是这样的..检测到聊天消息节点变动时每隔50ms重新注入一次表情..这个节点是动态加载的，向上滑的时候下面的节点就移除了，上面的节点加入需要重新注入..

所以滑得快的话可能会出现这样的情况，正在寻找更好的替代方案，你暂时可以认为是by design的..

**Comment by gaocegege** [comment]
0.0
Got it...
