### ISSUE TITLE
Linux托盘能否提示未读消息数量？

### ISSUE THREAD

**Issue by yzsatgithub** [geeeeeeeeek/electronic-wechat#100]
#### Description
Linux托盘能否提示未读消息数量？ 也就是红色的小数字

#### Specifications

- Version of Electron (run `$ electron --version`): `v1.1.1`
- Version of Node.js (run `$ node --version`): `v5.9.0`
- OS: `Ubuntu 14.04 LTS`
- Architecture `x86_64`

**Comment by geeeeeeeeek** [comment]
@yzsatgithub 暂时不可以。Electron的dock badge和tray title都只有OS X有，你可以去Electron社区抗议下。
