### ISSUE TITLE
无法处理撤回动作

### ISSUE THREAD

**Issue by petronny** [geeeeeeeeek/electronic-wechat#101]
#### Description
无法处理撤回消息动作，撤回消息显示的都是"阻止一次撤回"

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.37.2`
- Version of Node.js (run `$ node --version`): `v5.9.1`
- OS: `Archlinux`
- Architecture `x86_64`

**Comment by geeeeeeeeek** [comment]
不然应该显示什么？

**Comment by petronny** [comment]
应该正确撤回上一条消息，显示谁谁谁撤回了一条消息

**Comment by geeeeeeeeek** [comment]
…你没有理解这个功能的意义么，就是用来阻止撤回的啊

**Comment by petronny** [comment]
做成一个选项吧。虽然这个很hack，但是不要默认就阻止撤回

**Comment by geeeeeeeeek** [comment]
以后可以考虑做成一个选项。但是默认阻止撤回对用户来说有利无害啊。

**Comment by petronny** [comment]
从做产品的角度来说会给用户不好的用户体验。或者认为你这个其实是bug，不利于推广。

**Comment by geeeeeeeeek** [comment]
我不认为会带来不好的用户体验。这个feature的反馈一直都是非常正面的，而且撤回的文案也不难理解吧，不至于会产生什么误会。
