### ISSUE TITLE
自行打包后运行，出现对话框全白的情况

### ISSUE THREAD

**Issue by yzsatgithub** [geeeeeeeeek/electronic-wechat#103]
#### Description
刚刚升级到最新的1.1.1版本（用的是git pull然后重新编译打包。）一天之后再运行软件，就会出现窗口全白的情况，如图。
![2016-03-26 12 57 22](https://cloud.githubusercontent.com/assets/10882352/14058149/a3dde502-f352-11e5-9377-50555234a99f.png)

如果在安装文件夹运行`npm start`，则会出现扫码页面，但是扫码成功后，仍然是一片空白。

尝试过重新安装。

#### Specifications

- Version of Electron (run `$ electron --version`): `v1.1.1`
- Version of Node.js (run `$ node --version`): `v5.9.0`
- OS: `Ubuntu14.04 LTS`
- Architecture `x86_64`

**Comment by geeeeeeeeek** [comment]
网络问题（网速、DNS等），首屏没有加载出来。

刷新重试或在浏览器中尝试访问wx.qq.com，是否能够正常加载。

**Comment by geeeeeeeeek** [comment]
如果浏览器可访问而electron不行的话请打开dev tools发一下console的报错。删除app重新build应该能解决。

**Comment by yzsatgithub** [comment]
@geeeeeeeeek  用浏览器可以打开wx.qq.com。  随后立即试了一下app，又可以用了。  如果再出现类似的状况，我就把console报错贴出来。

**Comment by geeeeeeeeek** [comment]
@yzsatgithub 那可能只是网络状态有问题，多个多次复现我再open这个issue。不过我觉得有必要加个loading的indicator。

**Comment by yzsatgithub** [comment]
@geeeeeeeeek 有道理，一些必要的提示信息
