### ISSUE TITLE
os X 10.11.4下有新消息后点击托盘图标没有响应

### ISSUE THREAD

**Issue by evonotevil** [geeeeeeeeek/electronic-wechat#104]
First, make sure your issue is strictly related to the ***Electronic WeChat*** project. If it's a question or feature request, you can remove the template below.

#### Description

要手动点击Dock上的图标才可以。

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.36.9`
- Version of Node.js (run `$ node --version`): `v0.0.0`
- OS: `<OS>`
- Architecture `<ARCH>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by geeeeeeeeek** [comment]
无法复现，你能再次复现吗？

**Comment by evonotevil** [comment]
还是不行

**Comment by geeeeeeeeek** [comment]
你使用的是master上的代码build的，还是哪一个release？

**Comment by evonotevil** [comment]
用的是v1.1的release

**Comment by geeeeeeeeek** [comment]
@evonotevil 我好像还是没有理解…你是说notification的气泡还是状态栏的tray icon？
