### ISSUE TITLE
缓存爆掉后不会再接受任何消息

### ISSUE THREAD

**Issue by petronny** [geeeeeeeeek/electronic-wechat#106]
#### Description
在收到大量动态图片表情后会不能接受任何后续消息
__再现方法__
登录后向回话发送大量动态图片表情即可，没必要不同。
__其他说明__
1. 删除.{config,cache}/Electron后重新登录不会恢复，删chromium的才行

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.37.2`
- Version of Node.js (run `$ node --version`): `v5.9.1`
- OS: `Archlinux`
- Architecture `x86_64`

**Comment by geeeeeeeeek** [comment]
首先，我这无法复现，多少贴纸发过去都没问题，多半是你网络或浏览器性能的问题。其次，这是网页版微信的实现决定的，我做不了什么优化。
