### ISSUE TITLE
可以增加快捷键截屏、消息数量不提示的功能吗？

### ISSUE THREAD

**Issue by timothyyang96** [geeeeeeeeek/electronic-wechat#109]
First, make sure your issue is strictly related to the ***Electronic WeChat*** project. If it's a question or feature request, you can remove the template below.

#### Description
微信mac端有直接快捷键截屏的功能，以及可以取消消息数量提示。

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- Version of Node.js (run `$ node --version`): `v0.0.0`
- OS: `<OS>`
- Architecture `<ARCH>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by timothyyang96** [comment]
还有几个问题，1、语音没法播放；2、要看最新的公众号文章需要全部刷新一遍。

**Comment by timothyyang96** [comment]
又发现了一个问题，好像没法在群里@其他成员

**Comment by arrowrowe** [comment]
- 群聊@的问题参见 #33.

**Comment by geeeeeeeeek** [comment]
@timothyyang96 语音应该是可以播放的，公众号的话是网页版微信的实现问题了。

群聊比较麻烦，要注入一个选择群成员的panel。获取群成员是做得到的，之前稍微做了点笔记：
```javascript
// 好像是.chat的scope
currentContact.MemberList
```

```javascript
function getAtName(ele){
  var contact = angular.element(ele).scope().$parent.contact;
  if (contact.RemarkName) {
  	return contact.NickName;
  } else if (contact.DisplayName) {
  	return contact.DisplayName;
  } else {
  	return contact.NickName;
  }
}

angular.element('pre:last').scope().editAreaCtn += '@' + getAtName();
```

```javascript
angular.element('pre:last').scope().editAreaCtn = "Hello world";
```

**Comment by timothyyang96** [comment]
又发现了一个bug，从网页上复制文字到客户端上，文字前后总有大段空格，需要手动删除。
