### ISSUE TITLE
osxpack.sh脚本

### ISSUE THREAD

**Issue by Jasonix** [geeeeeeeeek/electronic-wechat#11]
First, make sure your issue is strictly related to the ***Electronic WeChat*** project. Some upstream issues caused by ***electron*** can be viewed in the **guidelines for contributing** showing above.

If it's a question or feature request, you can remove the template below.

#### Description
当前 --version=0.36.7 会报错， 改成--version=0.36.8才能正常打包

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- Version of Node.js (run `$ node --version`): `v0.0.0`
- OS: `<OS>`
- Architecture `<ARCH>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by geeeeeeeeek** [comment]
看你的stack trace，是不是因为你安装的electron版本和pack使用的版本不一致导致的。

**Comment by Jasonix** [comment]
是的， nam install 安装的Electron是0.36.8

**Comment by geeeeeeeeek** [comment]
好，我修改下脚本

**Comment by xiaoyu2er** [comment]
npn install 后 运行脚本提示 Error: you need to npm install electron-packager. Aborting.
全局安装 electron-packager 后， 脚本运行正常。

**Comment by geeeeeeeeek** [comment]
对的，`electron-packager`需要在global安装，或者至少需要加入path中。我会修改一下脚本。

**Comment by viko16** [comment]
脚本的执行可以加到 package.json 里的 scripts 对象中，这样就不需要全局安装了，会调用 node_modules/.bin/ 中的内容

**Comment by geeeeeeeeek** [comment]
@viko16 具体加入到scripts的哪个command中？

**Comment by viko16** [comment]
@geeeeeeeeek 我提个 pr 吧。

**Comment by viko16** [comment]
@geeeeeeeeek 

### 效果演示：
![image](https://cloud.githubusercontent.com/assets/5064777/13325650/b679f3be-dc1d-11e5-8216-7a0a9b3b9213.png)
> ^ 全局并没有安装 `electron-packager`

![image](https://cloud.githubusercontent.com/assets/5064777/13325695/dae5b698-dc1d-11e5-81ba-7abad118318e.png)
> ^ 使用 script 与不使用的对比

**Comment by geeeeeeeeek** [comment]
@viko16 Thx a lot.

**Comment by htc550605125** [comment]
#16
