### ISSUE TITLE
可否添加记录上一次配置信息的功能

### ISSUE THREAD

**Issue by yangzj1992** [geeeeeeeeek/electronic-wechat#111]
每次扫码登录后，默认都是开启桌面通知和开启声音的..每次都要把声音提醒关闭掉..感觉比较麻烦.可否保存上一次的设定配置？扫码登录后自动加载上一次的配置信息？

**Comment by geeeeeeeeek** [comment]
微信自己应该就没保存配置…

技术上应该可以自己往localStorage写配置，然后通过Angular注入，有人认领这个需求么？
