### ISSUE TITLE
【求助】通过chrome抓包得到的消息通知是乱码

### ISSUE THREAD

**Issue by whahuzhihao** [geeeeeeeeek/electronic-wechat#113]
在截取mmwebwx-bin/webwxsync通知过来的新消息时发现内容是乱码字符
body.msgList[0].Content = "å•Š"; 像这种，请问有没有办法变成中文呢？

不仅是electron里面是这样，官方web微信里用chrome抓包也是这样。

**Comment by geeeeeeeeek** [comment]
@whahuzhihao 我这也是这样的，微信做了下编码转换，然而我也不知道有什么卵用。

你看到的是UTF-8编码，原文是Unicode编码，所以显示为乱码。转换回去(UTF8 to Unicode)就好了。

**Comment by whahuzhihao** [comment]
解决了…… 因为response里没有返回所用的编码，所以node默认当做iso-8859-1来处理的。其实字节码是对的，只要转换一下就行了。
`var content = new Buffer(e.Content,'binary').toString('utf8');`

**Comment by gurongsheng** [comment]
只有部分是对的，chrome里面也同样乱码，目前我测试chrome 54的某些版本不乱码

**Comment by aninfeel** [comment]
这是开发工具显示的联系人的数据：
{
"Uin": 0,
"UserName": "@bf8d8632c7b4ef5b695195208ac6c2b1",
"NickName": "å‘¨æœ›",
"AttrStatus": 4296743,
"PYInitial": "",
"PYQuanPin": "",
"RemarkPYInitial": "",
"RemarkPYQuanPin": "",
"MemberStatus": 0,
"DisplayName": "",
"KeyWord": "qin"
}
,{
"Uin": 0,
"UserName": "@ae9e19dfabae487af1d5bf0a0a67eeb50b54ab90f877f19e25902e21dc06dc3b",
"NickName": "åˆ˜æ˜Žæ˜¾",
"AttrStatus": 104485,
"PYInitial": "",
"PYQuanPin": "",
"RemarkPYInitial": "",
"RemarkPYQuanPin": "",
"MemberStatus": 0,
"DisplayName": "",
"KeyWord": ""
}

NickName看起来像乱码，UserName完全看不出怎么回事？

**Comment by xiaokaike** [comment]
https://chrome.google.com/webstore/detail/set-character-encoding/bpojelgakakmcfmjfilgdlmhefphglae

这个插件，将编码改为 `utf-8` 就可以了
