### ISSUE TITLE
二维码超时失效问题

### ISSUE THREAD

**Issue by RainySeattle** [geeeeeeeeek/electronic-wechat#117]
#### Description
若打开应用后没有立即扫码登录，则一段时间后扫码登录会失效，手机提示『暂时无法登录，请尝试重新登录』。
推测此问题是微信方出于安全性的考虑对二维码的有效时间做了限制造成，故建议 electronic-wechat 增加定时刷新二维码。
谢谢。

**Comment by geeeeeeeeek** [comment]
其实二维码是会自动刷新的，不过网络中断了之后似乎就不会了。

**Comment by iamcc** [comment]
Cmd + R 刷新下就可以。

**Comment by djne** [comment]
希望在二维码界面可以提示CMD+R刷新，我搜了半天才找到这里解决了问题，期间不断的重新启动，点击二维码都没效果
