### ISSUE TITLE
群内@的选择框太小了

### ISSUE THREAD

**Issue by ray26** [geeeeeeeeek/electronic-wechat#120]
在群内at的时候如果名字太长的话，会被选择框挡住，希望能够把选择框扩大一点，而且选择框里面无法显示emoji的名字
![1](https://cloud.githubusercontent.com/assets/6435613/14408204/ca71f19c-ff1c-11e5-9a00-3635617eb86e.jpg)
![default](https://cloud.githubusercontent.com/assets/6435613/14408205/cbb5b926-ff1c-11e5-96bb-7c7f92864a8d.jpg)

**Comment by geeeeeeeeek** [comment]
名字主要是提示作用，看到前几个字应该就够了吧。如果要完整显示的话选择框可能会变得很长，因为一些人的昵称就是那么长。。

Emoji的话我这是可以显示的，可以见另一个issue中的截图。
