### ISSUE TITLE
ubuntukylin 扫描二维码进入主界面之后，又自动返回到了二维码页面

### ISSUE THREAD

**Issue by vinartis** [geeeeeeeeek/electronic-wechat#123]
#### Description
系统：
Linux leons 4.2.0-35-generic #40-Ubuntu SMP Tue Mar 15 22:15:45 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

使用最新代码进行安装和启动
`Merge: 60e51ff 91ac928
Author: Zhongyi Tong <ZHONGYI.TONG@foxmail.com>
Date:   Sun Apr 10 20:24:56 2016 +0800

    Merge pull request #121 from geeeeeeeeek/feature/group-at
    
    * 粗暴解决群@功能
`

扫描二维码之后，进入了微信主界面，然后立即又返回到了二维码扫描页面

**Comment by geeeeeeeeek** [comment]
session的问题，不是很清楚，我这里无法复现。你能提供更多的信息吗？应该重新登录下就好了吧。

**Comment by vinartis** [comment]
我这里并没有其他的操作，就是clone下代码，然后执行sudo npm install 然后执行sudo npm start

**Comment by vinartis** [comment]
@geeeeeeeeek  问题可以关闭，这个是因为我本地的系统时间不正确造成的，不过这个也算是一个ｂｕｇ吧。不能因为本机的系统时间影响程序的正常运行

**Comment by geeeeeeeeek** [comment]
@vinartis 能具体说明一下和系统时间有什么关系吗？

**Comment by vinartis** [comment]
@geeeeeeeeek 我本机的系统时间比实际时间提前了两天，比如今天是4月11号 我的系统时间是4月13号，我修改了主板里面的时间为正确的时间之后，再启动wechat就没有问题了

**Comment by geeeeeeeeek** [comment]
@vinartis 你这个应该和微信官方或electron反馈……
