### ISSUE TITLE
关于登录流程的优化建议

### ISSUE THREAD

**Issue by xingrz** [geeeeeeeeek/electronic-wechat#127]
相信是由于网页版微信的限制，现在断网再连上（比如 MacBook 合盖下班回家…）是会跳回扫码页面的。而官方客户端则可以一直保持在线。

那么就会带来一个不太方便的情况是：等我重新揭开 MacBook 时，我就忘了这回事了…所以第一点，**掉线后建议直接将窗口弹到前台。**

那么第二个情况是，我忘了它掉线了，它就一直在后台…等我想起来，切换过去，拿起手机扫码…这时候这个二维码已经过期失效了(#117)，是不成功的。**那么建议在未登录状态下，应用从后台切换到前台时强行刷新一下二维码。**

**Comment by geeeeeeeeek** [comment]
@xingrz 正在考虑

**Comment by geeeeeeeeek** [comment]
正在优化这个问题，Jquery的错误不再会阻塞二维码自动刷新，接下来会在检测到网络重连的时候强制刷新一下应用。
```
commit b2c907bd3fde3eb1f57512826adb6be5ae5306db
Author: Zhongyi Tong <zhongyi.tong@foxmail.com>
Date:   Sat Apr 30 11:09:00 2016 +0800

    Optimize app startup.

    In previous versions, when a network error occured, the main process would be jammed by undefined $ exception. Thus the QR code would not refresh itself.

    This is a fix to #127.
```

**Comment by geeeeeeeeek** [comment]
Optimized in #168.
