### ISSUE TITLE
MacBook Retina 屏幕下聊天内容中的 emoji 显示效果不佳

### ISSUE THREAD

**Issue by xingrz** [geeeeeeeeek/electronic-wechat#128]
<img width="498" alt="2016-04-14 12 52 24" src="https://cloud.githubusercontent.com/assets/288288/14517423/dbf129ee-023f-11e6-91f1-587a191b17c0.png">

如图所示，QQ 表情是正常的，而符号表情则没有使用 Retina 分辨率。

表情选择框里则是正常的。

**Comment by geeeeeeeeek** [comment]
@xingrz 微信用了两张雪碧图，排列完全不一样，没法换。

```
url(/zh_CN/htmledition/v2/images/web_wechat_login_bg28a2f7.jpg)
url(/zh_CN/htmledition/v2/images/icon/emoji28a2f7.png)
```
