### ISSUE TITLE
发送图片窗口的菊花显示效果不佳

### ISSUE THREAD

**Issue by xingrz** [geeeeeeeeek/electronic-wechat#129]
<img width="527" alt="2016-04-14 12 50 37" src="https://cloud.githubusercontent.com/assets/288288/14517455/29c78d0c-0240-11e6-98e4-23abd5a0336f.png">

如图，太大，而且不是 Retina 分辨率。

建议改小 `_(:зゝ∠)_`

**Comment by geeeeeeeeek** [comment]
怪微信咯…这个story下个milestone再说吧…把剩下几个关键的issue修了就拉release分支了
