### ISSUE TITLE
公众号菜单

### ISSUE THREAD

**Issue by ray26** [geeeeeeeeek/electronic-wechat#134]
公众号的菜单能不能默认收起来，全部都是展开的不好寻找，而且显得很乱😳

**Comment by geeeeeeeeek** [comment]
![image](https://cloud.githubusercontent.com/assets/7262715/14698610/1c12d6ca-07c3-11e6-91e2-6e38e1478b70.png)
你说的是这个？

**Comment by leckylao** [comment]
![screen shot 2016-06-14 at 1 02 48 pm](https://cloud.githubusercontent.com/assets/148800/16029951/6c1603bc-3230-11e6-8848-2cf097b57526.png)

@geeeeeeeeek 能问一下这个公众号菜单是怎么调出来吗？我弄了半天没弄出来。。。

**Comment by geeeeeeeeek** [comment]
@leckylao 刷刷刷，刷不出来看代码，就知道了

**Comment by leckylao** [comment]
@geeeeeeeeek cmdR刷新是吧？刷不出来。代码看了

`angular.element('.reader')`

意思是微信网页版本来就有公众号是吧？我怎么没有。。。。

**Comment by leckylao** [comment]
`$(".reader_menu")
[]
$(".reader")
[]`

是不是我的账号的问题，抓的这些class都是没东西的。。。。。

**Comment by geeeeeeeeek** [comment]
你可以看看微信的代码，html和js，看看为什么少了个tab

**Comment by leckylao** [comment]
我想确认一下。
1. 这个是微信的问题不是软件问题？
2. 你的账号默认就有公众号那个tab？

On Tue, Jun 14, 2016, 4:19 PM Zhongyi Tong <notifications@github.com> wrote:

> 你可以看看微信的代码，html和js，看看为什么少了个tab
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/geeeeeeeeek/electronic-wechat/issues/134#issuecomment-225789850>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAJFQFQUbC2QVFFW-c3CH8S17Q-BHVtBks5qLkf_gaJpZM4II6zn>
> .
>
-- 
Regards,

Lecky Lao

**Comment by geeeeeeeeek** [comment]
@leckylao 微信一些功能会检测环境来决定是否显示（如截屏）。公众号的 tab 都是有的，你如果想知道为什么没显示的话建议你研究一下微信的代码。

**Comment by leckylao** [comment]
谢谢 @geeeeeeeeek 看了一下代码
`<div class="tab no_reader" ng-class="{no_reader: !isShowReader}">`
只能看到环境变量isShowReader，硬改也调不出来

`<div class="nav_view ng-scope" ng-style="{visibility:$state.current.name ==='read'?'visible':'hidden',width:$state.current.name ==='read'?'auto':'0'}" nav-read-directive="" style="visibility: hidden; width: 0px;">`
这个view得点到read tab才显示

但是看不出来为什么隐藏和怎么调出来，能请教一下怎么下一步研究微信的代码吗？我觉得应该不止我一个人会有这个问题。。。。

**Comment by geeeeeeeeek** [comment]
额这不是环境变量。你去看一下对应controller的代码，看一下isShowReader的逻辑是怎样的，如果你会angular的话...

**Comment by leckylao** [comment]
@geeeeeeeeek 谢谢，我终于找到了。。。。

`t.isShowReader = /qq\.com/gi.test(location.href)`

但是我的wx.qq.com redirect到web.wechat.com。。。。。。。。有什么办法不？
