### ISSUE TITLE
Linux 版文件路径带空格、可执行文件名是大写且带空格

### ISSUE THREAD

**Issue by GitatHub** [geeeeeeeeek/electronic-wechat#138]
Linux 版文件路径带空格、可执行文件名是大写且带空格很不合理
虽然可以自己修改，通过软链接解决，但是这个本应该可以避免

---------------
问题：
文本输入框不能右键
OS FEDORA 23 64

**Comment by geeeeeeeeek** [comment]
文件名我觉得有必要改一下

**Comment by geeeeeeeeek** [comment]
Fixed in [release/1.2 7b3cf97].
