### ISSUE TITLE
可以搞下支持win10使用不?

### ISSUE THREAD

**Issue by carl-wang-cn** [geeeeeeeeek/electronic-wechat#140]
First, make sure your issue is strictly related to the ***Electronic WeChat*** project. If it's a question or feature request, you can remove the template below.

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- Version of Node.js (run `$ node --version`): `v0.0.0`
- OS: `<OS>`
- Architecture `<ARCH>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by geeeeeeeeek** [comment]
Windows应该是可以使用的，不过我就不提供支持了，没有测试机。
