### ISSUE TITLE
v1.2.0 Release Notes + Collaborator 招募

### ISSUE THREAD

**Issue by geeeeeeeeek** [geeeeeeeeek/electronic-wechat#147]
**v1.2 (2016.04.21)** 已发布，请在本地使用 `git pull origin master` 更新代码，或前往 [Release](https://github.com/geeeeeeeeek/electronic-wechat/releases/latest) 下载应用。

**由于electron API变动，请务必升级你的electron之后再启动应用。**
### 推荐关注

- 新增 更新检测模块，应用内即可检查更新

- 新增 公众号文章的第三方分享功能

  现支持一键分享到微博、QQ 空间、Facebook、Twitter、Evernote 和邮件 (感谢 @oblank 的贡献)

- 新增 群聊 @ 提及成员功能，但收到提醒需要服务端支持 (感谢 @iamcc 的贡献)

- 升级 `electron-prebuilt` 版本至 `0.37.6` ， `electron-packager` 版本至 `7.0.0`。

  请 `npm install` 更新依赖。不支持v4.0以下的Node版本。**

- ~~降级 Emoji贴纸显示的功能~~

  ~~由于微信协议调整和官方代码缺陷，现有商店内贴纸及部分个人收藏的贴纸无法显示。后续跟进微信的修复进行调整。~~
  **好消息！微信已经修复了bug，现在所有贴纸均可正常显示！**

### 其他修改

1. 优化 登录界面使用单独的尺寸 (感谢 @xnfa 的贡献)
2. 优化 修改 OS X 下隐藏其他窗口的快捷键为 `Command+Alt+H` 。
3. 优化 Linux 下可执行文件文件名使用小写字母，去除空格。
4. 优化 Linux 下使用彩色图标。

其他 features 和 issues 将在 v1.3 中实现/修复。代码持续集成，每隔四周固定发布一次 release 。

另外，今后可以通过：

```shell
brew cask install electronic-wechat
```

安装 Electronic WeChat。刚给他们发了 pull request，要过段时间才能用。

### Collaborator 招募

由于精力有限，有时候不能很快地响应 issues 和 features… 所以希望征集 1 - 2 名小伙伴作为 collaborator 一起管理项目。希望你：

- 是 Electronic WeChat 用户，提交过 issues 或 pull requests，熟悉项目代码。
- 熟悉 基于 Angular 的前端开发，了解 Node 和 Electron。

**Comment by rivershang** [comment]
There is a type for the version of electron-prebuilt, it should be 0.37.6 :)

**Comment by knarfytrebil** [comment]
本人熟悉Backbone.js的开发，使用CoffeeScript. 也想做Collaborator.

**Comment by geeeeeeeeek** [comment]
@rivershang Thx! There should be a same typo in CHANGELOG.md. Would you like to fire a PR?

**Comment by rivershang** [comment]
@geeeeeeeeek You are welcome ^^ Done for #155 please review it, thanks.

**Comment by houkensjtu** [comment]
很有兴趣研究一下这个项目的代码，但是我不是很熟悉你所说的前端开发技术。
能否考虑简单介绍一下，这个项目的代码开发主要需要掌握哪些主要技术，这样也许会有更多有兴趣的使用者参与进来也说不定。

**Comment by geeeeeeeeek** [comment]
@knarfytrebil @houkensjtu 你们可以先review下代码，验证一下积压下来的issues。下个版本想加个控制面板，提供一些功能的可选项，这个功能希望留给collaborator来做。

**Comment by geeeeeeeeek** [comment]
普天同庆，微信修复了代码，现在所有贴纸均可正常显示！

**Comment by ripples-alive** [comment]
@geeeeeeeeek  贴纸问题需要更新么，还是直接就好了？ 😳 

以及同有兴趣完善此项目（强烈讨厌万年不更新的官方客户端），不过常年写后端，不擅长界面的东西，感觉除了 node 会玩其余就不行了，不知道扛不扛得住 😂

**Comment by geeeeeeeeek** [comment]
@ripples-alive 不需要更新…

话说你叫什么名字…我看你是复旦的…

**Comment by houkensjtu** [comment]
@geeeeeeeeek 多谢指点。虽然没有JavaScript经验，但是最近自学感觉node.js还是比较容易理解的。但是Angular的东西感觉比较摸不着头脑，看了一些网上的所谓tutorial也有点一知半解。有神马好的资料推荐吗？

**Comment by geeeeeeeeek** [comment]
@houkensjtu 看你的水平 基础比较好的话可以看build your own angular js，这本我看下来相当不错

**Comment by houkensjtu** [comment]
@geeeeeeeeek 看上去自己功力有点不够。。不过不知道是哪里不够，我先再打一打JavaScript的基础吧。THX！

**Comment by houkensjtu** [comment]
@geeeeeeeeek 另外微信网页版的知识要怎么获取呢（比如扫码登录的流程和原理之类）？这个和微信开放平台不是一回事吧

**Comment by geeeeeeeeek** [comment]
@houkensjtu 打开DevTools自己看代码调试 网上也有一些文章
