### ISSUE TITLE
1.2.0 无法启动 OS X El Capitan

### ISSUE THREAD

**Issue by dearrrfish** [geeeeeeeeek/electronic-wechat#148]
#### Description

Error of `Application "Electronic Wechat" cannot be opened` occurs when launching the app.

`npm start` works all right.
v1.1.1 works all right.

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.37.6`
- Version of Node.js (run `$ node --version`): `v5.9.0`
- OS: `OS X El Capitan 10.11.5 beta (15F18c)`
- Architecture `x64`
- Stack trace from the error message (if any)

**Comment by geeeeeeeeek** [comment]
奇怪，我换台Mac复现一下。
