### ISSUE TITLE
electronic桌面通知在16.04異樣

### ISSUE THREAD

**Issue by kdplus** [geeeeeeeeek/electronic-wechat#150]
First, make sure your issue is strictly related to the ***Electronic WeChat*** project. If it's a question or feature request, you can remove the template below.

#### Description
* 今天更新了ubuntu16.04發現electronic-wechat的桌面通知和更新之前的不太一樣了
* 也pull了最新版的問題也是一樣，現場圖如下
![screenshot from 2016-04-22 21-18-16](https://cloud.githubusercontent.com/assets/3047375/14742798/963abfae-08d0-11e6-835b-4f0a3ce561d1.png)

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- Version of Node.js (run `$ node --version`): `v5.9.1`
- OS: `ubuntu 16.04 lts`
- Architecture `<ARCH>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by geeeeeeeeek** [comment]
比较麻烦的是我这里无法复现…这两天没时间测试别的系统…如果你有兴趣的话可以研究一下，如果是electron导致的话建议给它们发个issues

![image](https://cloud.githubusercontent.com/assets/7262715/14743304/80e3e2cc-08d3-11e6-9d1a-ea71770f2fc7.png)

**Comment by kdplus** [comment]
@geeeeeeeeek 
剛才發現特地執行一下
npm install --save node-notifier
就恢復正常了2333....不知道是不是16.04的個例

**Comment by geeeeeeeeek** [comment]
可能你有些依赖没有更新吧
