### ISSUE TITLE
github提供的下载linux的下载包无法下载

### ISSUE THREAD

**Issue by coding-happily** [geeeeeeeeek/electronic-wechat#151]
请问一下作者能否提供一下国内的下载链接？

**Comment by zhaoqin102** [comment]
最好给个网盘地址，我下载了好几天都没成功。npm的包用淘宝源一样没速度

**Comment by geeeeeeeeek** [comment]
淘宝的cnpm听说都有CDN加速了，为什么会没速度...

网盘的话得我手动上传啊，现在都是CI自动发布的，而且应用自带的更新源也在GitHub上...

建议还是自带梯子吧..一劳永逸让生活更美好 : )

**Comment by coding-happily** [comment]
有什么好的梯子推荐  速度比较快

**Comment by geeeeeeeeek** [comment]
青云 之前用过一段时间 比较易用

**Comment by geeeeeeeeek** [comment]
theqingyun.info

**Comment by 1dot75cm** [comment]
lantern, xx-net 或自己搭服务器也挺好 @coding-happily
