### ISSUE TITLE
npm start successful，npm run build:osx failed

### ISSUE THREAD

**Issue by lightzero** [geeeeeeeeek/electronic-wechat#153]
First, make sure your issue is strictly related to the ***Electronic WeChat*** project. If it's a question or feature request, you can remove the template below.

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- Version of Node.js (run `$ node --version`): `v0.0.0`
- OS: `<OS>`
- Architecture `<ARCH>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>

>OS X EI Capitan 10.11.4 (15E65)

**Comment by ray26** [comment]
报错信息没有啊

**Comment by lightzero** [comment]
编译没有报错。不过打不开。

**Comment by geeeeeeeeek** [comment]
@lightzero 你electron什么版本？确定升级到0.36.7了么

**Comment by lightzero** [comment]
@geeeeeeeeek 谢谢，从新检查更新一下，都成功了。膜拜大神。

**Comment by geeeeeeeeek** [comment]
@lightzero 关键是electron有一个API变动。所以我这次特地发了release notes提醒要更新依赖…
