### ISSUE TITLE
播放小视频窗口关不了

### ISSUE THREAD

**Issue by xiafb** [geeeeeeeeek/electronic-wechat#154]
First, make sure your issue is strictly related to the ***Electronic WeChat*** project. If it's a question or feature request, you can remove the template below.

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- Version of Node.js (run `$ node --version`): `v0.0.0`
- OS: `<OS>`
- Architecture `<ARCH>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by geeeeeeeeek** [comment]
@xiafb 可能和窗口尺寸有关系，关闭按钮被遮挡，试试esc。
