### ISSUE TITLE
托盘图标双击无效.

### ISSUE THREAD

**Issue by eleveni386** [geeeeeeeeek/electronic-wechat#157]
1. 托盘图标双击无效,必须右键, 选择show, 
2. 通知气泡, 点击无法切换至应用程序( 1. 已经在前端了. 没hide, 2. 托盘情况下)

神, 有计划解决这两个问题么?

不懂, 这块东西. 爱莫能助, 只能提意见了.

**Comment by geeeeeeeeek** [comment]
@eleveni386 Linux目前就是这么设计的，右键是一个菜单，Show or Exit。如果双击的语义不明确。

通知气泡是一个已知的问题，Mac下应该是可以的，和electron的实现有关，会继续跟进这个问题。
