### ISSUE TITLE
Failure to send message(s)

### ISSUE THREAD

**Issue by jediofthecode** [geeeeeeeeek/electronic-wechat#158]
#### Description

I frequently have a problem where messages fail to send, and have to re-send, or take an extremely long time to send.

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.37.5`
- Version of Node.js (run `$ node --version`): `v5.11.0`
- OS: `ArchLinux`
- Architecture `x86_64`

**Comment by geeeeeeeeek** [comment]
Can you confirm it's network related or not? It seems my code could not possibly have any impact on that.

**Comment by jediofthecode** [comment]
I do not have the issue on my phone when connected to the same Wi-FI, so I suspect it may be an issue with the web implementation of wechat, and not your electron based client.

**Comment by geeeeeeeeek** [comment]
@jediofthecode Sometimes you just need to reload the app after connection broken. I can do nothing about it.
