### ISSUE TITLE
Linux KDE系统托盘图标是一个白色的方框

### ISSUE THREAD

**Issue by mengzdsd** [geeeeeeeeek/electronic-wechat#160]
First, make sure your issue is strictly related to the ***Electronic WeChat*** project. If it's a question or feature request, you can remove the template below.

#### Description
打开之后，系统托盘图标显示为一个白色的方框。

![screenshot_20160428_091345](https://cloud.githubusercontent.com/assets/17825639/14872829/94d2610c-0d22-11e6-88b5-204fb39eb34c.png)

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.37.6`
- Version of Node.js (run `$ node --version`): `v6.0.0`
- OS: `openSUSE Leap`
- Architecture `x86_64`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by geeeeeeeeek** [comment]
I'll look into that.

**Comment by mengzdsd** [comment]
@geeeeeeeeek 我使用的是KDE 5桌面环境。

**Comment by xgdgsc** [comment]
Changing icon size can solve this problem: https://github.com/sindresorhus/caprine/issues/58 , https://github.com/sindresorhus/caprine/commit/c150350d547070b56db7f576ed7a6ff23c3d0a3d

**Comment by geeeeeeeeek** [comment]
@xgdgsc Thanks so much. Will fix it in the next release.

**Comment by geeeeeeeeek** [comment]
@xgdgsc Fixed. Please checkout.

**Comment by xgdgsc** [comment]
Tested, works quite well. Thanks!
