### ISSUE TITLE
一种在 Windows 下给 electronic-wechat 添加快捷方式的方法

### ISSUE THREAD

**Issue by geekxiaoke** [geeeeeeeeek/electronic-wechat#162]
### 一种在 Windows 下给 electronic-wechat 添加快捷方式的方法
不太喜欢每次打开 electronic-wechat 都得用命令行，所以用批处理弄了一个快捷方式，在此介绍一下。
新建一个 txt 文档，改文件名为 electronic-wechat.bat ，编辑，写入以下内容：
```
cd "c:\Program Files (x86)\Tencent\electronic-wechat"
npm start
```
保存，双击该批处理文件即可打开 electronic-wechat。
**这里的路径"c:\Program** Files **(x86)\Tencent\electronic-wechat"请根据自己的情况更改。**

---

但是还存在一个问题，以上批处理文件会附带打开一个命令行窗口，如果想要隐藏这个命令行窗口，请继续看下文。
在同一目录下，新建一个 txt 文档，更名为 runbat.vbs ，编辑，写入以下内容：
```
set ws=wscript.createobject("wscript.shell")
ws.run "electronic-wechat.bat /start",0
```
保存，然后双击该 vbs 文件，即可隐藏运行命令行窗口。
以上。

**Comment by geeeeeeeeek** [comment]
@geekxiaoke 竟然还有在 Windows 上跑 electronic-wechat 的好感动…不过或许你可以直接打包，应该会生成exe的吧？

**Comment by geekxiaoke** [comment]
@geeeeeeeeek 之前试过打包，失败了，没有进一步折腾，发了 issues ，你回复说 Windows 下面不管，:( 。

**Comment by geeeeeeeeek** [comment]
@geekxiaoke 因为我平时只用两台Mac和一堆Linux...多一个平台多很多坑..反正不会维护还不如不支持..
