### ISSUE TITLE
聊天气泡右键复制无效

### ISSUE THREAD

**Issue by GitatHub** [geeeeeeeeek/electronic-wechat#164]
#### Description
1. fedora 下， 聊天记录里面右键复制无效，无法进入剪贴版
2. fedora下，聊天输入窗口里无法右键
3. fedora 下， ewechat窗口打开后，如果系统自动锁屏，屏幕将无法进入节能模式。屏幕总是被自动点亮。

#### Specifications

- Version of Electron 1.2.0
- Version of Node.js (run `$ node --version`): `v0.0.0`
- OS: `<OS>` FEDORA 23 X64

**Comment by holmeszyx** [comment]
ubuntu也是一样

**Comment by geeeeeeeeek** [comment]
I'll look into that.

**Comment by GitatHub** [comment]
如果消息是一张图片，右键只能下载，没有转发等选项。

**Comment by geeeeeeeeek** [comment]
@GitatHub Web WeChat 本身就不支持这个功能。

**Comment by GitatHub** [comment]
哦 谢谢

**Comment by geeeeeeeeek** [comment]
搞定了，需要Flash支持，代价是安装包要增加25M，你们真想要这样吗…

**Comment by GitatHub** [comment]
FLASH。。。。
那还是算了吧。。。
伟大的HTML5做不到嘛？

**Comment by geeeeeeeeek** [comment]
@GitatHub 当然做得到，你得问微信怎么想的。。

**Comment by holmeszyx** [comment]
安装包大点还好, Flash什么管他的.. 
功能没有才蛋疼. 可怜我等linux用户
能给个可选项否, 愿下大包的下大包, 不愿下的,就用正常的包.

@geeeeeeeeek 好像还有个小问题, 在升级后,在多显示器下, 每次打开应用,窗口都会偏向显示器的一个边缘. 以前的版本记得应该是居中的. 也是ubuntu下.

**Comment by geeeeeeeeek** [comment]
@holmeszyx Linux下不可以用快捷键复制吗？

**Comment by holmeszyx** [comment]
@geeeeeeeeek  新版好像可以ctrl c了!  多谢啊!

以前的版本, 只能从外面copy到wechat里面, wechat里面, 怎么ctrl c都没效....

**Comment by geeeeeeeeek** [comment]
@holmeszyx 其实一直是可以的…

**Comment by geeeeeeeeek** [comment]
我先 close 了。把 Flash 打包进去 repo 和安装包实在太大了，等设置中心写好了之后让用户自己填写 Flash 路径就好了。
