### ISSUE TITLE
对Ubuntu状态栏图标以及应用程序图标的优化

### ISSUE THREAD

**Issue by RegisWang** [geeeeeeeeek/electronic-wechat#166]
在Ubuntu下，状态栏图标使用的是resources/app/assets/icon.png，但是在1.2.0版本中提供的图标并不是很好看。同时应用没有提供在Ubuntu下可用的.desktop文件，导致在Ubuntu中运行时，launcher上是一个问号。
http://pan.baidu.com/s/1qY1kHYk
中有两个图标：

- icon.png是用来在ubuntu状态栏上显示的，和系统图标风格一致；
- desktop_icon.png是用作desktop文件的图标的，是官方原版图标；

建议的存放位置都是resources/app/assets/路径下，建议提供一个简单的WeChat.desktop文件：
```
[Desktop Entry]
Version=1.2.0
Name=WeChat
Comment=Connecting a half billion people
Keywords=chat;talk;im;message;
Exec=/path-to/electronic-wechat-linux-x64/electronic-wechat
Icon=/path-to/electronic-wechat-linux-x64/resources/app/assets/desktop_icon.png
Categories=InstantMessaging;Network;
Terminal=false
StartupNotify=true
Type=Application
```

**Comment by geeeeeeeeek** [comment]
@RegisWang 之所以 Linux 下使用彩色 tray icon 是状态栏有深色和浅色之分，所以灰度的图标在深色 or 浅色背景下会很诡异。
![image](https://cloud.githubusercontent.com/assets/7262715/15329759/726e3ba8-1c8c-11e6-8c87-e936b33a54c7.png)

![image](https://cloud.githubusercontent.com/assets/7262715/15329675/1d4bd3a6-1c8c-11e6-92ec-7914e68b4023.png)

至于 Dock 图标一直是彩色的呀…问号的问题在很早的版本就被修复了…

你看看能不能解决你的问题，`*. desktop`配置我不熟悉，你可以发一个Pull Request。
