### ISSUE TITLE
Ubuntu 16.04 托盘不显示图标

### ISSUE THREAD

**Issue by whirlwind110** [geeeeeeeeek/electronic-wechat#169]
ubuntu 16.04 unity
1.右上角托盘不显示图标，15.10下正常。
2.消息提醒变成弹窗。而不是原来Notify-OSD 的气泡

**Comment by geeeeeeeeek** [comment]
I'll look into that.

**Comment by ferstar** [comment]
可以尝试安装一下`libappindicator1`组件

**Comment by geeeeeeeeek** [comment]
@whirlwind110 参考 @ferstar 的回答，Electron 显示托盘图标需要这个组件
