### ISSUE TITLE
启动的时候卡在四个球 转啊转 但是打不开登录页

### ISSUE THREAD

**Issue by ruizhipeng** [geeeeeeeeek/electronic-wechat#170]
如果有时间请帮忙解决 非常感谢 我的系统是archlinux  electron版本 0.37.5-1

**Comment by geeeeeeeeek** [comment]
说明网络不好应用没加载完。。。

**Comment by ruizhipeng** [comment]
thanks

**Comment by squallliu** [comment]
遇到了一样的问题，但是用浏览器没问题，老版本也没有问题

**Comment by squallliu** [comment]
自己去掉了splash就可以了，wx-rendered时间没有触发，实际上登录二维码界面已经有了
