### ISSUE TITLE
无缘无故信息发不出去.遇到第二次了

### ISSUE THREAD

**Issue by eleveni386** [geeeeeeeeek/electronic-wechat#173]
我是下载的1.2.0的deb包. 直接使用的. 在使用时, 用着用着, 信息就发不出去. 不知道如何debug. 以及日志在哪里. 
另外, 是否可以考虑, 在二维码页面上,增加一个刷新二维码按钮. 这样当二维码过期是, 可以手动刷新. 而不用退出应用,再进入应用这样.

**Comment by geeeeeeeeek** [comment]
1. 菜单里有刷新，也有快捷键。
2. 信息发布出去应该是网络断了，微信自己的 app 写成这样我也很无奈…
3. 会考虑这个建议，虽然现在有自动刷新，但感觉需要更加激进一些…

**Comment by ripples-alive** [comment]
表示出现过好几次不知道为啥图片就是发不出去，刷新就好了。。。

话说二维码自动刷新可以做成切到前台是未登录就自动刷一下么。。。

**Comment by geeeeeeeeek** [comment]
@ripples-alive 现在加了启动超时重试，试试？如果连接没断的话二维码自己就会刷新的。每次 focus 刷新一下感觉有点诡异。可以先用快捷键。
