### ISSUE TITLE
Linux 下 启动后一直显示 splash window 无法打开主窗口

### ISSUE THREAD

**Issue by wenLiangcan** [geeeeeeeeek/electronic-wechat#174]

**Comment by ruizhipeng** [comment]
感觉之前版本反倒比这个要好一些 我的也进不去

**Comment by toddleo** [comment]
我也遇到了同样的问题. 无论是pacman上的二进制版本还是自编译的版本都一直"Starting App"

**Comment by ruizhipeng** [comment]
等作者修复吧

**Comment by zzkristy** [comment]
我在Mac下也遇到这个问题

**Comment by geeeeeeeeek** [comment]
你们能调试一下吗…我拉到 master 分支之前在 Ubuntu 测试过没有这个问题…

有时候确实进不去，因为网络的原因，和这个 Splash Window 没关系吧，要搁旧版本也一样吧

**Comment by ruizhipeng** [comment]
额 旧版本我这边启动后会会自动进入后台 然后手动点出来刷新就有二维码了

**Comment by geeeeeeeeek** [comment]
你现在也可以直接用快捷键或菜单刷新..看来这个问题那么严重我加个超时重试吧

**Comment by wenLiangcan** [comment]
@geeeeeeeeek 找到问题了，原来是我没有安装 `pinyin` 这个依赖。

@toddleo 你试一下 `AUR` 上的这个包看看 ： https://aur.archlinux.org/packages/electronic-wechat-git/

**Comment by geeeeeeeeek** [comment]
@wenLiangcan 方便维护一下 [系统支持矩阵](https://github.com/geeeeeeeeek/electronic-wechat/wiki/System-Support-Matrix) 吗？你可以新建一栏镜像源写在备注里。

**Comment by wenLiangcan** [comment]
@geeeeeeeeek 我添加了相关信息，你看一下我的格式可不可以？

另外，我特意标明了包的名字是因为 `AUR` 上还有另外一个不由我维护的名为 [electronic-wechat](https://aur.archlinux.org/packages/electronic-wechat/) 的包，这个包是跟随官方版本号更新的，而我维护的有 `-git` 后缀的包直接从最新的 git 仓库源代码进行打包。

**Comment by geeeeeeeeek** [comment]
@wenLiangcan 我干脆[新增了一个表格](https://github.com/geeeeeeeeek/electronic-wechat/wiki/System-Support-Matrix#%E7%A4%BE%E5%8C%BA%E8%B4%A1%E7%8C%AE%E7%9A%84%E5%AE%89%E8%A3%85%E5%8C%85)，列出所有社区贡献的包。上一个表格中的验证版本你填一下你的Arch Linux版本吧。真的太感谢啦！

@1dot75cm @hexchain 欢迎继续更新第三方软件仓库的镜像~

**Comment by hexchain** [comment]
@wenLiangcan electron 不同版本间 API 有差异，aur/electron 并不一定等于此项目所需的 electron 版本。

**Comment by wenLiangcan** [comment]
@geeeeeeeeek Arch Linux 是采用滚动更新的发行版，准确说没有具体的版本号，虽然它的安装镜像会有具体的更新日期，而我的系统是两三年前安装的，采用安装镜像的更新日期也不妥，所以我觉得要么像现在留空或者用我最近一次打包验证的日期。

@hexchain 这一点我知道。不过一开始打包我是为了自己方便，所以用了 `-git` 结尾作为包名，让它显得没那么正是，让想要严谨对待的人去维护 `electron-wechat`。

首先，我安装了好几个 electron 的软件，使用独立安装的 electron 可以减少一些空间的使用。其次，去掉 electron 的打包可以减少打包时间。

当然，如果你认为 `AUR` 是公共的社区，上面的包都应该严谨对待，你愿意维护的话，我可以放弃这个包。

**Comment by geeeeeeeeek** [comment]
@wenLiangcan @hexchain 有两个包其实没什么问题，一个对应 release，一个对应 git 。至于 electron 版本我隔几个发布才会更新一次，就是不知道 aur/electron 多久更新。

**Comment by wenLiangcan** [comment]
@geeeeeeeeek aur/electron 理论上永远都是最新版的 Electron

**Comment by hexchain** [comment]
最近 atom 项目恰好受到更新 electron （见 https://github.com/atom/atom/pull/11348 ，过程比较漫长） 的影响，以及各种 nodejs 程序都对 electron 有不同版本的需求。electron 本身仍然处于 0.x.y 的版本，按照 [semver](http://semver.org/#spec-item-4) 的说法，不应认为 API 稳定，任何时候都可能产生变更。因此我个人认为最好不要共享这类组件。

另外，aur/electron 已经过时有一段时间了。

**Comment by toddleo** [comment]
@wenLiangcan 多谢, 更新后已经可以用了
