### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by prenfic** [geeeeeeeeek/electronic-wechat#175]
First, make sure your issue is strictly related to the ***Electronic WeChat*** project. If it's a question or feature request, you can remove the template below.

#### Description
1. To be able to change the font of messages
2. is it possible to manual change the fonts of emoji among google emoji, apple emoji, LG or sth else??? --> actually this's just my wishful thinking due to the recent changes of emoji on my iPhone

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.37.6`
- Version of Node.js (run `$ node --version`): `v6.0.0`
- OS: `<OS>`10.11.4
- Architecture `<ARCH>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by geeeeeeeeek** [comment]
Too heavy, won't do.
