### ISSUE TITLE
关于多开

### ISSUE THREAD

**Issue by lmnsg** [geeeeeeeeek/electronic-wechat#176]
可不可以开发一个多开的功能呢？
因为工作有另一个微信，自己私人也有一个，所以蛮想要这个功能的

**Comment by RegisWang** [comment]
有多开功能啊，再启动一次应用就又是一个新的扫码登陆框。

**Comment by ripples-alive** [comment]
@RegisWang 这跟系统以及启动方式啥的有关吧，Mac 上封装好的 `.app` 貌似是没法多开的。。。

**Comment by geeeeeeeeek** [comment]
@ripples-alive 如果共用 cookies 那么显然是无法做到多开的。我之前 npm start 跑在 electron 进程和 build 之后跑在 electronic-wechat 倒是可以做到两个分离的 session 和 cookies。话又说回来了，实现多 session 登录还是挺麻烦的…
