### ISSUE TITLE
Electronic Wechat Helper占用CPU持续较高

### ISSUE THREAD

**Issue by geeyan** [geeeeeeeeek/electronic-wechat#183]
#### Description
如题。
![image](https://cloud.githubusercontent.com/assets/4083759/15141097/0ec65470-16d1-11e6-8d4b-8f418a0af050.png)
![image](https://cloud.githubusercontent.com/assets/4083759/15141119/24b565dc-16d1-11e6-8ef2-266aafe58e16.png)
使用的是mac下的electronic-wechat，版本是v1.2.0 (2016.04.21)

#### Specifications
- Version of Electron (run `$ electron --version`): `v0.0.0`
- Version of Node.js (run `$ node --version`): `v4.2.1`
- OS: `OS X`
- Architecture `<ARCH>`
- Stack trace from the error message (if any)

**Comment by geeeeeeeeek** [comment]
你要这么想，Chrome的资源占用，能小的了么……

脑补一下 Chrome Helper

**Comment by geeyan** [comment]
@geeeeeeeeek 不不不，chrome这边并没有太大占用啊。。
![image](https://cloud.githubusercontent.com/assets/4083759/15146607/064dc6a2-16ef-11e6-8cab-5257fe6a56af.png)

用上一版的EW也没有这个问题。

**Comment by geeeeeeeeek** [comment]
@geeyan 那我有空做下 profile ，不过我好像没遇到资源占用的问题

![image](https://cloud.githubusercontent.com/assets/7262715/15146788/dabc2604-16ef-11e6-9057-0f5f12668956.png)

**Comment by geeyan** [comment]
ok，3ks，辛苦了，期待~ 
天热了，今天手掌有被蒸热感=。=~

**Comment by ferstar** [comment]
哈哈, chrome本来就是耗电大户, 换safari后立马夏转秋

**Comment by geeeeeeeeek** [comment]
@geeyan 

FYI, https://github.com/electron/electron/pull/5378.
