### ISSUE TITLE
字体显示问题（建议）

### ISSUE THREAD

**Issue by houkensjtu** [geeeeeeeeek/electronic-wechat#185]
#### Description
我使用Gentoo发行版运行本APP时发现中文的字体有出现不一致的问题（部分字呈现一种字体，另一部分呈现另一种字体）。这应该是由于我的Gentoo box没有设置比较完善的字体匹配机制（相对的，最近的Ubuntu等发行版应该已经预先配置好了比较好用的字体配置，所以不会出现此问题。）

虽然这是一个仅发生在个别发行版的问题，但是我想是不是可以把字体内嵌到App里面，而不要依赖于运行主机的X window系统，这样也从一种角度提高了APP用户体验的一致性。

附：我运行时的截图: https://goo.gl/photos/7i2nDekkZJ8yByvh8

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.37.8`
- Version of Node.js (run `$ node --version`): `v0.12.6`
- OS: `Gentoo linux`
- Architecture `x86_64`

**Comment by arrowrowe** [comment]
[![@houkensjtu 运行时的截图](https://lh3.googleusercontent.com/QqnwtBQvidK-sj0Mf8nNlHdqaDuRA7OL5NklwqTucVnUtXWzWd6ONh_KLSybQ-tdKfnzTEgAZWhTXwWGpKKnKHEst3oXNZDUwK7uqQNkhOksJCEEIYRXBjC3SpCY-ZpLGbtmSlDB9qKgxkY8yPH-URS8Q33-losdpO9fv6NanJ-FJ1zYpPf45Shlme23g1N4zm2HTjNmuQvgu9tCih8GyCogINGOpFlofVNcv261ArA4nP-DVrmRlK2s4cp944yoclPvumsxlTTX84tdO7e2ljaiwmpgYtPPZ4BnDaX6vvXHJrdusOyKMltb7Zh02Xf5O4-5k_f8uDd4is5ANTmIQO3IG-8kqdE0qH7TAou9NT-f6xQbK09A4-lK7bSVXfNfuwJVt4hup39N43CeqtxlabglJz4-G4GgfwBqV3fCCxF3Ahp3gczfADJF2sPyUe2Ls-2Y079KWcS-sfWoS-YFdg34hqT7f6P_obsXIbRSbRTnHmwyZ9hjsEhB-vEG2CJEdL1LtkKJ6PR2a3nnWveB0Yz3bVZyDy17tgg598Ec3u-iaLxggDHhdfaOFbpeSiJmCIZs_Da1RowcWfTjCeDgPsIGVRjcADE=w518-h251-no)](https://goo.gl/photos/7i2nDekkZJ8yByvh8)

**Comment by geeeeeeeeek** [comment]
@houkensjtu @arrowrowe 微信的字体会一直向下 fall back ，如果前面的字体都没有的话会使用 `sans-serif` 字体族的系统默认字体，所以我不是很清楚为什么会出现这个问题

```
"Helvetica Neue",Helvetica,"Hiragino Sans GB","Microsoft YaHei","微软雅黑",Arial,sans-serif
```

**Comment by arrowrowe** [comment]
(我只是路过贴个图的...)

**Comment by geeeeeeeeek** [comment]
@arrowrowe 是你系统`sans-serif`默认字体的字符集不全吧？你试试安装字体试试。暂时不考虑内嵌字体。

**Comment by xgdgsc** [comment]
好像archlinux装了wps会影响本程序的字体，怎么改回来。
