### ISSUE TITLE
Chinese words problem 

### ISSUE THREAD

**Issue by blackPantherOS** [geeeeeeeeek/electronic-wechat#187]
Please add multilanguage support - maybe just english-; because blackPanther OS users does not understand the chinese words and can't using now.

**Comment by geeeeeeeeek** [comment]
@blackPantherOS Sorry for that. Multi-language support will come at 2.x versions. Maybe a month later. You can modify my code for now.

**Comment by geeeeeeeeek** [comment]
@blackPantherOS Now, the texts for message recall and mention user are in English. The sharing menu is still in Chinese. The whole i18n thing will be done in 2.x. But I believe the current version will not block your reading.

BTW, is there any English speakers using this app?
