### ISSUE TITLE
mute 的信息还是会弹出消息推送

### ISSUE THREAD

**Issue by taoalpha** [geeeeeeeeek/electronic-wechat#189]
赞赞! 似乎 mute 的组的消息依然会推送~ 没判断 mute? :) 要是再能有个截图就更棒了哈哈

**Comment by geeeeeeeeek** [comment]
mute 的组是不会有消息提示的。但如果登录 Web WeChat 时没有 mute 改组，在其他客户端 mute 之后这个状态不会同步到 Web WeChat。
