### ISSUE TITLE
使用统一的窗口风格

### ISSUE THREAD

**Issue by wenLiangcan** [geeeeeeeeek/electronic-wechat#19]
现在使用的是系统原生的窗口，看截图在 OSX  下挺好看的，不过在 Linux 下不太好看。不知可不可以设计一个统一的窗口风格？

不知 Electron 支不支持自定义的窗口风格，不过我知道 Node Webkit 是可以的，比如这是 [Popcorn Time](https://github.com/popcorn-official/popcorn-desktop) 的窗口 ：
![selection_007](https://cloud.githubusercontent.com/assets/1244181/13370618/30f791ca-dd48-11e5-95b1-edcb26ecde37.png)      

这是我系统的原生窗口：

![selection_008](https://cloud.githubusercontent.com/assets/1244181/13370624/65fd434c-dd48-11e5-9e7c-51a78ae8a1a8.png)

**Comment by geeeeeeeeek** [comment]
据我所知是没有的，你可以给electron发个feature request。还有我记得Linux下应该是不会显示菜单的吧？

**Comment by arrowrowe** [comment]
re @geeeeeeeeek: 我猜是 gnome 的锅... cc gnome 用户 @spacemeowx2

**Comment by wenLiangcan** [comment]
@arrowrowe 我用的是 KDE。
@geeeeeeeeek 显示菜单大概是因为我没有打包直接用独立安装的 Electron 启动的原因吧（难道非要打包才能隐藏菜单？）。既然 Electron 没有这个特性那我关闭这个 issue 吧。

**Comment by fritx** [comment]
@wenLiangcan 注意到ta这个nw应用设了`frame:false`，估计是自己用web实现了你说的窗口样式。
你是想要自定义顶栏的意思吗？只要不显示frame，自己用web实现一个顶栏即可。
不知道你是不是这个意思？

```js
// https://github.com/butterproject/butter-desktop/blob/master/package.json
"window": {
  // ...
  "frame": false,
  // ...
}
```

**Comment by izuolan** [comment]
抱歉，再开，有个问题是我也是gnome用户，启动后会有菜单栏，怎么去掉？@wenLiangcan

**Comment by wenLiangcan** [comment]
@fritx 我说的窗口指的是有最大化/最小化按钮的那一栏，不知你说的顶栏包不包括那里？

**Comment by wenLiangcan** [comment]
@izuolan 我开了个 PR #21，不知作者会不会合并，你可以去看一下 diff 先自己修改一下。

**Comment by fritx** [comment]
@wenLiangcan 没错我说的就是最大化/最小化这一栏 那个就是`frame`

**Comment by geeeeeeeeek** [comment]
这个倒问题不大，可以作为一个low priority的feature。我比较关心Linux下的menu怎么办，无法优雅地显示。

**Comment by wenLiangcan** [comment]
@fritx 明白了
@geeeeeeeeek 那我重新打开这个 issue 吧。“雅地显示 menu”是什么意思？我提交了一个 PR #21 直接去掉了非 OSX 平台的菜单栏，你觉得怎么样？或者也可以只保留 `autoHideMenuBar: true` ，这样默认会隐藏菜单栏，可以按 Alt 键调出。

**Comment by geeeeeeeeek** [comment]
auto hide之后osx状态栏上也不显示菜单么？我希望是osx显示菜单，Linux自动隐藏，如果不能用JSON对象配置应该也有相应的编程接口吧。

现在菜单倒是无所谓，但后面回复机器人、更新检查接进来没有菜单入口就找不到了。

**Comment by wenLiangcan** [comment]
@geeeeeeeeek 不太清楚 `autoHideMenuBar` 在 OSX 上的行为，也许可以这样： `autoHideMenuBar: remote.process.platform != "darwin"` ?

**Comment by geeeeeeeeek** [comment]
Fixed in #21. 目前OS X显示菜单，Linux下默认隐藏。暂时没有打算自己绘制边框。
