### ISSUE TITLE
公众号消息无法更新

### ISSUE THREAD

**Issue by ALBluestockings** [geeeeeeeeek/electronic-wechat#191]
First, make sure your issue is strictly related to the ***Electronic WeChat*** project. If it's a question or feature request, you can remove the template below.

#### Description
v1.2.0
公众号消息无法更新

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- Version of Node.js (run `$ node --version`): `v0.0.0`
- OS: `<OS>`
- Architecture `<ARCH>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by geeeeeeeeek** [comment]
微信 WebApp by design 就是这样的。
