### ISSUE TITLE
登录界面缩放不正确

### ISSUE THREAD

**Issue by eleveni386** [geeeeeeeeek/electronic-wechat#193]
First, make sure your issue is strictly related to the ***Electronic WeChat*** project. If it's a question or feature request, you can remove the template below.

#### Description

登录时. 偶尔会这样. 昨天还是好好的. 今天什么代码都没改动. 然后就这样了.

![](http://paste.ubuntu.org.cn/i4213412)

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- Version of Node.js (run `$ node --version`): `v4.2.6`
- OS: `<Ubuntu 16.04 LTS>`
- Architecture `<x86_64>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by geeeeeeeeek** [comment]
@eleveni386 是这样的，要 DOM 加载完成之后才会执行 CSS 注入，如果有一个资源没有加载出来可能会出现这个情况。
