### ISSUE TITLE
Electronic WeChat version show incorrect number

### ISSUE THREAD

**Issue by donly** [geeeeeeeeek/electronic-wechat#196]
Hi, I like this app on OS X, when I using it I found some issues

#### Description

1. Download the latest release from [v1.2.0](https://github.com/geeeeeeeeek/electronic-wechat/releases).
1. Install it by drag `Electronic WeChat.app` to `Applications` folder.
1. Click ***Electronic WeChat*** app menu-> About Electronic WeChat, it shows `版本 0.37.6 (0.37.6)`
1. Click Help menu -> `Check for New Release`, shows `No Update Available, You are using the latest version(v1.2.0).` 

And one more issue, right click mouse on AppIcon in Dock, select `Exit`, it can't exit.

**Comment by geeeeeeeeek** [comment]
Fixed in `master`. Please checkout.

**Comment by donly** [comment]
Thank you, ge9k man. After I upgrade to `1.3.0`, the version number is right, but the one more issue, right click mouse on AppIcon in Dock, select Exit, it can't exit.

**Comment by geeeeeeeeek** [comment]
@donly Yes. I'll look into that.

**Comment by donly** [comment]
And I found the operation twice could exit

**Comment by geeeeeeeeek** [comment]
@donly If chat window is present, hide it. If not, quit app.
