### ISSUE TITLE
Cannot npm start, has errors

### ISSUE THREAD

**Issue by iVanlIsh** [geeeeeeeeek/electronic-wechat#197]
> fs.js:634

>  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

>  Error:`` ENOENT: no such file or directory, open '/Users/ivan_l/GitHub/electronic-wechat/node_modules/electron-prebuilt/path.txt'

>     at Error (native)
>     at Object.fs.openSync (fs.js:634:18)
>     at Object.fs.readFileSync (fs.js:502:33)
>     at Object.<anonymous> (/Users/ivan_l/GitHub/electronic-wechat/node_modules/electron-prebuilt/index.js:4:42)
>     at Module._compile (module.js:541:32)
>     at Object.Module._extensions..js (module.js:550:10)
>     at Module.load (module.js:456:32)
>    at tryModuleLoad (module.js:415:12)
>    at Function.Module._load (module.js:407:3)
>    at Module.require (module.js:466:17)

**Comment by geeeeeeeeek** [comment]
安装问题，重新 `npm insall`.
