### ISSUE TITLE
Settings Panel

### ISSUE THREAD

**Issue by geeeeeeeeek** [geeeeeeeeek/electronic-wechat#199]
提供各种功能开关及设置。将在 electronic-wechat v2.0 中发布。

**Comment by eleveni386** [comment]
开森.  期待2.0了.

**Comment by timothyyang96** [comment]
@geeeeeeeeek 什么时候支持听取语音？

**Comment by timothyyang96** [comment]
@geeeeeeeeek 还有个问题，在界面上选了关闭声音后，还是有声音

**Comment by geeeeeeeeek** [comment]
@timothyyang96 自古以来就支持语音。那个 notification 的问题需要再看下。

**Comment by timothyyang96** [comment]
@geeeeeeeeek 为什么我语音只显示，但不能播放
