### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by iVanlIsh** [geeeeeeeeek/electronic-wechat#205]
#### Description

为什么，我手动，可以把包下下来而且很快，npm install 就一直超时，然后fetch failed。btw，两个包下下来以后应该装哪儿😂

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.36.0`
- OS: `<10.11.5>`
- Stack trace from the error message (if any)

``` 
npm ERR! fetch failed https://registry.npmjs.org/electron-packager/-/electron-packager-7.0.1.tgz
npm WARN retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:1080
npm ERR! fetch failed https://registry.npmjs.org/pinyin/-/pinyin-2.7.3.tgz
npm WARN retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:1080
```

**Comment by eleveni386** [comment]
我在下载electron-1.1.0的时候一直都是连接被重置. 最后我去看了下electron的download.js 找到了他的cache位置. 自己手工wget下来回来 丢到他的cache目录下. 就轻而易举搞定了. 
你可以试试 ~/.electron/ 放到这个下面.

**Comment by geeeeeeeeek** [comment]
@iVanlIsh 可以试试 cnpm 。README 有传送门。要学会科学上网啊！

**Comment by iVanlIsh** [comment]
我ss一直开着啊。。😂

**Comment by geeeeeeeeek** [comment]
@iVanlIsh 总是真的是网络的问题…你试试 cnpm 吧…

**Comment by iVanlIsh** [comment]
好。。orz

**Comment by ripples-alive** [comment]
@iVanlIsh ，命令行一般默认不会代理的吧 -_-#。。。

**Comment by ray26** [comment]
貌似命令行要自己配置吧，而且为何不用taobao的cnpm

**Comment by kingcinlee** [comment]
DOWN不下来... 醉了.能不能具体说说怎么下的.我是个小白. - _- |

**Comment by ripples-alive** [comment]
命令行的话，装个 proxychains，配置下 ss 的地址，然后 proxychains + 原来的命令就好了。。。
话说为啥非要自己打包，又不改代码，直接下打包好的不好么。。。
