### ISSUE TITLE
ubuntu14.04，右键可以复制消息内容但是粘贴不行

### ISSUE THREAD

**Issue by lzjqsdd** [geeeeeeeeek/electronic-wechat#206]
#### Description
复制消息内容，采用右键复制复制不到，但是使用Ctrl+C/V是可以复制粘贴的

#### Specifications

- Version of Electron (run `$ electron --version`): `v1.3.0`
- OS: `<Ubuntu14.04>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by geeeeeeeeek** [comment]
@lzjqsdd 这是一个已知的问题。请见 #164 的讨论。如果要实现的话需要把 Flash 一起打包进来，这样安装包就太大了。在 v2.x 中，会新增设置页，让用户手动指定 Flash 地址，这样就可以使用了。现在先用快捷键吧…
