### ISSUE TITLE
Ubuntu 16.04无法创建快捷方式

### ISSUE THREAD

**Issue by Acris** [geeeeeeeeek/electronic-wechat#207]
打开electronic-wechat以后，在Launcher图标上点击右键，无论是选择Lock to launcher，还是Add to Dash，重启以后固定的图标会消失，Dash中也没有快捷方式的图标。

尝试过自己写.desktop文件，重启后Dash中仍然无法看到快捷方式。

cat ~/.local/share/applications/electronic-wechat.desktop 
[Desktop Entry]
Version=1.0
Type=Application
Name=Electronic WeChat
Icon=electronic-wechat
Path=/home/acris/Software/Electronic WeChat
Comment=A better WeChat on Mac OS X and Linux
Exec=electronic-wechat
Categories=Network;
Terminal=false
StartupWMClass=electronic-wechat

**Comment by Acris** [comment]
此问题以解决。

原因是因为我把程序放在Electronic WeChat文件夹下，文件夹名称含有空格。

将文件夹修改为Electronic-WeChat后即可正常创建快捷方式。

**Comment by geeeeeeeeek** [comment]
@Acris 请问 `Electronic WeChat` 是你自己创建的吗？因为我记得特地优化了 Linux 下的文件名，应该是没有空格的？

**Comment by Acris** [comment]
@geeeeeeeeek 对的，原本解压后的文件夹名称是 `electronic-wechat-linux-x64` ，我自己修改成 `Electronic WeChat` 的 （ 算是强迫症吧，哈哈）
