### ISSUE TITLE
MAC版的包无法下载,各种梯子试了都没用

### ISSUE THREAD

**Issue by SunnyLinSD** [geeeeeeeeek/electronic-wechat#208]
我和我的朋友都尝试在不同网络下,用各种梯子的方法下载mac版的安装包,但是下载时的速度都非常慢,请问能上传一个网盘版本吗?

**Comment by geeeeeeeeek** [comment]
@SunnyLinSD 如果有人愿意维护一个网盘版本那最好，但这样比较麻烦，因为现在的发布都是 CI 自动打包的。

**Comment by ray26** [comment]
@geeeeeeeeek 我来维护可以吗

**Comment by geeeeeeeeek** [comment]
@ray26 那太感谢了。可以顺便更新一下[ Wiki 中软件仓库](https://github.com/geeeeeeeeek/electronic-wechat/wiki/System-Support-Matrix)。我不知道你打算怎么做？手动上传么？我觉得国内的网盘应该没有提供相关的 API 吧。

**Comment by ray26** [comment]
有想过的同步方法

**Comment by ripples-alive** [comment]
@geeeeeeeeek  不过国内网盘都各种可以装自动同步，也勉勉强强算自动化吧 😂

**Comment by ray26** [comment]
你误解我的意思了，不是软件，有人破解了api

**Comment by ripples-alive** [comment]
@ray26 ，哦，对，你一说我想起来了，好像是有人维护着来着的，当时看能不能破限速的时候看过几眼 -_-#

**Comment by ray26** [comment]
@geeeeeeeeek 麻烦提供一下ci编译之后的输出路径

**Comment by micln** [comment]
放到七牛上呢？

**Comment by ripples-alive** [comment]
(>_>) 感觉好主意啊。。。

**Comment by ray26** [comment]
@micln 好主意

**Comment by geeeeeeeeek** [comment]
@ray26 `dist` 下会有三个 tar ，你可以看下 tar-all 的脚本。话说微信红包我想6.1儿童节发个 release 修一下 bugly 上的 bug :)

**Comment by ray26** [comment]
@geeeeeeeeek 好啊(*^◎^*)，儿童节和miui8抢风头

**Comment by geeeeeeeeek** [comment]
@ray26 @ripples-alive 已经把你们加到了 collaborator 里面…最近比较忙可能出现不会那么频繁…

注意稳定的 commit 再往 master 上推，其他修改最好还是先发 PR…以及别推到 production 上去…会触发 CI 的 release…

**Comment by ripples-alive** [comment]
😂 表示现在这玩意还不熟，不敢乱推，我要改还是发 PR 的好。。。

**Comment by ray26** [comment]
@SunnyLinSD https://github.com/geeeeeeeeek/electronic-wechat/releases  可以看最新release里面的国内分流地址，已经稳定运行了
