### ISSUE TITLE
希望去掉 OS X 双指连续两次轻触放大

### ISSUE THREAD

**Issue by FradSer** [geeeeeeeeek/electronic-wechat#213]
OS X 双指连续两次轻触 Magic Trackpad 或者连续两次轻触 Magic Mouse 会方法整个页面，希望能够去掉。

**Comment by geeeeeeeeek** [comment]
@FradSer 留一下你的 electron/ OS 版本。我这里无法复现。

**Comment by FradSer** [comment]
@geeeeeeeeek 
OS X: 10.11.5 (15F34)
直接从[这里](https://github.com/geeeeeeeeek/electronic-wechat/releases/tag/v1.3.0) 下载的 Electronic WeChat v1.3.0
