### ISSUE TITLE
节能模式 一段时间后 Crash，今晚尝试复现

### ISSUE THREAD

**Issue by MrBowen** [geeeeeeeeek/electronic-wechat#214]
先来给你 report 一下。
错误提示印象中是某关键组件，但是当时刚醒来，没记住。
查阅了 Lib/Logs 没有发现 crash 日志。
今晚尝试复现一下。

**Comment by geeeeeeeeek** [comment]
我印象里更可能是 electron 或者 chromium 的 bug，不过先等你复现，没有 log 有截图么？

**Comment by MrBowen** [comment]
我用的 Shift + Control + Com + 4，发现这里并不能上传截图。
且 OS X 没有自带的系统剪贴板功能，你懂得……
没记错的话是 electron 的问题。
我晚上试试。

**Comment by MrBowen** [comment]
自从今早的 crash 后，我发图一直报错。
“图片上传失败，请检查你的网络，abort”
已重启应用 + 重启 MBP

**Comment by geeeeeeeeek** [comment]
@MrBowen issue 里可以上传截图的，直接粘贴或者上传都可。

顺便贴一下你的 electron 和 OS X 版本

**Comment by MrBowen** [comment]
没有安装独立的 electron，只有 node 和 git。
都是之前就装过的。

从1.2.0 开始用 electronic-wechat，从 brew 安装。
后期卸载，直接从这里下的 1.3.0 的安装包。

搜索 electron 找到某 version 文件，如图， 1.1.0.
<img width="453" alt="capture d ecran 2016-05-24 a 13 05 29" src="https://cloud.githubusercontent.com/assets/17046239/15501850/41a8c974-21b0-11e6-9189-cf55bfadc2fb.png">

node -v
v4.4.4

OS X 10.11.5

PS 粘贴为成功，截图为文件拖进来的，哈哈

**Comment by MrBowen** [comment]
出门挂了三个小时的节能模式（屏保），依然没有复现。
使用 AppCleaner 完全删除 electronic-wechat，再使用 brew 安装 1.3.0。
图片上传依然不行，“图片上传失败，请检查你的网络，abort”。

要不我 ping 一下？

<img width="412" alt="capture d ecran 2016-05-24 a 17 00 09" src="https://cloud.githubusercontent.com/assets/17046239/15508785/2376ed7a-21d1-11e6-8f4d-747e556fd712.png">

**Comment by geeeeeeeeek** [comment]
@MrBowen 你 https 端口没被封吧？

另外 `brew` 怎么装 1.3.0 ？目前 `brew cask install` 安装的是1.2.0。

**Comment by MrBowen** [comment]
<img width="425" alt="capture d ecran 2016-05-24 a 17 22 36" src="https://cloud.githubusercontent.com/assets/17046239/15509541/269ea972-21d4-11e6-9983-a19dbf669c1b.png">

先给你个报错。
发生在我想退出，点图标的退出没反应，又点窗口内意见反馈下面的退出后，发生的。

**Comment by MrBowen** [comment]
![capture d ecran 2016-05-24 a 17 24 35](https://cloud.githubusercontent.com/assets/17046239/15509629/6bf2cb2a-21d4-11e6-8e5c-77c7e7341e9c.png)

brew 下的的确是 1.3.0 ……

我现在查查我的 https 端口。

**Comment by ripples-alive** [comment]
我印象中brew早就是1.3了……

**Comment by geeeeeeeeek** [comment]
@ripples-alive 卧槽竟然真的更新了 [Update electronic wechat to 1.3.0 (#21314)](https://github.com/caskroom/homebrew-cask/commit/1451a00d1e527586ab818b7eb796ca6849d4d198)。我一直懒得改，竟然有人帮我发 PR ，太感动了。

**Comment by geeeeeeeeek** [comment]
@MrBowen 这个我有空看一下，可能是一些奇怪的原因…

**Comment by ripples-alive** [comment]
brew 更新版本大概比较容易…大家自己用 brew 的想更新发现 brew 上版本还是旧的话目测就会自己去pr😂

**Comment by MrBowen** [comment]
@geeeeeeeeek 
我取消了所有的代理、忽略和 surge。
图的问题依旧……
可能我的网络环境特殊？
之前一直好的啊，要不测试一下？

**Comment by whq731** [comment]
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Object has been destroyed
    at Error (native)
    at SplashWindow.hide (/Users/weihanqing/Downloads/Electronic WeChat-darwin-x64/Electronic WeChat.app/Contents/Resources/app.asar/src/windows/controllers/splash.js:36:23)
    at WeChatWindow.resizeWindow (/Users/weihanqing/Downloads/Electronic WeChat-darwin-x64/Electronic WeChat.app/Contents/Resources/app.asar/src/windows/controllers/wechat.js:27:20)
    at EventEmitter.ipcMain.on (/Users/weihanqing/Downloads/Electronic WeChat-darwin-x64/Electronic WeChat.app/Contents/Resources/app.asar/src/main.js:55:25)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at EventEmitter.<anonymous> (/Users/weihanqing/Downloads/Electronic WeChat-darwin-x64/Electronic WeChat.app/Contents/Resources/electron.asar/browser/api/web-contents.js:130:25)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
