### ISSUE TITLE
更新提醒过于频繁

### ISSUE THREAD

**Issue by bluedazzle** [geeeeeeeeek/electronic-wechat#217]
#### Description

更新提醒出现太频繁，影响使用。。。

![截图](https://raw.githubusercontent.com/bluedazzle/electronic-wechat/master/screen.png)

#### Specifications

- Version of Electron (run `$ electron --version`): `v1.3.0`
- OS: `<MAC OS X 10.11.4>`
- Stack trace from the error message (if any)

``` 
null
```

**Comment by geeeeeeeeek** [comment]
你是怎么搞出那么多弹窗的……

**Comment by bluedazzle** [comment]
它自动刷新的，频率还挺高的

**Comment by MrBowen** [comment]
@geeeeeeeeek 曾经遇到过类似状况，但是没这么多。
自动刷新的
我的是未登录状态（已登录，后期自己断开）

**Comment by geeeeeeeeek** [comment]
@bluedazzle OK，知道是什么问题，找时间修一下

**Comment by geeeeeeeeek** [comment]
Fixed in latest version. Will not check update after window reloaded.
