### ISSUE TITLE
Cannot send files/images through wechat

### ISSUE THREAD

**Issue by jediofthecode** [geeeeeeeeek/electronic-wechat#218]
#### Description

I am unable to send any files or pictures through the wechat client, the images just show the loading indicator forever and never send. And with files it just says failed to upload.

#### Specifications

- Version of Electron `v1.1.0`
- OS: `Archlinux kernel 4.5.4`

**Comment by MrBowen** [comment]
Same issue...

**Comment by koya3110** [comment]
I have same issue on Web WeChat with Windows 8.1 & Google Chrome.
Receiving photo has no problem.
I can send images/photos from both up-to-date clients on iPhone 5c or Xperia A2, though.

**Comment by geeeeeeeeek** [comment]
If that is upstream related, I would rather close this issue and wait their fix come out.
