### ISSUE TITLE
希望加入窗口拖动功能

### ISSUE THREAD

**Issue by 4096void** [geeeeeeeeek/electronic-wechat#222]
#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- OS: `<OS>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by geeeeeeeeek** [comment]
@4096void 什么意思？electron v1.1.0 一下版本窗口均可拖动。electron v1.1.1 修改了 API 实现，以后会适配
