### ISSUE TITLE
osx10.11.6无法启动

### ISSUE THREAD

**Issue by ray26** [geeeeeeeeek/electronic-wechat#223]
在osx10.11.6无法启动，一直卡在starting app
![default](https://cloud.githubusercontent.com/assets/6435613/15631301/2b4c7a7a-2595-11e6-8b10-640340546e2c.jpg)
![default](https://cloud.githubusercontent.com/assets/6435613/15631302/2c99d0c6-2595-11e6-9540-1ca4600e7140.jpg)

**Comment by geeeeeeeeek** [comment]
@ray26 和 OS 版本有关吗？我 10.11.4 无法复现

**Comment by ray26** [comment]
我觉得也是，因为10.11.6现在还是开发者预览版😂😂😂

**Comment by geeeeeeeeek** [comment]
@ray26 怎么感觉你所有 OS 用的都是 dev 版本……

**Comment by geeeeeeeeek** [comment]
@ray26 我反正被 electron v1.1.1 坑惨了，又改 API 实现，这下 OS X 下窗体无法拖动了，得单独去适配

另外你看下 Web WeChat 的贴纸是否无法显示了？有没有别的办法 hack？

**Comment by ray26** [comment]
开发要求😂😂😂😂

**Comment by ray26** [comment]
官方实现了吗，我现在打不开😂😂😂

**Comment by geeeeeeeeek** [comment]
@ray26 官方…显然是不希望实现这个功能…

打不开感觉是 preload 出了问题，你可以 debug 看看卡在哪了？

**Comment by ray26** [comment]
hack ios或者android端上的通信协议，看看行不行，我等这段时间慢完之后debug一下

**Comment by geeeeeeeeek** [comment]
@ray26 好，辛苦
