### ISSUE TITLE
疑惑和建议：编译后初次启动奇慢， version文件的含义和提示关于下载图片的状态

### ISSUE THREAD

**Issue by bash-horatio** [geeeeeeeeek/electronic-wechat#224]
#### Description
第一次体验，确实是很好的项目。必须给作者以及其他Committer点赞！
##### 疑惑1：
之前听说electron很好用，构建桌面应用比较便捷。于是就想自己编译来玩玩，在master能成执行`npm install && npm start`。
```
electronic-wechat$ npm start
> electronic-wechat@1.3.0 start /home/light/Gits/APPS/electronic-wechat
> electron src/main.js
```

但是初次启动真的很慢。如下图持续了很久便转去下载release包。不知道是不是正常现象，楼主基本没玩过npm, node.js和electron（除了之前编译[atom](http://atom.io)失败过）
![eletron](https://cloud.githubusercontent.com/assets/12002153/15632303/31d98f9c-25c0-11e6-9375-fba26ecc999c.png)

##### 疑惑2 ：
下载的最新版的release包，目前是v1.3.0，但是里面的version文件却是**v1.1.0**。
```
electronic-wechat$ cat version 
v1.1.0
```
请问version文件记载的是本软件的版本还是eletron的？楼主看到release log的内容有 
* 升级 electron 至 1.1.0， Chrome 至 50.0.2661.102，Node 至 6.1.0 (感谢 @lfs1102 的贡献)

##### 疑惑3： 
release包一开始是从分流地址下的，再从github直接下，version文件内容还是v1.1.0 。不过神奇的是，两个tar包的md5值不一样？！
```
94b9947b9cd613cfdbd2b5b44769cb0a  linux-x64-clouddn.tar.gz
b20ee28eef2cd8663f6012f0529491f6  linux-x64-github.tar.gz
```

##### 建议：
刚好今天毕业照（楼主在折腾atom和electronic-wechat，没去），不少人发照片到群里。既然有客户端，就在电脑上直接下载了。图片加载，显示等都很好，还可以用鼠标拖曳图片！但是下载和下载成功，没有任何提示信息，怪怪的。平时用web版，这是浏览器干的活，所以作者暂时没考虑到吧。期待作者加个小气泡，提升用户体验！

最后，再次感谢作者以及Committers的辛勤无私的贡献！

#### Specifications
- Version of Electron
```
electronic-wechat$ ./node_modules/.bin/electron --version
v1.2.0
```
- OS: 
```
electronic-wechat$ cat /etc/issue
Debian GNU/Linux stretch/sid \n \l
```

**Comment by ripples-alive** [comment]
国内分流地址暂时不稳，能 GitHub 直接下建议还是直接下。。。

**Comment by ray26** [comment]
国内分流地址还在调试，因为现在国内分流地址里面是和github里面的release不是一个版本的，正式启用要等下一个release

**Comment by ray26** [comment]
请问你使用npm start直接编译启动也很慢吗，现在可能有这个bug

**Comment by bash-horatio** [comment]
@ray26 
是的，npm install 后 npm start，就一直停在上面的界面
bug? 另外，release 里有个eletronic-wechat，但是npm install后没出现这个，文档里也没提到……

>请问你使用npm start直接编译启动也很慢吗，现在可能有这个bug

**Comment by bash-horatio** [comment]
这样子……但是如上所述，两种包的version文件里都是v1.1.0

> 国内分流地址还在调试，因为现在国内分流地址里面是和github里面的release不是一个版本的，正式启用要等下一个release

**Comment by klyan** [comment]
Ubuntu 14.04下单独运行npm start，一直停留在Starting App这个界面上，没有报其他错误。
npm run build:linux 一直停留在 “Packaging app for platform linux x64 using electron v1.2.0”

**Comment by geeeeeeeeek** [comment]
@klyan `electron v1.2.0`... 这个版本还没有测试过，electron 一会改 API 一会改 API 实现可烦了。不如你先用 `v1.1.0` 打包一下看看？

**Comment by bash-horatio** [comment]
@klyan 虽然系统和你不一样，但是感觉关系不大。之前都是下载编译包时用的，现在v1.3.0可以npm start启动,  一切正常：
```
electronic-wechat$ npm start
> electronic-wechat@1.3.0 start /home/light/Gits/APPS/electronic-wechat
> electron src/main.js
```
> Ubuntu 14.04下单独运行npm start，一直停留在Starting App这个界面上，没有报其他错误。
npm run build:linux 一直停留在 “Packaging app for platform linux x64 using electron v1.2.0”

**Comment by geeeeeeeeek** [comment]
@bash-horatio 问题解决了？所以是v1.2.0有问题v1.3.0正常启动了？如果有问题欢迎继续更新issue。

**Comment by bash-horatio** [comment]
@geeeeeeeeek 现在v1.2.0和v1.3.0都可以正常启动
不过我想尝试打包，出现以下错误:
```
$ scripts/build-all.sh
\033[0;31mError\033[0m: you need to npm install electron-packager. Aborting.

$ npm install electron-packager
electron-packager@7.5.1 node_modules/electron-packager
├── lodash.get@4.4.1
├── rcedit@0.5.1
├── run-series@1.1.4
├── minimist@1.2.0
├── electron-osx-sign@0.3.1
├── debug@2.2.0 (ms@0.7.1)
├── resolve@1.1.7
├── extract-zip@1.5.0 (debug@0.7.4, mkdirp@0.5.0, concat-stream@1.5.0, yauzl@2.4.1)
├── plist@1.2.0 (util-deprecate@1.0.2, base64-js@0.0.8, xmldom@0.1.22, xmlbuilder@4.0.0)
├── electron-download@2.1.2 (path-exists@1.0.0, home-path@1.0.3, rc@1.1.6, mkdirp@0.5.1, nugget@1.6.2, mv@2.1.1)
├── fs-extra@0.30.0 (path-is-absolute@1.0.0, jsonfile@2.3.1, graceful-fs@4.1.5, klaw@1.3.0, rimraf@2.5.4)
└── asar@0.12.1 (chromium-pickle-js@0.1.0, commander@2.9.0, minimatch@3.0.3, tmp@0.0.28, mkdirp@0.5.1, cuint@0.2.1, glob@6.0.4, mksnapshot@0.3.0)

$ scripts/build.sh
\033[0;31mError\033[0m: you need to npm install electron-packager. Aborting.
```

这个electron-packager是怎么回事？
