### ISSUE TITLE
[RFC] 有可能支持抢红包吗？

### ISSUE THREAD

**Issue by phoenixgao** [geeeeeeeeek/electronic-wechat#229]
#### Description

有可能支持抢红包吗？

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- OS: `<OS>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by geeeeeeeeek** [comment]
@phoenixgao 
并不能。不过你可以用我另外一个开源项目。
```
https://github.com/geeeeeeeeek/WeChatLuckyMoney
```
