### ISSUE TITLE
看到geeeeeeeeek这么性感的id,Linux下的极客们不考虑在终端上用用微信聊天么~

### ISSUE THREAD

**Issue by sjdy521** [geeeeeeeeek/electronic-wechat#23]
原谅我是来贡献idea的，直接贴图：
![通过irc客户端在linux终端上使用微信](https://github.com/sjdy521/Mojo-Weixin/raw/master/screenshot/IRCShell.jpg)

**Comment by geeeeeeeeek** [comment]
uhm，终端聊天geek是geek，但确实对用户不友好吧，这个项目面向的也不只是geek…后面可能会借这个壳推出聊天机器人的接口，不过也只是附带的功能而已

我是没有打算这样做，不过你觉得有意思的话也可以开源你的代码，供有需求的Linux用户使用…

P.S. 其实我还是挺看脸的…

**Comment by viko16** [comment]
https://github.com/Urinx/WeixinBot

已经有不少类似的库咯

**Comment by geeeeeeeeek** [comment]
@viko16 我指的是支持Web Hook，有消息了向那个url发个POST，然后将回复的文本返回。

**Comment by sjdy521** [comment]
https://github.com/sjdy521/Mojo-Weixin

**Comment by sjdy521** [comment]
我现在把发送消息和接受消息api给分开了，发送的api只管发送 接收的api只管接收 太少了 刚才的讨论给我很大启发 我应该在接收消息post到指定url的时候 如果指定url返回消息就可以当作消息发送出去

**Comment by gaocegege** [comment]
@sjdy521 用过大大的MojoQQ，非常Geek :+1:

**Comment by sjdy521** [comment]
@gaocegege 多谢，现在我是被主人的id吸引过来的
