### ISSUE TITLE
Ubuntu14.04下npm start一直停留在Starting App界面，npm run build:linux 同样无法编译

### ISSUE THREAD

**Issue by klyan** [geeeeeeeeek/electronic-wechat#230]
#### Description

Ubuntu 14.04下单独运行npm start，一直停留在Starting App这个界面上，没有报其他错误。
npm run build:linux 一直停留在 “Packaging app for platform linux x64 using electron v1.2.0”

**Comment by ray26** [comment]
这个一直停留的问题发现了，正在debug

**Comment by VanicLY** [comment]
相似的问题，系统16.04，不过terminal可以运行，npm打包就一直停留着，等待了半个小时过后，错误提示name too long

**Comment by arrowrowe** [comment]
Node & NPM's version?

**Comment by ray26** [comment]
please see #224

**Comment by VanicLY** [comment]
npm 3.5.2   
nodejs 4.2.6

sorry！
还是学生，课程较多，刚刚才回复，抱歉！
