### ISSUE TITLE
对方发送的表情图片无法显示

### ISSUE THREAD

**Issue by caydyn-skd** [geeeeeeeeek/electronic-wechat#232]
#### 无法显示表情图片

![qq20160606-0 2x](https://cloud.githubusercontent.com/assets/13514092/15810506/e31ab1b6-2bd1-11e6-9f16-e2dceee12da6.png)
#### Specifications
- Version of Electron (run `$ electron --version`): `v1.3.0`
- OS: `<OS> 10.11.6 Beta (15G7a)`
- Stack trace from the error message (if any)

```
<Stack trace here>
```

**Comment by ray26** [comment]
现在表情贴纸好像又挂了

**Comment by geeeeeeeeek** [comment]
对的，微信修改了协议，没办法

**Comment by shilianghong** [comment]
@geeeeeeeeek  大神我问下，我在看那个 checkEmojiContent 的代码 然后我对比了一下 网页微信收到的cgi-bin/mmwebwx-bin/webwxsync 的 response, 

我找不到 MMDigest 和 MMImgStyle 这两个properties 
是我理解有些错误码？ 这两个properties是本就是没有的 
还是微信现在的response内没有这两个properties了？ 
因为我看到 MMImgStyle 的大小好像不会对 发送的贴纸 在网页上的显示造成什么影响  可能如果发送的是图片的话 就是
   就会影响

另外就是商店内的sticker是不是都显示不出来了 我在traffic内都找不到任何关于这个sticker的讯息

**Comment by geeeeeeeeek** [comment]
这两个properties在response返回时应该还是没有的，经过微信业务逻辑之后才有的。我是在http provider劫持了response，然后锁定了properties。

时间有点久了，记得不是很清楚了，你可以去翻一下preload的代码。现在不work了，还没仔细看过原因，但很有可能显示不了贴纸了。

**Comment by leeyiw** [comment]
遇到了同样的问题，比较影响聊天体验。

**Comment by mountainguan** [comment]
只是部分超过一定尺寸的贴图显示不了～尺寸小的可以显示，主要是长宽的问题
