### ISSUE TITLE
使用i18next本地化语言

### ISSUE THREAD

**Issue by soleo** [geeeeeeeeek/electronic-wechat#233]
#### Description

目前的项目中默认使用英语作为显示语言。有一小部分中文化的代码，但是尚未结合到项目中使用。推荐使用http://i18next.com/ 做本地化的语言处理。

**Comment by geeeeeeeeek** [comment]
@soleo 谢谢建议，i18n 确实是 2.0 的一个 task ，距离完成还有一段时间。你要有兴趣的话可以来发 PR 🙂

**Comment by FradSer** [comment]
这个赞。

**Comment by geeeeeeeeek** [comment]
i18n 在当前的 release 已经完成。
