### ISSUE TITLE
1.3.0版本时不时刷新后自动退出

### ISSUE THREAD

**Issue by timothyyang96** [geeeeeeeeek/electronic-wechat#234]
#### Description
网页版一直有类似问题，屏幕一暗就自动退出需要重新扫描二维码。

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- OS: `<OS>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by timothyyang96** [comment]
以及，还是希望能够同mac版微信一样，增加截屏功能

**Comment by whoarememe** [comment]
你好,请问这个是不是类似一个浏览器打开了微信网页版呢?

**Comment by geeeeeeeeek** [comment]
@whoarememe 是的
