### ISSUE TITLE
希望增加点击关闭后最小化，现在是关闭后再打开聊天记录全部清空。总是误点，所以有这个需求。谢谢

### ISSUE THREAD

**Issue by howcity** [geeeeeeeeek/electronic-wechat#235]
#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- OS: `<OS>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by geeeeeeeeek** [comment]
并没有啊，点击关闭就是最小化

**Comment by ray26** [comment]
在osx上点击关闭但实际上后台还是在运行的
