### ISSUE TITLE
文档里边增加CDN下载地址的提示吧

### ISSUE THREAD

**Issue by ccbikai** [geeeeeeeeek/electronic-wechat#24]
#### Description
淘宝提供了 electron 的镜像，国内下载更快

You can set the `ELECTRON_MIRROR` or [`NPM_CONFIG_ELECTRON_MIRROR`](https://docs.npmjs.com/misc/config#environment-variables) env or `mirror` opt variable to use a custom base URL for grabbing electron zips.

```plain
## Electron Mirror of China
ELECTRON_MIRROR="https://npm.taobao.org/mirrors/electron/"

```

**Comment by geeeeeeeeek** [comment]
Looks fine to me.
