### ISSUE TITLE
阅读里的公众号推送的消息  客户端不自动刷新

### ISSUE THREAD

**Issue by xuye** [geeeeeeeeek/electronic-wechat#242]
#### Description

阅读里的公众号推送的消息  客户端不自动刷新， 我重新reload窗口之后才显示最新的消息

#### Specifications

- Version of Electron (run `$ electron --version`): `v1.3.0`
- OS: `<Mac OS>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by geeeeeeeeek** [comment]
与 Electronic WeChat 无关，请向微信团队反馈。
