### ISSUE TITLE
网络不稳定时自动登录，主界面频繁到前台

### ISSUE THREAD

**Issue by wean** [geeeeeeeeek/electronic-wechat#244]
#### Description

网络不稳定时，不停的自动登录，即使是已经最小化的主界面也被切换到前台，影响其他程序的使用

#### Specifications

- Version of Electron (run `$ electron --version`): `v1.3.0`
- OS: `Funtoo Linux(cinnamon desktop 2.8.8)`
- Stack trace from the error message (if any)

``` 
```

**Comment by geeeeeeeeek** [comment]
@wean 谢谢反馈，建议不用的时候先 quit 应用。
