### ISSUE TITLE
点通知的view没切换到程序窗口

### ISSUE THREAD

**Issue by xgdgsc** [geeeeeeeeek/electronic-wechat#245]
#### Description
v1.3.0在plasma下弹出通知，点击view按钮，没切换到程序窗口

#### Specifications

- Version of Electron (run `$ electron --version`): `v 1.1.0`
- OS: `archlinux`

**Comment by eleveni386** [comment]
xfce下也没有切换到程序窗口.

**Comment by geeeeeeeeek** [comment]
Duplicate of #286.
