### ISSUE TITLE
ubuntu14.04 隔一段时间微信窗口就会自动弹出来一下，然后内容就像刷新了或者重新登陆一样，之前的聊天记录都不见了。

### ISSUE THREAD

**Issue by yzsatgithub** [geeeeeeeeek/electronic-wechat#246]
#### Description

系统：ubuntu14.04
现象： 隔一段时间微信窗口就会自动弹出来一下，然后内容就像刷新了或者重新登陆一样，之前的聊天记录都不见了。这样很烦，看不到之前自己说了什么。。　

#### Specifications

- Version of Electron (run `$ electron --version`): `v1.3.0`
- OS: `Ubuntu 14.04 LTS`
- Stack trace from the error message (if any)

**Comment by geeeeeeeeek** [comment]
说明你的session经常断呗，检查网络环境。

**Comment by ripples-alive** [comment]
@geeeeeeeeek 断了不是跳到登陆页面么？

**Comment by geeeeeeeeek** [comment]
@ripples-alive 对的，除非没有网无法跳至登录页

**Comment by ripples-alive** [comment]
可是看他这个的意思，他没有跳到登陆页面，还是在正常的登陆状态的样子

**Comment by geeeeeeeeek** [comment]
这样，那我过几天看下

**Comment by yzsatgithub** [comment]
@geeeeeeeeek 是的，就像@ripples-alive 所说，是弹出正常登陆成功之后的样子，只有联系人列表，没有消息内容。

**Comment by kvnkuang** [comment]
我也遇到了一样的问题，不过我是隔一分钟左右就会重新弹出扫码界面。网络应该没问题，其他网站和应用都正常。

**Comment by ipfans** [comment]
最近频繁的出现了这个问题，是否是微信更新了一些接口呢？

**Comment by geeeeeeeeek** [comment]
Duplicate of #272.

**Comment by xgdgsc** [comment]
@geeeeeeeeek 这个怎么会dup 272呢。这个问题我最近也经常碰到，自动重新刷新一样。

**Comment by NeilZhy** [comment]
请问这个问题解决了吗，我现在也是一分钟弹出一次扫码登录页面，网络环境都好着呢
