### ISSUE TITLE
Incorrect buddy list items

### ISSUE THREAD

**Issue by KenetJervet** [geeeeeeeeek/electronic-wechat#247]
#### Description
Sorry my Chinese input is fucked up. My main problem is that the buddy list contains all those historical buddies that i added, even though i have already removed some of them from the list, and electronic wechat will not display their nicknames but only their avatars. This is really annoying.

I expect the buddy list to only include those accounts that *REALLY ARE* connected to me, but not show those that i have already deleted.

Thanks!

#### Specifications

- Version of Electron (run `$ electron --version`): `v1.2.0`
- OS: `Gentoo`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by geeeeeeeeek** [comment]
If you add a friend on your phone, there would be some delay before Web WeChat syncs your changes. And for some implementation reasons, changes like group notification on/off would not be synced.

I'm not sure if a deleted friend would be synced to Web WeChat. If that is an implementation issue, please reach the official WeChat team for further support.

**Comment by KenetJervet** [comment]
Yes you're right. I tried Web WeChat and it performed the same behavior. I never used Web WeChat before and always thought this project was implemented via web APIs with customized user interface.
