### ISSUE TITLE
通知能不能不要显示以前的消息 

### ISSUE THREAD

**Issue by xgdgsc** [geeeeeeeeek/electronic-wechat#248]
#### Description

目前archlinux下plasma桌面通知弹出的时候会显示前面的几条看过的消息，能不能只显示最新的消息。

**Comment by geeeeeeeeek** [comment]
@xgdgsc 截图。不明白。

**Comment by xgdgsc** [comment]
就是说一个群里面的消息，出“消息1”的时候，弹通知，我点了view看了之后，“消息2”来的时候通知是：
“消息1”
“消息2”
这样的，而不是光“消息2”。

**Comment by geeeeeeeeek** [comment]
@xgdgsc 不清楚为什么 electron 在 archlinux 的表现那么诡异。Mac 下没见过弹重复的气泡…

**Comment by xgdgsc** [comment]
我记得一开始用electronic-wechat时是正常的，后来不知道是kde升级了还是什么原因。

**Comment by geeeeeeeeek** [comment]
@xgdgsc 大概又是什么兼容性问题。OS 和 electron 只要其一更新总会出问题。。
