### ISSUE TITLE
更新的主分支代码 执行 npm install 报这个错误

### ISSUE THREAD

**Issue by tianshaokai** [geeeeeeeeek/electronic-wechat#249]
module.js:338
    throw err;
    ^

Error: Cannot find module '/home/tianshaokai/wechat/electronic-wechat/install'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3

**Comment by geeeeeeeeek** [comment]
删除后重新安装。

**Comment by tianshaokai** [comment]
我就是删除 了 才执行的 npm install 的

**Comment by arrowrowe** [comment]
确定执行的是 `npm install` 而不是 `node install`?......

**Comment by arrowrowe** [comment]
这个报错非常像 `node something` 然后找不到 something.........

**Comment by tianshaokai** [comment]
OK了，重新打开了命令窗口就好了

**Comment by geeeeeeeeek** [comment]
经常有人报这个 issue ，然而这是 npm 的锅，安装中断造成的。
