### ISSUE TITLE
编译好，启动出现错误

### ISSUE THREAD

**Issue by StormBolt** [geeeeeeeeek/electronic-wechat#250]
启动的过程中出现
`
ATTENTION: default value of option force_s3tc_enable overridden by environment.
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
`
请帮助看下

**Comment by geeeeeeeeek** [comment]
这是一个 Chromium 的已知 bug ，请前往他们的社区反馈。
你可以参考以下的帖子和解决方案。

https://bugs.chromium.org/p/chromium/issues/detail?id=319267
https://github.com/adobe/brackets/issues/7195
https://bbs.archlinux.org/viewtopic.php?id=182396
https://askubuntu.com/questions/525644/google-chrome-error

**Comment by StormBolt** [comment]
electronic-wechat会调用Chromium 吗？目前我的ubuntu 15已经卸载Chromium ，安装的是chrome 版本 50.0.2661.75 (64-bit)

**Comment by geeeeeeeeek** [comment]
@StormBolt 它自带一个，不然安装包为什么那么大呢
