### ISSUE TITLE
能添加类似于 点按bar栏 icon图标的快捷键呼出功能吗? show all 用不了哦

### ISSUE THREAD

**Issue by sheephe** [geeeeeeeeek/electronic-wechat#253]
#### Description

快捷键用惯的人很是难受 不想点bar栏 icon图标去呼出

求在menu 里面添加一行能呼出的选项 起码我们能自己diy快捷键 XD

谢啦

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- OS: `<OS>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by geeeeeeeeek** [comment]
@sheephe 下个版本会加上这个功能，之前已有类似讨论。
