### ISSUE TITLE
保持一段时间的会话

### ISSUE THREAD

**Issue by eleveni386** [geeeeeeeeek/electronic-wechat#254]
在chrome中. 关闭浏览器或者tab时. 在一定时间范围内(没测试多久) 再次通过chrome访问wechat,是不需要再次扫描二维码. 
在win版本中. 退出之后, 也是在一定时间范围内. 不需要再次扫描二维码.

**Comment by geeeeeeeeek** [comment]
Electronic WeChat 也是这样的。
