### ISSUE TITLE
Mac下消息提示数字过大

### ISSUE THREAD

**Issue by Lluvio** [geeeeeeeeek/electronic-wechat#255]
#### Description

在mac下 消息提醒数字可否小点？亦或者只做一个动态提醒，不显示数字

#### Specifications

Version 1.3.0 (1.3.0)
OS: Mac

**Comment by geeeeeeeeek** [comment]
@Lluvio 哪里的字大？托盘？Dock？

**Comment by Lluvio** [comment]
@geeeeeeeeek 是托盘...如下
![image](https://cloud.githubusercontent.com/assets/6127266/16143726/2c063c4c-34a1-11e6-9ed0-abfa6c761861.png)
