### ISSUE TITLE
one suggestion and one issue

### ISSUE THREAD

**Issue by GitatHub** [geeeeeeeeek/electronic-wechat#256]
1. can the font size of chatting text be resizable?
2. unable to paste copied image into the chat text input box

thanks

**Comment by ripples-alive** [comment]
Why you want to paste copied image into the chat text input box? As for WeChat, text and images are not allowed to be sent in one message.

**Comment by GitatHub** [comment]
因为在上一个版本里 这个功能是正常的，可以正常从剪贴板发图片。

**Comment by ripples-alive** [comment]
...从剪切版发图片和把图片粘到输入框还是有区别的……
上一版本是指哪个，我应该用的是 1.3.0，我这里是可以的。。。

**Comment by GitatHub** [comment]
1.3.0 不可以从剪贴板粘贴并发送图片
1.2.0 可以
系统是 feodra

**Comment by geeeeeeeeek** [comment]
Duplicate of #272.
