### ISSUE TITLE
nodejieba安装失败

### ISSUE THREAD

**Issue by eleveni386** [geeeeeeeeek/electronic-wechat#257]
> nodejieba@1.4.11 install /home/eleven/wechat/electronic-wechat/node_modules/nodejieba
> node-gyp rebuild

make: Entering directory '/home/eleven/wechat/electronic-wechat/node_modules/nodejieba/build'
  CXX(target) Release/obj.target/nodejieba/lib/index.o
  CXX(target) Release/obj.target/nodejieba/lib/nodejieba.o
  SOLINK_MODULE(target) Release/obj.target/nodejieba.node
  COPY Release/nodejieba.node
rm: /home/eleven/wechat/electronic-wechat/node_modules/nodejieba/build/Release/nodejieba.node 不存在!
nodejieba.target.mk:131: recipe for target 'Release/nodejieba.node' failed
make: *** [Release/nodejieba.node] Error 1
make: Leaving directory '/home/eleven/wechat/electronic-wechat/node_modules/nodejieba/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/eleven/wechat/node-v6.2.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.4.0-24-generic
gyp ERR! command "/home/eleven/wechat/node-v6.2.0-linux-x64/bin/node" "/home/eleven/wechat/node-v6.2.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/eleven/wechat/electronic-wechat/node_modules/nodejieba
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN install:nodejieba@1.4.11 nodejieba@1.4.11 install: `node-gyp rebuild`
npm WARN install:nodejieba@1.4.11 Exit status 1

**Comment by geeeeeeeeek** [comment]
删除重装……
