### ISSUE TITLE
ubuntu 16.04 下的系统消息点击无效

### ISSUE THREAD

**Issue by aleechou** [geeeeeeeeek/electronic-wechat#261]
#### Description

ubuntu 16.04 下,当收到好友消息时, 弹出的系统通知点击没有效果.
应该是点击了以后打开聊天窗口.

mouseover 的效果不对, mouseover时变半透明(不可读), mouseout 反而正常.

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.36.2`
- electronic-wechat v1.3.0
- OS: `ubuntu 16.04`

**Comment by felixzone** [comment]
OSX 10.11.5点击系统通知也无法弹出聊天窗口

**Comment by geeeeeeeeek** [comment]
Duplicate.
