### ISSUE TITLE
不能刷新登陆二维码

### ISSUE THREAD

**Issue by pan-long** [geeeeeeeeek/electronic-wechat#262]
#### Description
微信登陆二维码会过期，但是不能electronic wechat不能刷新二维码。只能重启再扫码登录。

#### Specifications

- Version of Electron (run `$ electron --version`): `v1.3.0`
- OS: `Mac OS El Capitan`

**Comment by ripples-alive** [comment]
菜单栏应该有刷新啊。。。

**Comment by pan-long** [comment]
啊，我看到了！谢谢！

**Comment by ValentinZhao** [comment]
@ripples-alive 我想请问一下，electron自带的window是不能接收到微信扫码状态的更新的吗？
