### ISSUE TITLE
在群里艾特别人，别人在手机上没有提醒。

### ISSUE THREAD

**Issue by kzx1025** [geeeeeeeeek/electronic-wechat#263]
#### Description
在微信群里艾特别人，并没有起到实质的功能，艾特的人收不到提醒。

#### Specifications

- Version of Electron (run `$ electron --version`): `v1.3.0`

**Comment by geeeeeeeeek** [comment]
协议不支持，只能补全 id ，无法和客户端做到一样的 @ 效果。
