### ISSUE TITLE
Ubuntu14.04 `“qq表情”`和`“符号表情”`一片空白

### ISSUE THREAD

**Issue by yzsatgithub** [geeeeeeeeek/electronic-wechat#264]
#### Description

系统：ubuntu14.04
现象： `“qq表情”`和`“符号表情”`一片空白，只能看到`“动画表情”`里的兔斯基。别人发的基本表情也什么都看不到。最初安装的时候没有这个问题，过了一段时间之后才有的，期间没有动过代码和文件。

#### Specifications

- Version of Electron (run `$ electron --version`): `v1.3.0`
- OS: `Ubuntu 14.04 LTS`
- Stack trace from the error message (if any)

![2016-06-21 16 01 01](https://cloud.githubusercontent.com/assets/10882352/16222204/7fab681a-37c9-11e6-82a4-277e379e5b15.png)
![2016-06-21 16 01 41](https://cloud.githubusercontent.com/assets/10882352/16222207/81a594a6-37c9-11e6-8e89-dc1fcf6d1e7f.png)
![2016-06-21 16 01 48](https://cloud.githubusercontent.com/assets/10882352/16222209/84a025fe-37c9-11e6-84c4-f75a0234dacc.png)

**Comment by ripples-alive** [comment]
#232

**Comment by geeeeeeeeek** [comment]
其实这不是同一个issue，我看下

**Comment by ripples-alive** [comment]
这样么。。。好吧，我的锅。。。
