### ISSUE TITLE
希望来新消息的时候，状态栏的微信图标能闪烁，就像win里面一样

### ISSUE THREAD

**Issue by halexan** [geeeeeeeeek/electronic-wechat#265]
#### Description

希望来新消息的时候，状态栏的微信图标能闪烁，就像win里面一样

#### Specifications

- Version of Electron (run `$ electron --version`): `v1.3.0`
- OS: `<ubuntu14.04>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by geeeeeeeeek** [comment]
不打算这样做。Linux/Max 下 IM 好像没有这样实现的。
