### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by bingFly** [geeeeeeeeek/electronic-wechat#274]
#### Description
info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.7.5
3 info using node@v0.12.2
4 verbose node symlink /usr/local/bin/node
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart electronic-wechat@1.3.0
7 info start electronic-wechat@1.3.0
8 verbose unsafe-perm in lifecycle true
9 info electronic-wechat@1.3.0 Failed to exec start script
10 verbose stack Error: electronic-wechat@1.3.0 start: `electron src/main.js`
10 verbose stack Exit status 127
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid electronic-wechat@1.3.0
12 verbose cwd /Users/hanbing/github_YY/electronic-wechat
13 error Darwin 15.4.0
14 error argv "node" "/usr/local/bin/npm" "start"
15 error node v0.12.2
16 error npm  v2.7.5
17 error code ELIFECYCLE
18 error electronic-wechat@1.3.0 start: `electron src/main.js`
18 error Exit status 127
19 error Failed at the electronic-wechat@1.3.0 start script 'electron src/main.js'.
19 error This is most likely a problem with the electronic-wechat package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     electron src/main.js
19 error You can get their info via:
19 error     npm owner ls electronic-wechat
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- OS: `<OS>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by bingFly** [comment]
是我的node和npm的版本问题么？

**Comment by geeeeeeeeek** [comment]
是

**Comment by bingFly** [comment]
版本要求什么？我改下。
