### ISSUE TITLE
问一下哪里可以下到deb包呢？

### ISSUE THREAD

**Issue by LzyAWP-Fred** [geeeeeeeeek/electronic-wechat#275]
我在用得是通用linux版本。我看到有rpm版得下，没找到deb的。谢谢～

**Comment by geeeeeeeeek** [comment]
@LzyAWP-Fred 这些包是社区维护的，如果还没有人做的话就没有了
https://github.com/geeeeeeeeek/electronic-wechat/wiki/System-Support-Matrix

**Comment by ripples-alive** [comment]
@geeeeeeeeek  话说，System support matrix wiki 页面图标怎么一副诡异挂彩了的样子。。。

**Comment by geeeeeeeeek** [comment]
@ripples-alive 那个check的icon不知怎么就防盗链了，有空换一下

**Comment by zenozeng** [comment]
@LzyAWP-Fred 今晚刚打了一个 v1.4.0 的 deb 包，不过只在 Debian 上测试过，Ubuntu 应当也可以用。可以试试：
https://github.com/zenozeng/electronic-wechat-deb

**Comment by LzyAWP-Fred** [comment]
我现在加.desktop快捷方式用得, 还有我换了fedora了2333. 不过也谢谢啦.
