### ISSUE TITLE
长时间运行会出现无法从electronic-wechat中复制文字出来的问题,重开解决

### ISSUE THREAD

**Issue by lrinQVQ** [geeeeeeeeek/electronic-wechat#279]
#### Description

大约开了4.5个小时,突然就无法复制文字了orz
Ubuntu 16.04 64位和Debian 8.5 64位都有这个问题

#### Specifications

- OS: `Ubuntu 16.04 64 bit,Debian 8.5 64 bit`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by geeeeeeeeek** [comment]
Duplicate of #272. Will look into that.

**Comment by lrinQVQ** [comment]
Thanks
