### ISSUE TITLE
输入框内右键无效，消息框内右键复制无效

### ISSUE THREAD

**Issue by weehowe-z** [geeeeeeeeek/electronic-wechat#283]
#### Description

- 输入框鼠标右键不显示菜单

- 消息框内使用右键复制无效（ctrl c 可以）

#### Specifications

- Version of Electron (run `$ electron --version`): `v1.2.5`
- OS: `Arch Linux`
- DE: `Gnome`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by geeeeeeeeek** [comment]
微信实现的复制需要flash支持，因此消息框内右键的复制确实是无效的。我会和 #272 一起看一下编辑器的问题。
