### ISSUE TITLE
这个项目还在维护吗？

### ISSUE THREAD

**Issue by WANG-lp** [geeeeeeeeek/electronic-wechat#287]
这个项目还在维护吗？已经好就没有处理过issue了

**Comment by eleveni386** [comment]
同问, 好久没提交过代码了.

**Comment by kylezhang** [comment]
就当学习了，还真的指望着这个

**Comment by geeeeeeeeek** [comment]
@WANG-lp @eleveni386 我复活了。前阵子比较忙，几个项目打开35个issue和pr吓到我了，让我先看一下，几个应用最近一两周更新。
