### ISSUE TITLE
macos上只要屏幕黑了进入省电模式再点亮屏幕就需要重新扫码登录

### ISSUE THREAD

**Issue by anuxs** [geeeeeeeeek/electronic-wechat#288]
#### Description
在macos上，特别是在用电池的情况下，只要屏幕一黑进入省电模式，在把屏幕点亮，就得重新扫码登录了，非茶麻烦。
但是，官方微信就不需要重新扫码登录了，他保持了登录状态。
所以不厌其烦。
希望改进。

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- OS: `<MacOS 10.12 beta3>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by ripples-alive** [comment]
web 微信就是这样…

**Comment by geeeeeeeeek** [comment]
这个没法解决，和其他第三方微信客户端作者也沟通过了
