### ISSUE TITLE
sudo cnpm install electron-prebuilt -g 执行时报错 

### ISSUE THREAD

**Issue by vipzrx** [geeeeeeeeek/electronic-wechat#292]
#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- OS: `<OS>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```
$ sudo cnpm install electron-prebuilt -g
[electron-prebuilt@1.2.8] link /usr/bin/electron@ -> ../lib/node_modules/.electron-prebuilt_npminstall/electron-prebuilt/1.2.8/electron-prebuilt/cli.js
[electron-prebuilt@*] installed at node_modules/.electron-prebuilt_npminstall/electron-prebuilt/1.2.8/electron-prebuilt (152 packages, use 19s, speed 113.65kB/s, json 921.17kB, tarball 1.22MB)
excute post install scripts...
[electron-prebuilt@1.2.8] scripts.postinstall: "node install.js" at /usr/lib/node_modules/.electron-prebuilt_npminstall/electron-prebuilt/1.2.8/electron-prebuilt
/usr/lib/node_modules/.electron-prebuilt_npminstall/electron-prebuilt/1.2.8/electron-prebuilt/install.js:22
throw err
^

Error: end of central directory record signature not found
at /usr/lib/node_modules/.electron-prebuilt_npminstall/yauzl/2.4.1/yauzl/index.js:167:14
at /usr/lib/node_modules/.electron-prebuilt_npminstall/yauzl/2.4.1/yauzl/index.js:473:5
at /usr/lib/node_modules/.electron-prebuilt_npminstall/fd-slicer/1.0.1/fd-slicer/index.js:32:7
at FSReqWrap.wrapper as oncomplete
Error: post install error, please remove node_modules before retry!
Run "sh -c node install.js" error, exit code 1
Error: post install error, please remove node_modules before retry!
Run "sh -c node install.js" error, exit code 1
at ChildProcess. (/usr/lib/node_modules/cnpm/node_modules/npminstall/node_modules/runscript/index.js:67:21)
at emitTwo (events.js:87:13)
at ChildProcess.emit (events.js:172:7)
at maybeClose (internal/child_process.js:827:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by vipzrx** [comment]
kk@X201:~$ cd soft/soft_git/electronic-wechat/
kk@X201:~/soft/soft_git/electronic-wechat$ ls
assets        CONTRIBUTING.md    node_modules  README_zh.md
CHANGELOG.md  ISSUE_TEMPLATE.md  package.json  scripts
config.json   LICENSE.md         README.md     src
kk@X201:~/soft/soft_git/electronic-wechat$ sudo cnpm install
[sudo] password for kk: 
[electron-packager@^7.0.0] existed at /home/kk/soft/soft_git/electronic-wechat/node_modules/electron-packager
[electron-prebuilt@^1.1.0] existed at /home/kk/soft/soft_git/electronic-wechat/node_modules/electron-prebuilt
[pinyin@^2.7.1] existed at /home/kk/soft/soft_git/electronic-wechat/node_modules/pinyin
All packages installed (use 30ms, speed 0B/s, json 0(0B), tarball 0B)
kk@X201:~/soft/soft_git/electronic-wechat$ sudo npm start

> electronic-wechat@1.3.0 start /home/kk/soft/soft_git/electronic-wechat
> electron src/main.js

fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/kk/soft/soft_git/electronic-wechat/node_modules/.npminstall/electron-prebuilt/1.2.8/electron-prebuilt/path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.<anonymous> (/home/kk/soft/soft_git/electronic-wechat/node_modules/.npminstall/electron-prebuilt/1.2.8/electron-prebuilt/index.js:4:42)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

npm ERR! Linux 3.16.0-4-686-pae
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! electronic-wechat@1.3.0 start: `electron src/main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electronic-wechat@1.3.0 start script 'electron src/main.js'.
npm ERR! This is most likely a problem with the electronic-wechat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron src/main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electronic-wechat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls electronic-wechat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/kk/soft/soft_git/electronic-wechat/npm-debug.log
kk@X201:~/soft/soft_git/electronic-wechat$

**Comment by vipzrx** [comment]
kk@X201:~$ electron --version
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/lib/node_modules/.electron-prebuilt_npminstall/electron-prebuilt/1.2.8/electron-prebuilt/dist/electron ENOENT
    at exports._errnoException (util.js:873:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by vipzrx** [comment]
按照下面的链接，rm
Remove electron prebuilt - electron - Atom Discussion
https://discuss.atom.io/t/remove-electron-prebuilt/21067
 sudo npm rm -g electron-prebuilt
[sudo] password for kk: 
npm WARN uninstall not installed in /usr/lib/node_modules: "electron-prebuilt"

之后，还是有
kk@X201:~$ electron --version
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/lib/node_modules/.electron-prebuilt_npminstall/electron-prebuilt/1.2.8/electron-prebuilt/dist/electron ENOENT
    at exports._errnoException (util.js:873:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3

使用which查看
$ which electron
/usr/bin/electron

$ ls -al /usr/bin/electron
lrwxrwxrwx 1 root root 98 Jul 24 21:46 /usr/bin/electron -> ../lib/node_modules/.electron-prebuilt_npminstall/electron-prebuilt/1.2.8/electron-prebuilt/cli.js

**Comment by geeeeeeeeek** [comment]
不要`-g`，在项目根目录`npm install`安装项目依赖，即可使用`npm start`运行，或打包后以 app 的形式使用。

**Comment by linux0ne** [comment]
@geeeeeeeeek 

我的错误很离谱，一开始是#310的情况
现在是在根目录sudo npm install  结果终端一点儿显示都没有。  这是怎么了？
