### ISSUE TITLE
执行npm start 会失败，手动执行$ electron src/main.js 可以正常打开

### ISSUE THREAD

**Issue by vipzrx** [geeeeeeeeek/electronic-wechat#293]
#### Description

kk@X201:~/soft/soft_git/electronic-wechat$ sudo npm start

> electronic-wechat@1.3.0 start /home/kk/soft/soft_git/electronic-wechat
> electron src/main.js

fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/kk/soft/soft_git/electronic-wechat/node_modules/.npminstall/electron-prebuilt/1.2.8/electron-prebuilt/path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.<anonymous> (/home/kk/soft/soft_git/electronic-wechat/node_modules/.npminstall/electron-prebuilt/1.2.8/electron-prebuilt/index.js:4:42)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

npm ERR! Linux 3.16.0-4-686-pae
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! electronic-wechat@1.3.0 start: `electron src/main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electronic-wechat@1.3.0 start script 'electron src/main.js'.
npm ERR! This is most likely a problem with the electronic-wechat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron src/main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electronic-wechat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls electronic-wechat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/kk/soft/soft_git/electronic-wechat/npm-debug.log

kk@X201:~/soft/soft_git/electronic-wechat$ ls
assets        CONTRIBUTING.md    node_modules   README.md     src
CHANGELOG.md  ISSUE_TEMPLATE.md  npm-debug.log  README_zh.md
config.json   LICENSE.md         package.json   scripts

kk@X201:~/soft/soft_git/electronic-wechat$ electron src/main.js
Reconnect.

这个时候，就会弹出扫吗登录的界面
#### Specifications
- Version of Electron (run `$ electron --version`): `v0.0.0`

kk@X201:~$ electron --version
v1.2.8
- OS: `<OS>`

kk@X201:~$ uname -a
Linux X201 3.16.0-4-686-pae #1 SMP Debian 3.16.36-1 (2016-07-04) i686 GNU/Linux

kk@X201:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.5 (jessie)
Release:    8.5
Codename:   jessie
- Stack trace from the error message (if any)

```
<Stack trace here>
```

**Comment by Wkee** [comment]
**Description**
root@kerwin-MR-X3:/tmpgit/electronic-wechat#  npm start

> electronic-wechat@1.4.0 start /tmpgit/electronic-wechat
> electron src/main.js

fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/tmpgit/electronic-wechat/node_modules/electron/path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.<anonymous> (/tmpgit/electronic-wechat/node_modules/electron/index.js:4:42)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)

npm ERR! Linux 4.4.0-51-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! electronic-wechat@1.4.0 start: `electron src/main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electronic-wechat@1.4.0 start script 'electron src/main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electronic-wechat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron src/main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electronic-wechat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electronic-wechat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmpgit/electronic-wechat/npm-debug.log
root@kerwin-MR-X3:/tmpgit/electronic-wechat# ls
assets        CONTRIBUTING.md    node_modules   README.md     src
CHANGELOG.md  ISSUE_TEMPLATE.md  npm-debug.log  README_zh.md
config.json   LICENSE.md         package.json   scripts
root@kerwin-MR-X3:/tmpgit/electronic-wechat#  electron src/main.js
electron：未找到命令

**Question**
我的错误和你一样也是找不到路径的文件，但是为什么我用electron提示是未找到命令呢？

**Comment by ererermao** [comment]
同样的问题，有人解决了吗?

**Comment by georgezouq** [comment]
是不是node版本不对 我node v7.1.0 在OSX 上可以正常install 和 start

**Comment by geeeeeeeeek** [comment]
npm 不应该 sudo，可能会有权限问题
