### ISSUE TITLE
程序初始化失败，点击确认刷新页面

### ISSUE THREAD

**Issue by jkyeo** [geeeeeeeeek/electronic-wechat#297]
#### Description

扫码成功后手机端点击确认登录，electronic-wechat 客户端提示“程序初始化失败，点击确认刷新页面”。点击确认后返回扫码页面。

#### Specifications

- Version of Electron v1.3.0
- OS: `macOS 10.11.6`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by Blaok** [comment]
Same problem here. Latest Arch Linux x64, stable version installed from AUR. An interesting fact is that using Chrome nor IE on Windows 10 x64 does not work either (the same problem).

**Comment by pys200603027** [comment]
the same problem on my macOS10.11.3

**Comment by Blaok** [comment]
Seems that it is a bug of Android client of WeChat. The iOS version works for me...

**Comment by geeeeeeeeek** [comment]
Should be related to Web WeChat itself. So far no plan to fix it.
