### ISSUE TITLE
登录成功，页面没有跳转

### ISSUE THREAD

**Issue by izuolan** [geeeeeeeeek/electronic-wechat#3]
#### Description
npm start之后窗口打开，但是扫码后，电脑只显示扫码成功，手机点击登录，电脑没有反应。

#### 执行步骤：
```
# Clone this repository
git clone https://github.com/geeeeeeeeek/electronic-wechat.git
# Go into the repository
cd electronic-wechat
# Install dependencies and run the app
npm install && npm start
```

- OS: `Linux`

**Comment by geeeeeeeeek** [comment]
我去测试一下Linux环境。

**Comment by viko16** [comment]
+1，遇到同样的情况

OS X 10.11.3

**Comment by geeeeeeeeek** [comment]
@izuolan Linux是不是遇到了这个错误？
![image](https://cloud.githubusercontent.com/assets/7262715/13310030/72c6f4f6-dbbd-11e5-8dab-37ce82ea8cc6.png)

**Comment by DIYgod** [comment]
OS X 10.11.3 同样没转跳

**Comment by izuolan** [comment]
@geeeeeeeeek 我没遇到这个情况，更新之后已经好了～～
