### ISSUE TITLE
公众号新窗口打开报错

### ISSUE THREAD

**Issue by yuanxj1024** [geeeeeeeeek/electronic-wechat#30]
First, make sure your issue is strictly related to the ***Electronic WeChat*** project. If it's a question or feature request, you can remove the template below.

#### Description
查看公众号的某一文章，右侧窗口下拉菜单中的 ‘New Tab’ 点击报错：

错误信息如图:
![截图](http://7xix26.com1.z0.glb.clouddn.com/42FB75DA-47D3-4D02-9A98-1152B90886FF.png)

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.36.9`
- Version of Node.js (run `$ node --version`): `v5.5.0`
- OS: `EI Capitan 10.11.13`
- Architecture `<ARCH>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by geeeeeeeeek** [comment]
这应该是一个electron的上游bug，复现这个bug时尝试command + option + 打开dev tools应该也会出现这样的错误提示。我回去再仔细看一下。

**Comment by geeeeeeeeek** [comment]
应该是menu造成的

**Comment by yuanxj1024** [comment]
能力有限，只能都帮忙测试了，嘿嘿，加油，向你学习！！

**Comment by geeeeeeeeek** [comment]
确认是bug，周末修复，现在忍一下不要新窗口打开吧…

**Comment by chasuner** [comment]
点击阅读原文也会挂掉

**Comment by jyanchen** [comment]
@geeeeeeeeek 
````javascript
handler.handleRedirectMessage = (originalUrl) => {
  let regex = new RegExp("[\\?&]requrl=([^&#]*)");
  let redirectedUrl = regex.exec(originalUrl);
  if (redirectedUrl) {
    return decodeURIComponent(redirectedUrl[1].replace(/\+/g, " "));
  } else {
//return redirectedUrl; //null
    return originalUrl; //应该直接返回传过来的链接originalUrl
  }
};
````
