### ISSUE TITLE
微信表情包“野萌君”系列无法加载

### ISSUE THREAD

**Issue by GuoxUnique** [geeeeeeeeek/electronic-wechat#304]
如题，接收时为裂开的小图

**Comment by BlueBird1017** [comment]
还有“罗小黑战记”也无法加载，所以可能是所有自定义表情包都无法加载？

**Comment by BlueBird1017** [comment]
兔斯基可以加载，其他没有做进一步测试，结论应该是部分表情包无法加载

**Comment by linlihai** [comment]
+ 1

**Comment by bash-horatio** [comment]
@GuoxUnique 之前是都可以加载的。现在不行，我用v1.2.0，还想编译v1.3.0，看看会不会解决了这个问题。

**Comment by GuoxUnique** [comment]
@bash-horatio 是嘛，我之前也用，当时好像也行？（没注意）然后这次再编译的版本就不行了。好的我试试你的解决办法：）

**Comment by GuoxUnique** [comment]
下载了v1.3.0测试了一下，其他表情还是无法加载，显示的还是裂开的图片

**Comment by tsai1993** [comment]
希望能尽快修复这个问题呀，唯一的小瑕疵

**Comment by bash-horatio** [comment]
@geeeeeeeeek 之前release note中有提到用抓包注入表情的，对这个系列不管用？

**Comment by geeeeeeeeek** [comment]
被微信疯封了，没法修复。

**Comment by bash-horatio** [comment]
@geeeeeeeeek 好吧，辛苦了！其实表情包倒无伤大雅，还落得清静
