### ISSUE TITLE
点击对话框任意位置之后, 输入框内中文输入法输入的第一个字符会成为英文

### ISSUE THREAD

**Issue by zhanglintc** [geeeeeeeeek/electronic-wechat#305]
#### Description
看了看所有的issue, 好像没人提到这个:
在中文输入法状态下, 如果点击了上方的对话框, 然后输入字符的话, 第一个字符不能正确的调用中文输入法, 只能打出英文字符. 第二个字符才可以使用中文.

可以参考下面的图片:
![p1](http://img2.ph.126.net/dyzOw3Lkne_CwAj57aFPag==/6631597730304613301.png)
![p2](http://img2.ph.126.net/GJgyqNJ1KGpsBD0IJbYd2w==/6631789045327851737.png)

#### Specifications

- Version of Electron (run `$ electron --version`): 这一步运行了没有出来结果, 所以不知道... 
- OS: `<OS X EI Capitan version 10.11.6>`
- Electron WeChat: `Version 1.3.0 (1.3.0)`

**Comment by geeeeeeeeek** [comment]
@zhanglintc 很久以前Electron就修复了这个bug，现在无法复现。

**Comment by zhanglintc** [comment]
@geeeeeeeeek 意思是我更新到最新的Electron就可以解决吗? 我刚才重装了一下Electron, 现在是v1.4.1, 还是有这个问题.
