### ISSUE TITLE
公众号面板的弹出菜单在选区外点击应该收起

### ISSUE THREAD

**Issue by act262** [geeeeeeeeek/electronic-wechat#306]
#### Description

公众号面板的菜单按钮出现后，希望点击区域外或者点击分享后可以收起来，目前只有点击标题区域才收起来。

#### Specifications
![wechat_menu_hide_issues](https://cloud.githubusercontent.com/assets/4591669/17391509/3da8b2a4-5a49-11e6-8229-c59780d7e524.png)

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial

**Comment by geeeeeeeeek** [comment]
欢迎 PR ，低优先级，暂时不考虑实现。
