### ISSUE TITLE
能顺手编译个win版的吗？

### ISSUE THREAD

**Issue by klausgao** [geeeeeeeeek/electronic-wechat#309]
我们自己编译老是卡在jieba那里，搞不定了。
只想用，不想折腾了。

**Comment by geeeeeeeeek** [comment]
欢迎 PR， 但我不会提供支持。

**Comment by cybmp3** [comment]
> 
> 
> 我们自己编译老是卡在jieba那里，搞不定了。
> 只想用，不想折腾了。

https://github.com/trazyn/weweChat  可以看下这个。有类似的
