### ISSUE TITLE
遇到编译困难：cnpm install electronic-wechat 命令的完整终端信息 on ubuntu 14.04 64bit  

### ISSUE THREAD

**Issue by linux0ne** [geeeeeeeeek/electronic-wechat#310]
$ cnpm install electronic-wechat
npm WARN engine electron-packager@7.5.1: wanted: {"node":">= 4.0"} (current: {"node":"0.10.33","npm":"1.4.28"})
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.33","npm":"1.4.28"})
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.33","npm":"1.4.28"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.33","npm":"1.4.28"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.33","npm":"1.4.28"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.33","npm":"1.4.28"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.33","npm":"1.4.28"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.33","npm":"1.4.28"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.33","npm":"1.4.28"})

> electron-prebuilt@0.37.8 postinstall /home/o/node_modules/electronic-wechat/node_modules/electron-prebuilt
> node install.js

Downloading electron-v0.37.8-linux-x64.zip
Error: connect ETIMEDOUT

Error: connect ETIMEDOUT
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.33","npm":"1.4.28"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.33","npm":"1.4.28"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.33","npm":"1.4.28"})

> nodejieba@2.2.2 install /home/o/node_modules/electronic-wechat/node_modules/pinyin/node_modules/nodejieba
> node-gyp rebuild

make:进入目录'/home/o/node_modules/electronic-wechat/node_modules/pinyin/node_modules/nodejieba/build'
  CXX(target) Release/obj.target/nodejieba/lib/index.o
  CXX(target) Release/obj.target/nodejieba/lib/nodejieba.o
  SOLINK_MODULE(target) Release/obj.target/nodejieba.node
  SOLINK_MODULE(target) Release/obj.target/nodejieba.node: Finished
  COPY Release/nodejieba.node
make:离开目录“/home/o/node_modules/electronic-wechat/node_modules/pinyin/node_modules/nodejieba/build”
npm ERR! electron-prebuilt@0.37.8 postinstall: `node install.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the electron-prebuilt@0.37.8 postinstall script.
npm ERR! This is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.13.0-93-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "--registry=https://registry.npm.taobao.org" "--cache=/home/o/.npm/.cache/cnpm" "--disturl=https://npm.taobao.org/dist" "--userconfig=/home/o/.cnpmrc" "install" "electronic-wechat"
npm ERR! cwd /home/o
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by linux0ne** [comment]
一楼的内容是我在家里网络下的安装过程，家里的网络配置可能有问题，不过我不确定，所以请大家给予帮助。

下面的内容是我在别人的机器上安装这个软件的终端信息，不巧的是也遇到了错误，但是这个错误的原因我也搞不懂，也请大家给予帮助。

electronic-wechat@1.3.0 /opt/electronic-wechat
├─┬ electron-packager@7.5.1 
│ ├─┬ asar@0.12.1 
│ │ ├── chromium-pickle-js@0.1.0 
│ │ ├─┬ commander@2.9.0 
│ │ │ └── graceful-readlink@1.0.1 
│ │ ├── cuint@0.2.1 
│ │ ├─┬ glob@6.0.4 
│ │ │ ├─┬ inflight@1.0.5 
│ │ │ │ └── wrappy@1.0.2 
│ │ │ ├── inherits@2.0.1 
│ │ │ └── once@1.3.3 
│ │ ├─┬ minimatch@3.0.3 
│ │ │ └─┬ brace-expansion@1.1.6 
│ │ │   ├── balanced-match@0.4.2 
│ │ │   └── concat-map@0.0.1 
│ │ ├─┬ mkdirp@0.5.1 
│ │ │ └── minimist@0.0.8 
│ │ ├─┬ mksnapshot@0.3.0 
│ │ │ ├─┬ decompress-zip@0.3.0 
│ │ │ │ ├─┬ binary@0.3.0 
│ │ │ │ │ ├── buffers@0.1.1 
│ │ │ │ │ └─┬ chainsaw@0.1.0 
│ │ │ │ │   └── traverse@0.3.9 
│ │ │ │ ├── mkpath@0.1.0 
│ │ │ │ ├─┬ nopt@3.0.6 
│ │ │ │ │ └── abbrev@1.0.9 
│ │ │ │ ├── q@1.4.1 
│ │ │ │ ├─┬ readable-stream@1.1.14 
│ │ │ │ │ └── isarray@0.0.1 
│ │ │ │ └─┬ touch@0.0.3 
│ │ │ │   └── nopt@1.0.10 
│ │ │ ├── fs-extra@0.26.7 
│ │ │ └─┬ request@2.55.0 
│ │ │   ├── aws-sign2@0.5.0 
│ │ │   ├─┬ bl@0.9.5 
│ │ │   │ └── readable-stream@1.0.34 
│ │ │   ├── caseless@0.9.0 
│ │ │   ├─┬ combined-stream@0.0.7 
│ │ │   │ └── delayed-stream@0.0.5 
│ │ │   ├── forever-agent@0.6.1 
│ │ │   ├─┬ form-data@0.2.0 
│ │ │   │ └── async@0.9.2 
│ │ │   ├─┬ har-validator@1.8.0 
│ │ │   │ ├── bluebird@2.10.2 
│ │ │   │ ├─┬ chalk@1.1.3 
│ │ │   │ │ ├── ansi-styles@2.2.1 
│ │ │   │ │ ├── escape-string-regexp@1.0.5 
│ │ │   │ │ ├─┬ has-ansi@2.0.0 
│ │ │   │ │ │ └── ansi-regex@2.0.0 
│ │ │   │ │ ├── strip-ansi@3.0.1 
│ │ │   │ │ └── supports-color@2.0.0 
│ │ │   │ └─┬ is-my-json-valid@2.13.1 
│ │ │   │   ├── generate-function@2.0.0 
│ │ │   │   ├─┬ generate-object-property@1.2.0 
│ │ │   │   │ └── is-property@1.0.2 
│ │ │   │   ├── jsonpointer@2.0.0 
│ │ │   │   └── xtend@4.0.1 
│ │ │   ├─┬ hawk@2.3.1 
│ │ │   │ ├── boom@2.10.1 
│ │ │   │ ├── cryptiles@2.0.5 
│ │ │   │ ├── hoek@2.16.3 
│ │ │   │ └── sntp@1.0.9 
│ │ │   ├─┬ http-signature@0.10.1 
│ │ │   │ ├── asn1@0.1.11 
│ │ │   │ ├── assert-plus@0.1.5 
│ │ │   │ └── ctype@0.5.3 
│ │ │   ├── isstream@0.1.2 
│ │ │   ├── json-stringify-safe@5.0.1 
│ │ │   ├─┬ mime-types@2.0.14 
│ │ │   │ └── mime-db@1.12.0 
│ │ │   ├── node-uuid@1.4.7 
│ │ │   ├── oauth-sign@0.6.0 
│ │ │   ├── qs@2.4.2 
│ │ │   ├── stringstream@0.0.5 
│ │ │   ├── tough-cookie@2.3.1 
│ │ │   └── tunnel-agent@0.4.3 
│ │ └─┬ tmp@0.0.28 
│ │   └── os-tmpdir@1.0.1 
│ ├─┬ debug@2.2.0 
│ │ └── ms@0.7.1 
│ ├─┬ electron-download@2.1.2 
│ │ ├── home-path@1.0.3 
│ │ ├─┬ mv@2.1.1 
│ │ │ ├── ncp@2.0.0 
│ │ │ └── rimraf@2.4.5 
│ │ ├─┬ nugget@1.6.2 
│ │ │ ├─┬ pretty-bytes@1.0.4 
│ │ │ │ ├── get-stdin@4.0.1 
│ │ │ │ └─┬ meow@3.7.0 
│ │ │ │   ├─┬ camelcase-keys@2.1.0 
│ │ │ │   │ └── camelcase@2.1.1 
│ │ │ │   ├── decamelize@1.2.0 
│ │ │ │   ├─┬ loud-rejection@1.6.0 
│ │ │ │   │ ├─┬ currently-unhandled@0.4.1 
│ │ │ │   │ │ └── array-find-index@1.0.1 
│ │ │ │   │ └── signal-exit@3.0.0 
│ │ │ │   ├── map-obj@1.0.1 
│ │ │ │   ├─┬ normalize-package-data@2.3.5 
│ │ │ │   │ ├── hosted-git-info@2.1.5 
│ │ │ │   │ ├─┬ is-builtin-module@1.0.0 
│ │ │ │   │ │ └── builtin-modules@1.1.1 
│ │ │ │   │ ├── semver@5.3.0 
│ │ │ │   │ └─┬ validate-npm-package-license@3.0.1 
│ │ │ │   │   ├─┬ spdx-correct@1.0.2 
│ │ │ │   │   │ └── spdx-license-ids@1.2.2 
│ │ │ │   │   └─┬ spdx-expression-parse@1.0.2 
│ │ │ │   │     └── spdx-exceptions@1.0.5 
│ │ │ │   ├─┬ read-pkg-up@1.0.1 
│ │ │ │   │ ├─┬ find-up@1.1.2 
│ │ │ │   │ │ ├── path-exists@2.1.0 
│ │ │ │   │ │ └─┬ pinkie-promise@2.0.1 
│ │ │ │   │ │   └── pinkie@2.0.4 
│ │ │ │   │ └─┬ read-pkg@1.1.0 
│ │ │ │   │   ├─┬ load-json-file@1.1.0 
│ │ │ │   │   │ ├─┬ parse-json@2.2.0 
│ │ │ │   │   │ │ └─┬ error-ex@1.3.0 
│ │ │ │   │   │ │   └── is-arrayish@0.2.1 
│ │ │ │   │   │ ├── pify@2.3.0 
│ │ │ │   │   │ └─┬ strip-bom@2.0.0 
│ │ │ │   │   │   └── is-utf8@0.2.1 
│ │ │ │   │   └── path-type@1.1.0 
│ │ │ │   ├─┬ redent@1.0.0 
│ │ │ │   │ ├─┬ indent-string@2.1.0 
│ │ │ │   │ │ └─┬ repeating@2.0.1 
│ │ │ │   │ │   └─┬ is-finite@1.0.1 
│ │ │ │   │ │     └── number-is-nan@1.0.0 
│ │ │ │   │ └── strip-indent@1.0.1 
│ │ │ │   └── trim-newlines@1.0.0 
│ │ │ ├─┬ progress-stream@1.2.0 
│ │ │ │ ├── speedometer@0.1.4 
│ │ │ │ └─┬ through2@0.2.3 
│ │ │ │   └─┬ xtend@2.1.2 
│ │ │ │     └── object-keys@0.4.0 
│ │ │ ├── single-line-log@0.4.1 
│ │ │ └── throttleit@0.0.2 
│ │ ├── path-exists@1.0.0 
│ │ └─┬ rc@1.1.6 
│ │   ├── deep-extend@0.4.1 
│ │   ├── ini@1.3.4 
│ │   └── strip-json-comments@1.0.4 
│ ├── electron-osx-sign@0.3.1 
│ ├─┬ extract-zip@1.5.0 
│ │ ├─┬ concat-stream@1.5.0 
│ │ │ ├─┬ readable-stream@2.0.6 
│ │ │ │ ├── core-util-is@1.0.2 
│ │ │ │ ├── isarray@1.0.0 
│ │ │ │ ├── process-nextick-args@1.0.7 
│ │ │ │ └── string_decoder@0.10.31 
│ │ │ └── typedarray@0.0.6 
│ │ ├── debug@0.7.4 
│ │ ├─┬ mkdirp@0.5.0 
│ │ │ └── minimist@0.0.8 
│ │ └─┬ yauzl@2.4.1 
│ │   └─┬ fd-slicer@1.0.1 
│ │     └── pend@1.2.0 
│ ├─┬ fs-extra@0.30.0 
│ │ ├── graceful-fs@4.1.5 
│ │ ├── jsonfile@2.3.1 
│ │ ├── klaw@1.3.0 
│ │ ├── path-is-absolute@1.0.0 
│ │ └─┬ rimraf@2.5.4 
│ │   └─┬ glob@7.0.5 
│ │     └── fs.realpath@1.0.0 
│ ├── lodash.get@4.4.1 
│ ├── minimist@1.2.0 
│ ├─┬ plist@1.2.0 
│ │ ├── base64-js@0.0.8 
│ │ ├── util-deprecate@1.0.2 
│ │ ├─┬ xmlbuilder@4.0.0 
│ │ │ └── lodash@3.10.1 
│ │ └── xmldom@0.1.22 
│ ├── rcedit@0.5.1 
│ ├── resolve@1.1.7 
│ └── run-series@1.1.4 
└─┬ pinyin@2.8.0 
  ├─┬ commander@1.1.1 
  │ └── keypress@0.1.0 
  └── object-assign@4.1.0 

npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! electron-prebuilt@1.3.3 postinstall: `node install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the electron-prebuilt@1.3.3 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/electronic-wechat/npm-debug.log
cymode@HPLinux:/opt/electronic-wechat$

**Comment by linux0ne** [comment]
是因为node.js的问题？？ 这个需要安装最新的还是LTS版本就可以了呢？？

最新的版本是6.3.1，这个版本还需要最新的java8来配合，越来越复杂了。555555555

**Comment by linux0ne** [comment]
我安装了最新的nodejs 和 npm ，然后再执行sudo npm install   却……
终端信息如下：
cymode@HPLinux:~$ type node
node 是 /opt/node-v6.3.1-linux-x64/bin/node
cymode@HPLinux:~$ type npm
npm 是 /usr/bin/npm
cymode@HPLinux:~$ node -v
v6.3.1
cymode@HPLinux:~$ npm -v
3.10.3
cymode@HPLinux:~$ cd /opt/electronic-wechat/
cymode@HPLinux:/opt/electronic-wechat$ sudo npm install
[sudo] cymode 的密码： 
/usr/bin/env: "node": 没有那个文件或目录
cymode@HPLinux:/opt/electronic-wechat$

**Comment by bash-horatio** [comment]
@linux0ne 在debian系，需要安装nodejs-legacy。其他估计也类似，手动软连接node到nodejs也可以，比较tricky

**Comment by linux0ne** [comment]
@bash-horatio 
我是通过在官网下载的二进制包来安装的nodejs，最新版本的node 和 npm。 我自己设置了一下，命令都可以正常运行了，结果在/opt/electronic-wechat/里执行 sudo npm install的时候，却提示我如下信息：
/usr/bin/env: "node": 没有那个文件或目录

唉，整个安装过程一波三折，各种不会，我也不知道怎么办了。java8已正确安装了。
关键是对nodejs不熟悉。

我现在都不知道在linux系统里nodejs和node这两个命令的区别是啥？
能不能再指点指点我？  谢谢了
我的QQ：3131489789   
utox：9706400DD13442E09A224850A3DEBC463F36AC4C5DC04261A368AF0C867F2751C26120A24A67

**Comment by bash-horatio** [comment]
@linux0ne 其实nodejs我也不了解，之前发的一个issue中有提到。
我在debian上装了nodejs-legacy后，结果如下：
```
$ ls -l /usr/bin/node
lrwxrwxrwx 1 root root 6 Feb 29 20:00 /usr/bin/node -> nodejs
```

一般repo有的包，我都不会单独去下。单看你的错误信息：
```/usr/bin/env: "node": 没有那个文件或目录```
估计你是改了**.bashrc/.profile**，只作用于当前用户，sudo加载的环境变量没有node？
建议在**/etc下的bashrc/profile**里加上node的环境（sudo env的玄学我也不太懂）

**Comment by linux0ne** [comment]
@bash-horatio 
之前的问题我解决了，现在的问题是：
Refusing to install electronic-wechat as a dependency of itself
拒绝安装……  怎么个事儿？

**Comment by bash-horatio** [comment]
@linuxOne 没遇到过……你想做什么的时候遇到这个错误？

**Comment by linux0ne** [comment]
@bash-horatio
# 下载仓库
－－－－－－－－－－－－下方为项目的中文安装教程－－－－－－－－－－－－
git clone https://github.com/geeeeeeeeek/electronic-wechat.git
# 进入仓库
cd electronic-wechat
# 安装依赖, 运行应用
npm install && npm start
－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－

我就是按上方的做法操作的，当我操作到npm install的时候，就出现了本帖自2楼开始的所有“挫折”（其中1楼的情况是我另一台电脑的）

针对楼上的：Refusing to install electronic-wechat as a dependency of itself

我在/opt/electronic-wechat/ 目录下执行 sudo npm install 后就会产生这个提示。  
我不知道这是为什么 ？

我若是再多运行几次sudo npm install 的话， 竟然就不再出现任何提示了。

**Comment by bash-horatio** [comment]
@linux0ne 现在问题解决了？
一边先编译好，再mv到opt吧，省得有权限问题。npm是有些傻的，网络不好，经常ERROR。加上它本能增量缓存dependency，每次都要rm -rf node_modules，很是懊恼。

**Comment by linux0ne** [comment]
@bash-horatio 
依然没有解决，真是没办法了。无论是代理网络还是正常网络都安装不上，难道非得买个VPN，呵呵。

**Comment by bash-horatio** [comment]
@linux0ne 没有遇到过你的问题，不确定究竟是什么原因引起的，还得你自己看看。有几个常用的electron开源项目，总体感受是，只要网络好，基本npm install和npm start都没问题。

**Comment by jiuxiaxixi** [comment]
我记得有打包好了的

Horatio <notifications@github.com>于2016年8月15日周一 下午4:48写道：

**Comment by bash-horatio** [comment]
@jiuxiaxixi ?? 我编译成功，但是不会打包，就是想试试打包

**Comment by jiuxiaxixi** [comment]
我也没有试过自己打包。不过现在用 deepin 里面自带微信。这个微信我之前用的时候总是自动重启 不知道怎么回事

Horatio <notifications@github.com>于2016年8月16日周二 上午11:04写道：
