### ISSUE TITLE
can't drag the window on the osx 10.11

### ISSUE THREAD

**Issue by B1anker** [geeeeeeeeek/electronic-wechat#311]
#### Description
when I open the wechat,I found that I can't drag the window!

#### Specifications

- Version of Electron (run `$ electron --version`): `v1.3.0`
- OS: `<OS>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by loufq** [comment]
@B1anker  有个PL还没合并 https://github.com/geeeeeeeeek/electronic-wechat/pull/291
