### ISSUE TITLE
If you do, this is most likely a problem with the electronic-wechat package

### ISSUE THREAD

**Issue by linux0ne** [geeeeeeeeek/electronic-wechat#316]
cymode@HPLinux:/opt/electronic-wechat$ sudo git pull --rebase
当前分支 master 是最新的。
cymode@HPLinux:/opt/electronic-wechat$ sudo npm install
cymode@HPLinux:/opt/electronic-wechat$ sudo npm start

> electronic-wechat@1.3.0 start /opt/electronic-wechat
> electron src/main.js

fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/opt/electronic-wechat/node_modules/electron-prebuilt/path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.<anonymous> (/opt/electronic-wechat/node_modules/electron-prebuilt/index.js:4:42)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)

npm ERR! Linux 4.4.0-34-generic
npm ERR! argv "/opt/node-v6.3.1-linux-x64/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! electronic-wechat@1.3.0 start: `electron src/main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electronic-wechat@1.3.0 start script 'electron src/main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electronic-wechat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron src/main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electronic-wechat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electronic-wechat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/electronic-wechat/npm-debug.log
cymode@HPLinux:/opt/electronic-wechat$ npm -v
3.10.3
cymode@HPLinux:/opt/electronic-wechat$ nodejs -v
v6.3.1
cymode@HPLinux:/opt/electronic-wechat$ node -v
v6.3.1
cymode@HPLinux:/opt/electronic-wechat$ 

怎么办？？？

**Comment by fangxing204** [comment]
同问题 ,直接下载release的app就可以直接启动

**Comment by geeeeeeeeek** [comment]
安装问题以后都不回复了，统一文档说明。
