### ISSUE TITLE
[Mac] ⌘+W关闭窗口后会重新加载对话

### ISSUE THREAD

**Issue by alviezhang** [geeeeeeeeek/electronic-wechat#32]
#### Description

⌘+W关闭微信窗口后，重新打开electronic-wechat会丢失关闭前相关的对话信息。

#### Specifications

- Version of Electron (run `$ electron --version`): `v1.0.1`
- OS: `OSX 10.11.3`

**Comment by arrowrowe** [comment]
是否与 #5 重复?

**Comment by geeeeeeeeek** [comment]
Duplicate of #5.
