### ISSUE TITLE
安装失败，小白看不明白，话说这软件要怎么删除？

### ISSUE THREAD

**Issue by Qwenjin** [geeeeeeeeek/electronic-wechat#326]
#### Description
小白看不懂为什么安装失败了～恳请大神解释。

#### Specifications

- Version of Electron (run `$ electron --version`): `v1.4.0`
- OS: Ubuntu16.04LTS
-终端情况：
/*
wenjin@wenjin-X550VC:~/wechat/electronic-wechat$ npm install && npm start

> nodejieba@2.2.3 install /home/wenjin/wechat/electronic-wechat/node_modules/nodejieba
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:354:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-34-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/wenjin/wechat/electronic-wechat/node_modules/nodejieba
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:nodejieba@2.2.3 nodejieba@2.2.3 install: `node-gyp rebuild`
npm WARN install:nodejieba@2.2.3 Exit status 1

> electron@1.3.4 postinstall /home/wenjin/wechat/electronic-wechat/node_modules/electron
> node install.js

sh: 1: node: not found
npm ERR! Linux 4.4.0-34-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! electron@1.3.4 postinstall: `node install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the electron@1.3.4 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/wenjin/wechat/electronic-wechat/npm-debug.log
wenjin@wenjin-X550VC:~/wechat/electronic-wechat$ npm run build:linux

> electronic-wechat@1.4.0 build:linux /home/wenjin/wechat/electronic-wechat
> ./scripts/build.sh linux x64

Start packaging for linux x64.
/usr/bin/env: "node": 没有那个文件或目录

*/
``` 
<Stack trace here>
```

**Comment by ray26** [comment]
你node依赖没装，sudo apt-get install node
，删除的话你把clone下来的文件夹删了就好了

**Comment by Qwenjin** [comment]
嗯，搞好了，实际上我是sudo apt-get install nodejs-legacy。
但还有个问题，就是我是运行了npm run build:linux， 好像是打包成APP，然后我在搜索栏目的时候，以前版本的还是存在，就是不知道怎么卸载它。
![image](https://cloud.githubusercontent.com/assets/15087970/17995436/578e9a5a-6b27-11e6-8b09-2f79707f5bbf.png)

**Comment by ray26** [comment]
长按试试

**Comment by Qwenjin** [comment]
它只有启动这个选项  0.0
![image](https://cloud.githubusercontent.com/assets/15087970/17996245/21fd8102-6b2d-11e6-9050-3f32667bb2cb.png)
