### ISSUE TITLE
有没有可能增加群聊内的提及(metion)功能?

### ISSUE THREAD

**Issue by xream** [geeeeeeeeek/electronic-wechat#33]
之前一直用 Mac 版微信就是为了这个功能

**Comment by cnhx** [comment]
同求这个功能

**Comment by geeeeeeeeek** [comment]
Good idea.

**Comment by nykma** [comment]
+1 for this

**Comment by sunshineclt** [comment]
同求这个功能

**Comment by zzvv** [comment]
+1 之前web wechat客户端就是因为没这个功能，被放弃了。诶~ 这个需求真心很大很大

**Comment by syslot** [comment]
同求at！

**Comment by i6941** [comment]
同求@

**Comment by toddleo** [comment]
这个实现了我就不用买Mac了 XD

**Comment by geeeeeeeeek** [comment]
@toddleo 买买买，Mac大法好

**Comment by leftstick** [comment]
好功能，要实现！^^。
已经在计划了么？

**Comment by tufu9441** [comment]
+1 for this!

**Comment by MechanicianW** [comment]
+1 for this! 已完全弃用官方客户端

**Comment by imdragonet** [comment]
这个貌似是把 wx.qq.com 打包的吧 所以如果 wx.qq.com 网页吧微信不支持 这个应该也不能支持吧

**Comment by iamcc** [comment]
pr 了一个粗暴的解决办法，那么多人有需求，临时加上，后面有时间优化。

**Comment by nykma** [comment]
辛苦了，我来测试下……

**Comment by geeeeeeeeek** [comment]
辛苦，这两天在外面，你们先测试看看

**Comment by geeeeeeeeek** [comment]
回来了。刚重构了分享的功能，主分支上代码冲突了。@iamcc 你修改一下重新发个pr吧，目标分支选择我新开的`feature/group-at`。我争取这周把这个功能做好。

**Comment by geeeeeeeeek** [comment]
各位可以checkout一下`feature/group-at`分支，体验一下。mention功能已经加上，能够正确地显示群成员昵称并替换为用户名，还有一些细节需要优化，代码重构。

![image](https://cloud.githubusercontent.com/assets/7262715/14355338/26e67b70-fd13-11e5-8300-061c50e49ee5.png)

根据select中option数量适应pop menu的高度：
![image](https://cloud.githubusercontent.com/assets/7262715/14355470/9c113ff2-fd13-11e5-9d9b-365f30358c15.png)

**Comment by zzvv** [comment]
感谢！so happy~ 普天同庆

**Comment by zzvv** [comment]
已checkout，os x 下可用。
弱弱的再提个需求，不支持上下方向键选择候选人。虽然鼠标滚动亦可解决。
然而这可看作不是主要需求吧。只是建议。

**Comment by timothyyang96** [comment]
@geeeeeeeeek 如何checkout，以及每次复制文字到网页版内，前后都会有大段空行的bug

**Comment by timothyyang96** [comment]
@可以打包新的安装包吗？

**Comment by toddleo** [comment]
@geeeeeeeeek Hi, 经过实际使用, 有些情况下at好友并不能生效. 虽然在输入框中能够正常显示, 但是消息发送后只会显示消息正文和一个 `@` 符号. 例如在输入框中输入:

> Hi 今天有哪些功能能够部署? @vc

实际发送出去的消息为:

> Hi 今天有哪些功能能够部署? @

**Comment by nykma** [comment]
辛苦了。我发现有和客户端上行为不一致的地方。
在一个微信群里，一个用户有三个名字：
- 我给他设置的 **备注名**
- 他自己的 **账户昵称**
- 他自己在群里设置的 **群昵称**

官方客户端的行为：
- 打at符号后弹出的菜单里显示的是 **备注名**
- 最后落到输入框里的是 **群昵称**

本客户端的行为：
- 打at符号后弹出的菜单里显示的是 **备注名**
- 最后落到输入框里的是 **账户昵称**

我们看了下，感觉是web版拿不到 **群昵称**，那就算了吧

- - - - - 
其实怎样都无所谓了，反正被mention的人**收不到通知**，再怎么折腾自动补完都意义不大 ˊ _ >ˋ

**Comment by syslot** [comment]
### 怒赞，辛苦了

发现两个bug
- at群成员，别人没有收到通知
- 在某些情况下，客户端没有获取到at人的名称

发现新功能有个细节问题
- at完之后，光标仍然在at之前 
- at框不能显示图片

**Comment by toddleo** [comment]
@nykma @nykma 原来你们也是at别人, 别人收不到通知么

**Comment by nykma** [comment]
@toddleo 客户端在mention他人时，除了发送聊天内容`text`外还有一个被at的人列表`mentioned_list`（字段名是我瞎猜的，不过肯定有）。目前微信web端的API似乎不会接那个`mentioned_list`，可以试着抓个Mac端的包看看结构？

**Comment by geeeeeeeeek** [comment]
@nykma 如果协议不支持那就没有办法了…

**Comment by nykma** [comment]
@geeeeeeeeek 啥叫客户端parse？
我的意思是：
1. 我在客户端输入框里打了一串字： `下午要不要出去玩？ @`
2. 客户端弹出联想框，我选了 `geeeeeeeeek`
3. 现在输入框里是 `下午要不要出去玩？ @geeeeeeeeek`，并且客户端维护的一个 `mentioned_user_list` 里多了一项 `user_id_of_geeeeeeeeek`
4. 点击发送，客户端实际发送的payload为：
```json
{
  "text": "下午要不要出去玩？ @geeeeeeeeek",
  "mentioned_user_list": ["user_id_of_geeeeeeeeek"]
}
```

以上都是我的猜测，最好抓个windows或者手机客户端的包拆开看看究竟发了什么

**Comment by geeeeeeeeek** [comment]
@nykma 客户端的协议不太好分析，`mentioned_user_list`有一定道理，因为服务端要推送mention提醒

**Comment by geeeeeeeeek** [comment]
代码已经进入master分支。

后续的修改：
1. 修复了有时落到输入框里的文字错误，如果存在应该优先使用DisplayName。
2. 弹出菜单显示在正在输入的位置，跟随光标，输入时菜单不会移动。

示意图：
![image](https://cloud.githubusercontent.com/assets/7262715/14410163/8c092612-ff5a-11e5-85e2-95881610bb1e.png)

**但是，@这个功能需要微信服务端支持，在此之前实际上是没有什么卵用的。弹出菜单的UI先保留着。**

另外，还存在一些问题，比如@之后光标停留在第一个字符的位置，这个我无法修复。有兴趣可以看一下。

这个feature大概就这样了，没有异议的话过两天close了。

**Comment by geeeeeeeeek** [comment]
修复了`光标停留在第一个字符`和`issue`

**Comment by RobinsChens** [comment]
完美呀
