### ISSUE TITLE
linux如何从dock启动app？每次都要从终端启动吗

### ISSUE THREAD

**Issue by threezj** [geeeeeeeeek/electronic-wechat#331]

**Comment by Jonham** [comment]
你可以自己创建一个快捷方式。参见[#166](https://github.com/geeeeeeeeek/electronic-wechat/issues/166)。
如果你是要使用最新版本，你可以把
Exec=electron /path/to/github/electronic-wechat/src
Icon=/path/to/any-icon/your-want/wechat.png

详细参见[#166](https://github.com/geeeeeeeeek/electronic-wechat/issues/166)
