### ISSUE TITLE
Fedora XFCE环境中，点击“view”程序主界面无法弹出

### ISSUE THREAD

**Issue by Gabirel** [geeeeeeeeek/electronic-wechat#334]
#### Description

Fedora XFCE环境中，点击“view”程序主界面无法弹出

##### Dtail
当消息来的时候，会有个小窗，有`view`按钮，但是`view`按钮是失效的

#### Specifications

- Version of Electron (run `$ electron --version`): `v1.4.0`
- OS: `Fedora23 XFCE4`

**Comment by Kulbear** [comment]
Dup #327
