### ISSUE TITLE
自定义托盘图标 linux

### ISSUE THREAD

**Issue by Rocket1184** [geeeeeeeeek/electronic-wechat#335]
之前用[BearyChat linux版](https://bearychat.com/)(也是electronic打包)的时候，发现它的托盘图标文件就在应用目录`resources/app/image`下，对图标不满意的用户~~强迫症的我~~可以自由的更换托盘图标重启应用即可生效；

不过既然打包成了`.pak`文件，貌似只有重新编译才能修改了~~好吧我承认我懒死了~~

另外，不是所有linux用户都喜欢彩色图标的啊；~~而且还可以适配高分屏~~

要附张图佐证我的说法：
![default](https://cloud.githubusercontent.com/assets/13914967/18236347/b2265010-7357-11e6-8ea2-d4d92871a96f.png)

微信图标是不是又大又~~糊~~清晰

**Comment by geeeeeeeeek** [comment]
问题是…我如何检测你是深色主题还是浅色主题呢？原先是一个萌萌哒白色的icon，但在浅色主题下根本看不清，只好先用彩色的

**Comment by Rocket1184** [comment]
我的意思其实是，可以把托盘图标的png文件暴漏出来，这样可以方便进行替换；

也可以加个切换开关，让用户自由选择吧 = =

**Comment by amitbha** [comment]
楼主用的是ubuntu？哪个分支版本？感觉字体挺好看的

**Comment by Rocket1184** [comment]
@amitbha 就是最普通的 Ubuntu Unity 。版本是 16.04 LTS ，系统默认字体是文泉驿微米黑。

**Comment by amitbha** [comment]
哦，原来如此。还是ubuntu字体优化的最好啊
刚把17.10换arch了，gnome-shell崩的受不了
