### ISSUE TITLE
Error: failed to fetch from registry: eslint

### ISSUE THREAD

**Issue by zpf4934** [geeeeeeeeek/electronic-wechat#336]
#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- OS: `<OS>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by geeeeeeeeek** [comment]
@Kulbear assign 给你吧

**Comment by Kulbear** [comment]
@geeeeeeeeek OK～

@zpf4934 能不能发一下你 node 和 npm 的版本号以及报错信息，通常这个问题是版本过旧造成的。
试一下先参考[这个](http://stackoverflow.com/questions/12913141/message-failed-to-fetch-from-registry-while-trying-to-install-any-module)？

**Comment by zpf4934** [comment]
mylover@mylover:~/tools/wechat$ node --version
v0.6.12
mylover@mylover:~/tools/wechat$ npm -v
1.1.4
错误信息:
npm ERR! Error: failed to fetch from registry: eslint
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/mylover/tools/wechat/electronic-wechat/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.2.0-109-generic
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /home/mylover/tools/wechat/electronic-wechat
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: eslint
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/mylover/tools/wechat/electronic-wechat/npm-debug.log
npm not ok






在 2016-09-07 00:09:06，"Ji Yang" <notifications@github.com> 写道：


@geeeeeeeeek OK～

@zpf4934 能不能发一下你 node 和 npm 的版本号以及报错信息，通常这个问题是版本过旧造成的。
试一下先参考这个？

**Comment by Kulbear** [comment]
@zpf4934 你这个版本实在是太古董了－  － 更新一下node和npm如何？

**Comment by geeeeeeeeek** [comment]
node 0.6都什么时候的版本了..好歹6.0吧..你更新试试
