### ISSUE TITLE
扫码无法登录

### ISSUE THREAD

**Issue by manielng** [geeeeeeeeek/electronic-wechat#337]
#### Description

the latest version v1.4.0

#### Specifications

- Version of Electron (run `$ electron --version`): `v1.4.0`
- OS: `maos 10.11.6` 
- Stack trace from the error message (if any)

最新版扫码无法登录
``` 
<Stack trace here>
```

**Comment by Kulbear** [comment]
提供一些更多的信息？这个版本稳定使用了很久了按理说

**Comment by manielng** [comment]
登录微信提示需要升级微信, 但是微信目前是最新版, 二维码有问题
