### ISSUE TITLE
Archlinux 

### ISSUE THREAD

**Issue by ketop** [geeeeeeeeek/electronic-wechat#338]
![2016-09-06-143924_1591x520_scrot](https://cloud.githubusercontent.com/assets/15652413/18264006/2b81db1c-7440-11e6-95ad-9cbfef6c1a85.png)

#### Description
when i  use command line: npm start.and error occurrs,
it seems somthing wrong
libconf-2.so.4:cannot open shared object file

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- OS: `<OS>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```
***************************************
Oooooooh,i see . i dont  install gconf.  [Solved !]
******************************************

**Comment by geeeeeeeeek** [comment]
clean cache and reinstall
