### ISSUE TITLE
提供截图以及后台保持在线状态

### ISSUE THREAD

**Issue by seasonscao** [geeeeeeeeek/electronic-wechat#34]
First, make sure your issue is strictly related to the ***Electronic WeChat*** project. If it's a question or feature request, you can remove the template below.

#### Description

希望能参考 mac-wechat 的快捷键：

1.  ctrl + command + w 打开 wechat 主界面
2.  增加截图功能，保留 ctrl + command + a  截图快捷键

以及，解决后台在线，长时间未使用自动登出的问题。

最后，多谢作者的开发，很美观~加油~

**Comment by geeeeeeeeek** [comment]
快捷键在考虑，截图是需要自备应用的，不可能自带截图功能。

**Comment by iplus26** [comment]
截图的话可以使用Mac自带的功能

⌘ + shift + 2/3/4 

其中用2的话可以不在桌面生成而放到剪切板里 然后在聊天框中粘贴

**Comment by seasonscao** [comment]
@iplus26 command + shift + 2 ? 好像没有这个快捷键吧  不过用 command + shift + control + 4 可以放到剪切板 但是要按那么多键  好麻烦

**Comment by geeeeeeeeek** [comment]
你可以用腾讯的snapshot，系统层级的截图应用，只需从剪贴板复制到输入框即可发送。

考虑到electron和chrome是两套chromium环境，现在似乎没有办法给electron装上插件。

**Comment by iplus26** [comment]
@seasonscao 好吧我搜索了一下... [Apple Support](https://support.apple.com/en-gu/HT201361) 说到 

> To save your screenshot to the Clipboard instead of a file on your desktop, use Command-Shift-Control-4.

但是我真的可以用哎...你们都不可以吗...

**Comment by seasonscao** [comment]
@iplus26 哈哈哈 做不到 查了一下需要下软件来辅助快捷键
@geeeeeeeeek 多谢, 这个简单多了 按起来不别扭 ;-)

**Comment by laserroger** [comment]
后台保持在线状态现在有了吗。。

**Comment by laserroger** [comment]
@iplus26 可以在keyboard->shorcuts->screenshots里面把快捷键改了：
![image](https://cloud.githubusercontent.com/assets/7451488/17530283/e9984134-5e44-11e6-91a5-c54a86347392.png)
