### ISSUE TITLE
Mac OSX 10.11 无法打开

### ISSUE THREAD

**Issue by wangpc** [geeeeeeeeek/electronic-wechat#340]
#### Description
如图:
![image](https://cloud.githubusercontent.com/assets/4384465/18340409/57c47e3a-75d7-11e6-9690-039b909a6069.png)
更新1.4.0后无法使用

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- OS: `<Mac OS X El Capitan 10.11.6 >`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by Kulbear** [comment]
从旧版本更新的？直接下载最新的1.4.0 release 有这个情况吗
