### ISSUE TITLE
在elementary os中系统托盘区没图标

### ISSUE THREAD

**Issue by jnuyanfa** [geeeeeeeeek/electronic-wechat#342]
> GtkStatusIcon (the old API for apps to place icons in the panel) has been deprecated since 2014 and is not implemented in elementary OS. 

#### Specifications

- Version of Electron (run `$ electron --version`): `v1.4`
- OS: `Elementary OS 0.4`

**Comment by 9sunrise9** [comment]
in *.desktop file, add  `env XDG_CURRENT_DESKTOP=Unity`  like:
```
Exec=env XDG_CURRENT_DESKTOP=Unity /**/**/electronic-wechat/dist/electronic-wechat-linux-x64/electronic-wechat
```

**Comment by jnuyanfa** [comment]
@9sunrise9 cool!
