### ISSUE TITLE
换行提示只针对Mac

### ISSUE THREAD

**Issue by koallen** [geeeeeeeeek/electronic-wechat#349]
#### Description

输入框的换行提示为`Cmd + Enter`，但是这只适用于Mac而不是Linux。有没有可能根据平台自动更改这个？

**Comment by geeeeeeeeek** [comment]
@koallen 因为我的 user agent 设置成了 Safari ，这是个细节问题，确实可以根据系统来更改

**Comment by Kulbear** [comment]
#380
