### ISSUE TITLE
二维码扫描确认后没响应

### ISSUE THREAD

**Issue by ole3021** [geeeeeeeeek/electronic-wechat#35]
First, make sure your issue is strictly related to the ***Electronic WeChat*** project. If it's a question or feature request, you can remove the template below.

#### Description
二维码扫描后 提示手机上确认，手机上确认后  没响应。。

**Comment by geeeeeeeeek** [comment]
@ole3021 你能否多次复现？用官方客户端有时也会出现这样的情况，是由网络状况导致的。

**Comment by ole3021** [comment]
@geeeeeeeeek 是的，不过官方的客户端并没有出现这个情况，我同时装了两个客户端 `electronic-wechat`是 release的版本， 但是官方的都可以正常登录，`electronic-wechat`扫描后 手机会弹出是否在mac上登录  确认后微信最上方没有提示说 已经mac登陆的消息，就没有反应了。
