### ISSUE TITLE
請問有辦法自動登入嗎？

### ISSUE THREAD

**Issue by laichiaheng** [geeeeeeeeek/electronic-wechat#351]
#### Description
每次都要從手機掃描 QR code，請問有辦法直接登入嗎？

#### Specifications
- Version of Electron (run `$ electron --version`): `v1.3.4`
- OS: `elementary OS 0.4 Loki (基於 Ubuntu 16.04)`

**Comment by Kulbear** [comment]
基于Web 微信的，不行。即使官方客户端都不能直接登录（但官方倒是可以免扫二维码，如果有实现方法欢迎PR啊）。
