### ISSUE TITLE
怎么总提示更新啊

### ISSUE THREAD

**Issue by vinceliuice** [geeeeeeeeek/electronic-wechat#354]
#### Description

已经是１．４版本了，每次打开都提示更新到１．４版
#### Specifications
- Version of Electron (run `$ electron --version`): `v0.0.0`
- OS: `<OS>`
- Stack trace from the error message (if any)

```
<Stack trace here>
```

**Comment by ChaceYoung** [comment]
+1 Ubuntu 14.04, version 1.4.0

**Comment by Kulbear** [comment]
之前一个判断版本号的逻辑有问题，已修复了应该。
