### ISSUE TITLE
[new feature] 建议： Linux 版本，增加进程唯一的验证

### ISSUE THREAD

**Issue by jiniang** [geeeeeeeeek/electronic-wechat#361]
#### Description

目前可以启动多个，建议增加PID唯一的验证避免启动多个程序

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- OS: `<OS>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by ripples-alive** [comment]
…我记得之前还有人问怎样多开…

**Comment by Kulbear** [comment]
感觉多开本身也是比官方强的一点2333

**Comment by stkevintan** [comment]
可以通过electron的makeSingleInstance接口实现。[官方文档](https://github.com/electron/electron/blob/v0.36.10/docs/api/app.md#appmakesingleinstancecallback)  

具体实现方法参考：https://github.com/stkevintan/electronic-wechat/blob/master/src/main.js#L31
终端启动命令：
```bash
electron /path/to/electronic-wechat  # 单实例
electron /path/to/electronic-wechat --newInstance # 创建另外一个实例 
```

同时在Linux下可以修改*.desktop添加创建新实例选项：
```ini
#!/usr/bin/env xdg-open

[Desktop Entry]
Type=Application
Name=Electronic WeChat
Comment=A better WeChat client
Exec=bash -c 'electron /path/to/electronic-wechat/'
Actions=new-instance;
...

[Desktop Action new-instance]
Name=New Instance
Name[zh_CN]=启动新实例
StartupWMClass=Wechat
Exec=bash -c 'electron /path/to/electronic-wechat/ --newInstance'

[NewInstance Shortcut Group]
Name=New Instance
Name[zh_CN]=启动新实例
Exec=bash -c 'electron /path/to/electronic-wechat/ --newInstance'
TargetEnvironment=Unity

```
