### ISSUE TITLE
添加好友

### ISSUE THREAD

**Issue by Y4m1n** [geeeeeeeeek/electronic-wechat#366]
#### Description

希望能够有添加好友的功能，像手机微信那样搜索微信号。
#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- OS: `<OS>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by Rocket1184** [comment]
微信网页版也不能直接搜微信号加好友，除非去扒微信的API = =
不过群聊里面是可以加的
