### ISSUE TITLE
无法生成APP

### ISSUE THREAD

**Issue by MichaelVipub** [geeeeeeeeek/electronic-wechat#374]
#### Description

npm install && npm start可以运行wechat。

但是build app的时候报错：
npm run build:linux
> electronic-wechat@1.4.0 build:linux /home/michael/src/git/wechat/electronic-wechat
> ./scripts/build.sh linux x64

Start packaging for linux x64.
Packaging app for platform linux x64 using electron v1.3.4
ENOENT: no such file or directory, rename '/tmp/electron-packager/linux-x64/electronic-wechat-linux-x64/electron' -> '/tmp/electron-packager/linux-x64/electronic-wechat-linux-x64/electronic-wechat'
经核查目录下确实没有这两个目录或者文件。

不过/tmp/electron-packager/linux-x64/electronic-wechat-linux-x64//resources 目录下有个文件app.asar。

这就是我知道的东西了。

#### Specifications

- Version of Electron (run `$ electron --version`): `v1.3.4`
- OS: `ubuntu`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
michael@vip:~/src/git/wechat/electronic-wechat$ npm run build:linux

> electronic-wechat@1.4.0 build:linux /home/michael/src/git/wechat/electronic-wechat
> ./scripts/build.sh linux x64

Start packaging for linux x64.
Packaging app for platform linux x64 using electron v1.3.4
ENOENT: no such file or directory, rename '/tmp/electron-packager/linux-x64/electronic-wechat-linux-x64/electron' -> '/tmp/electron-packager/linux-x64/electronic-wechat-linux-x64/electronic-wechat'

```

**Comment by EdwardYuan** [comment]
ubuntu 16.04 运行 npm run build:linux之后
> electronic-wechat@1.4.0 build:linux /home/edward/bin/electronic-wechat
> ./scripts/build.sh linux x64

Start packaging for linux x64.
Packaging app for platform linux x64 using electron v1.4.6

就这样两个小时了，一点动静都没有。。。

**Comment by Kulbear** [comment]
@EdwardYuan 下午due完作业我去Linux上测一下 按理说不太应该。
另外请使用production branch的source code
https://github.com/geeeeeeeeek/electronic-wechat/tree/production
