### ISSUE TITLE
failed to see the merge-forward messages which have inline-link

### ISSUE THREAD

**Issue by saleo** [geeeeeeeeek/electronic-wechat#375]
#### Description

Great work,thank you!

not sure whether can see the merge-forward messages which have NOT inline link

#### Specifications
-Version v1.4.0
- Version of Electron (run `$ electron --version`): `v1.3.4`
- OS: `ubuntu16.04(64 bit)`
-Chrome 53.0.2785.143 Built on Ubuntu

- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by geeeeeeeeek** [comment]
I don't understand your question.
