### ISSUE TITLE
no such file or directory, open '*/trayConfig.json'

### ISSUE THREAD

**Issue by yixd** [geeeeeeeeek/electronic-wechat#376]
#### Description
A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT: no such file or directory, open '/home/yixd/.config/electronic-wechat/trayConfig.json'
    at Error (native)

#### Specifications

- Version of Electron (run `$ electron --version`): `v1.4.6`
- OS: `linux`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by Kulbear** [comment]
重新打包一下应该就好了

**Comment by xinshouke** [comment]
@Kulbear I met this problem on platform both CentOS7 and win10. After executed  npm run build:win64 on platform win10, the problem still happened once again.

**Comment by merlinpang** [comment]
Under src/windows/controllers/app_tray.js

we can see

```
class AppTray {
  constructor(splashWindow, wechatWindow) {
    this.splashWindow = splashWindow;
    this.wechatWindow = wechatWindow;
    this.TRAY_CONFIG_PATH = path.join(app.getPath('appData'), 'electronic-wechat/trayConfig.json');
    this.lastUnreadStat = 0;

    fs.readFile(this.TRAY_CONFIG_PATH, (err, data) => {
      if (err) {
        this.trayColor = 'white';
        fs.writeFile(this.TRAY_CONFIG_PATH, '{"color":"white"}');
      } else {
        this.trayColor = JSON.parse(data.toString()).color;
      }
      this.createTray();
    });
  }
```

So, I manually create a ```trayConfig.json``` under your path ```/home/your_username/.config/electronic-wechat/trayConfig.json```

within the json File we fill with ```{"color":"white"}```,

and this will "manually" fix this problem.

**Comment by Kulbear** [comment]
It's weird that 
```
if (err) {
        this.trayColor = 'white';
        fs.writeFile(this.TRAY_CONFIG_PATH, '{"color":"white"}');
}
```
doesn't work as expected...

**Comment by Kulbear** [comment]
#359
