### ISSUE TITLE
After a long delay, the wechat scan image expires and does not refresh

### ISSUE THREAD

**Issue by tianshuo** [geeeeeeeeek/electronic-wechat#377]
#### Description

After a long delay, the Wechat scan image expires and does not refresh. Scanning the image will tell the user that the image has expired. The only way to refresh the image is to exit `electronic wechat` and reopen it. Instead, the user should be able to click on the scan image and refresh it after a delay.
扫一扫的图片过一段时间会失效，用户应该可以点击该图片进行刷新，而不是非得强行重启客户端才行。

#### Specifications

- Version of Electron (run `$ electron --version`): `v1.4.0`
- OS: `MacOS 10.12 (16A323)`
- Stack trace from the error message (if any)

**Comment by Kulbear** [comment]
Command + R
