### ISSUE TITLE
消息复制问题

### ISSUE THREAD

**Issue by StevenChenSE** [geeeeeeeeek/electronic-wechat#382]
#### Description

ubuntu聊天无法复制消息，需要quote到输入框才能复制。。。

#### Specifications

- Version of Electron (run `$ electron --version`):v1.4.6
- OS: Linux thinkpad 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by stingbo** [comment]
我也有此问题

**Comment by bash-horatio** [comment]
同样有这个问题，不过是切换到lxqt之后才发现这个问题的，系统粘贴板为Qlipper。
之前用Debian + xfce4 没问题，好像是10月后换成Debian + lxqt就只能先quote 再copy。
不知是不是Eletron对QT类GUI支持不好？
