### ISSUE TITLE
npm ERR Failed at the electronic-wechat@1.4.0 start script 'electron src/ma    in.js'

### ISSUE THREAD

**Issue by zhangheng4117** [geeeeeeeeek/electronic-wechat#384]
npm start时报错，不知道是版本不兼容还是什么问题，请指教下！！！

- Version of Electron (run `$ electron --version`): `v1.4.0`
- OS: `<RHEL 6.5>`

``` 
<Stack trace here>error node v6.2.0
error npm  v3.8.9
error file sh
error code ELIFECYCLE
error errno ENOENT
error syscall spawn
error electronic-wechat@1.4.0 start: `electron src/main.js`
error spawn ENOENT
error Failed at the electronic-wechat@1.4.0 start script 'electron src/main.js'.
error Make sure you have the latest version of node.js and npm installed.
error If you do, this is most likely a problem with the electronic-wechat     package,
error not with npm itself.
error Tell the author that this fails on your system:
error     electron src/main.js
error You can get information on how to open an issue for this project with:
error     npm bugs electronic-wechat
error Or if that isn't available, you can get their info via:
error     npm owner ls electronic-wechat
error There is likely additional logging output above.
verbose exit [ 1, true ]

**Comment by Kulbear** [comment]
复现失败。

**Comment by microcai** [comment]
100% 重现。

**Comment by Kulbear** [comment]
@microcai 提供一下log？

**Comment by RobinRush** [comment]
robinlin@robinlin-virtual-machine:~/electronic-wechat$ npm start

> electronic-wechat@2.0.0 start /home/robinlin/electronic-wechat
> electron src/main.js

/home/robinlin/electronic-wechat/node_modules/electron/index.js:9
  throw new Error('Electron failed to install correctly, please delete node_modules/' + path.basename(__dirname) + ' and try installing again')
  ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at Object.<anonymous> (/home/robinlin/electronic-wechat/node_modules/electron/index.js:9:9)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/robinlin/electronic-wechat/node_modules/electron/cli.js:3:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! electronic-wechat@2.0.0 start: `electron src/main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electronic-wechat@2.0.0 start script 'electron src/main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electronic-wechat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron src/main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electronic-wechat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electronic-wechat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/robinlin/electronic-wechat/npm-debug.log

**Comment by Kulbear** [comment]
@RobinRush 
Version of Electron (run $ electron --version): 
OS:

另外Node版本换到6.9 + 试试？不要7

**Comment by RobinRush** [comment]
robinlin@robinlin-virtual-machine:~/electronic-wechat$ sudo npm start

> electronic-wechat@2.0.0 start /home/robinlin/electronic-wechat
> electron src/main.js

/home/robinlin/electronic-wechat/node_modules/electron/index.js:9
  throw new Error('Electron failed to install correctly, please delete node_modules/' + path.basename(__dirname) + ' and try installing again')
  ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at Object.<anonymous> (/home/robinlin/electronic-wechat/node_modules/electron/index.js:9:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/robinlin/electronic-wechat/node_modules/electron/cli.js:3:16)
    at Module._compile (module.js:570:32)

npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/home/robinlin/node-v6.9.5-linux-x64/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! electronic-wechat@2.0.0 start: `electron src/main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electronic-wechat@2.0.0 start script 'electron src/main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electronic-wechat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron src/main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electronic-wechat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electronic-wechat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/robinlin/electronic-wechat/npm-debug.log

**Comment by pokerWu** [comment]
我也是这样的错误。node 6.10.0 , os:Ubuntu 16.04, 错误都是一样的 /electron/index.js:9:9

**Comment by Kulbear** [comment]
@pokerWu 
@RobinRush 
Master branch的代码也不行吗

**Comment by pokerWu** [comment]
@Kulbear 默认拉取的应该就是master branch?
我用最新的node 7，也运行不了

**Comment by Kulbear** [comment]
@pokerWu 有可能是之前electron版本没有锁在1.4.15造成的？我现在在package.json里锁在了1.4.15。

另外这个错误是因为electron没有成功安装，跟项目还没有什么关系呢。。

**Comment by dsseter** [comment]
npm list 显示已经安装了. 
└── lodash.pickby@4.6.0
├─┬ electron@1.4.15
│ ├─┬ electron-download@3.3.0
│ │ ├─┬ fs-extra@0.30.0
│ │ │ ├── klaw@1.3.1
│ │ │ └── rimraf@2.6.1
│ │ ├── home-path@1.0.3
│ │ ├─┬ nugget@2.0.1
│ │ │ ├─┬ pretty-bytes@1.0.4
│ │ │ │ ├── get-stdin@4.0.1
实际运行还有这个问题.

**Comment by RobinRush** [comment]
哦，后来我用了cnpm就可以了。@ALL
