### ISSUE TITLE
如何修改字体，ubuntu默认的字体太丑了

### ISSUE THREAD

**Issue by Yufeikang** [geeeeeeeeek/electronic-wechat#385]
#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- OS: `<OS>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by Kulbear** [comment]
暂时没有支持的计划 欢迎PR

**Comment by saicoco** [comment]
@Yufeikang 去改代码的css文件就好了

**Comment by Yufeikang** [comment]
关闭
