### ISSUE TITLE
scripts/build-win32.bat needs electron version(1.1.0 -> 1.4.8) update 

### ISSUE THREAD

**Issue by cooka** [geeeeeeeeek/electronic-wechat#387]
#### Description
scripts/build-win32.bat needs update
`--version=1.1.0` may fail,  and `--version=1.4.8` works.

#### Specifications

- Version of Electron (run `$ electron --version`): `v1.4.0`
- OS: `Windows`
- Stack trace from the error message (if any)

``` 
set PLATFORM=%1%
set ARCH=%2%
set APP_NAME="Electronic WeChat"

set ignore_list="dist|scripts|\.idea|.*\.md|.*\.yml|node_modules/nodejieba"

electron-packager . "%APP_NAME%" --platform=%PLATFORM% --arch=%ARCH% --version=**1.4.8**  --app-version=1.3.0 --asar --icon=assets\icon.png --overwrite --out=.\dist --ignore=%ignore_list%
```

**Comment by Kulbear** [comment]
Updated in the master branch, not yet in the production branch
