### ISSUE TITLE
retina高分屏幕的字体有点小

### ISSUE THREAD

**Issue by kitech** [geeeeeeeeek/electronic-wechat#388]
#### Description

retina高分屏幕的字体有点小，在macbook pro 13 retina上安装的Linux桌面。

搜索到atom关于Linux hidpi的说明，但不知道怎么能用上。

https://atom.io/packages/hidpi

#### Specifications

- Version of Electron (run `$ electron --version`): `v1.4.8`
- OS: `Linux  + macbook pro 13 retina`
- Stack trace from the error message (if any)

``` 

```

**Comment by wu2008yu** [comment]
我也是遇到了这个问题，希望能有一个更改字号的功能

**Comment by kitech** [comment]
我的 linux 上 electron-v1.4.15 上已经好了，好像是自动使用了桌面的dpi的设置了，字体显示与其他程序一致。

**Comment by kitech** [comment]
最新版本v2.0 又出问题了。

**Comment by Kulbear** [comment]
（捂脸）应该没有改过这些东西啊。。。能截图一下吗，我看看

**Comment by kitech** [comment]
![image](https://cloud.githubusercontent.com/assets/24404/23194554/646422ba-f874-11e6-8086-59455206de03.png)

**Comment by kitech** [comment]
左边是2.0版本，右边是1.4版本

使用archlinux自带的electron 1.4.15-1

kde 桌面环境。

**Comment by Kulbear** [comment]
费解ing 感谢反馈 研究下

**Comment by Rocket1184** [comment]
估计是plasma的配置哪里有问题。。。我也是plasma，2倍缩放，显示正常

**Comment by kitech** [comment]
要是说plasma配置问题，相同的环境，两个版本同时启动，表现也不一样，不好确定了。

**Comment by Kulbear** [comment]
@kitech 你先试一下，我这边没有环境。Electron最近改动了不少接口，感觉除了几个比较大的linux发行版都不同程度受影响了。

**Comment by kitech** [comment]
调plasma 2倍缩放管用，但桌面就大的不协调了。

现在又遇到奇妙问题，我一般用scale 
1.6倍，然后临时改成1.7倍，启动electronic-wechat-2.0，没问题。

然后再改回1.6倍。

另外我还用了Xorg -dpi 168调整非kde程序的缩放。

还是多谢了。

**Comment by jimmy9065** [comment]
我使用的是I3，也有这个问题，字体和头像都很小
我看了下electron是用gtk3的，而我也设置了gtk3的放大设置
export GDK_SCALE=2
但是对它似乎无效
