### ISSUE TITLE
二维码时不时不显示。

### ISSUE THREAD

**Issue by ideepinos** [geeeeeeeeek/electronic-wechat#390]
二维码时不时不显示。
![20161202171328](https://cloud.githubusercontent.com/assets/17267091/20828521/e5e2729e-b8b2-11e6-97d3-b09164d901aa.png)

**Comment by Kulbear** [comment]
应该是网络问题

**Comment by whirlwind110** [comment]
你这套图标风格不错啊，求推荐。
