### ISSUE TITLE
Brings up application when clicking on notifications

### ISSUE THREAD

**Issue by ZizhengTai** [geeeeeeeeek/electronic-wechat#391]
#### Description

When I click on the notifications, they simply disappear instead of bringing up the application from background. Is this the expected behavior?

- If yes, I found it rather inconvenient. It would be much nicer if clicking on notifications brings up the app.
- If not, what could it be that I'm doing wrong?

#### Specifications

- Version of Electron: `v1.4.10`
- OS: Arch Linux kernel `4.8.11`, GNOME `3.22.2`

**Comment by Kulbear** [comment]
Dup #327
