### ISSUE TITLE
npm run build:linux 运行时间超过3个小时

### ISSUE THREAD

**Issue by fm365** [geeeeeeeeek/electronic-wechat#392]
#### Description
运行如下命令：
npm run build:linux
超过3个小时还是没有结果，正常吗？

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- OS: `<OS>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by stkevintan** [comment]
应该实在下载electron吧。你的错误信息呢？
