### ISSUE TITLE
不能接收微信表情包中的表情

### ISSUE THREAD

**Issue by longhaiyan** [geeeeeeeeek/electronic-wechat#393]
macosx 10.11.6
请问，关于不能接收表情这个问题是这个软件不提供支持还是我的版本问题？

**Comment by stkevintan** [comment]
不支持，web 端接口被封了。
详情： https://github.com/geeeeeeeeek/electronic-wechat/issues/2

**Comment by bash-horatio** [comment]
这个问题重复提了好多issue，请看
[ 微信表情包“野萌君”系列无法加载](https://github.com/geeeeeeeeek/electronic-wechat/issues/304)
作者有提及原因

P.S.  我们作为用户，既然都提了issue，何不在提之前先搜索一把，看看有没有类似的主题呢？这样既提高解决问题的效率，也避免给作者带来麻烦
