### ISSUE TITLE
NPM模块问题

### ISSUE THREAD

**Issue by carrjay** [geeeeeeeeek/electronic-wechat#396]
在安装NPM依赖这一步报错如下，:~/Downloads/ Electronic WeChat微信/electronic-wechat-master$ npm install 
npm WARN eslint-config-airbnb@13.0.0 requires a peer of eslint@^3.9.1 but none was installed. 
npm WARN eslint-config-airbnb@13.0.0 requires a peer of eslint-plugin-jsx-a11y@^2.2.3 but none was installed.
 npm WARN eslint-config-airbnb@13.0.0 requires a peer of eslint-plugin-import@^2.1.0 but none was installed.
 npm WARN eslint-config-airbnb@13.0.0 requires a peer of eslint-plugin-react@^6.6.0 but none was installed. 
npm WARN eslint-config-airbnb-base@10.0.1 requires a peer of eslint@^3.9.1 but none was installed. npm WARN eslint-config-airbnb-base@10.0.1 requires a peer of eslint-plugin-import@^2.1.0 but none was installed.
 npm WARN eslint-config-ndla@0.0.5 requires a peer of eslint@^3.9.1 but none was installed. 
npm WARN eslint-config-airbnb@12.0.0 requires a peer of eslint@^3.6.0 but none was installed.
 npm WARN eslint-config-airbnb@12.0.0 requires a peer of eslint-plugin-import@^1.16.0 but none was installed. 
npm WARN eslint-config-airbnb-base@8.0.0 requires a peer of eslint@^3.6.0 but none was installed. npm WARN eslint-config-airbnb-base@8.0.0 requires a peer of eslint-plugin-import@^1.16.0 but none was installed.求解啊，另外在反馈个你稳定版的下载地址，提示地址非法下载中断《移动宽带》

**Comment by wujysh** [comment]
#403
