### ISSUE TITLE
请问，目前是否有防止信息撤销功能

### ISSUE THREAD

**Issue by stingbo** [geeeeeeeeek/electronic-wechat#399]
#### Description

目前是否有防止信息撤销功能

#### Specifications

- Version of Electron (run `$ electron --version`): `v1.4.0`
- OS: `ubuntu 16.04LTS`
- Stack trace from the error message (if any)

``` 
目前是否有防止信息撤销功能
```

**Comment by prenfic** [comment]
semms... there it's?

**Comment by bash-horatio** [comment]
今天发现微信web版增加了“撤回”功能（其实还有“删除”）。在手机端“撤回”仍旧可以阻止，但是网页版“撤回”不可以～
