### ISSUE TITLE
一直显示 Reconnect，跟微信网页版证书过期有关吗？

### ISSUE THREAD

**Issue by XuQK** [geeeeeeeeek/electronic-wechat#405]
#### Description
自己从 Production 分支编译安装的。
网络状况良好，百兆光纤，深信服后台的局域网，不过看起来并没有对微信相关链接做限制，只是提示微信网页版证书过期，然后登录二维码刷不出来，和这个有关系吗？

#### Specifications

- Version of Electron (run `$ electron --version`): `v3.10.10`
- OS: `Ubuntu 16.04 x64`
- Stack trace from the error message (if any)

``` 
> electronic-wechat@1.4.0 start /home/xuqk/Tool/electronic-wechat
> electron src/main.js

Reconnect.
Reconnect.
Reconnect.
Reconnect.
Reconnect.
Reconnect.
Reconnect.
Reconnect.
Reconnect.
Reconnect.
Reconnect.
...
```

**Comment by XuQK** [comment]
基本查明了，单位的深信服局域网的锅，MDZZ

**Comment by hqglichao** [comment]
我也碰到这种情况了，怎么解决的？
