### ISSUE TITLE
动画表情不显示

### ISSUE THREAD

**Issue by ToQuery** [geeeeeeeeek/electronic-wechat#406]
#### Description

ubuntu 16.04 64bit 微信表情不显示

#### Specifications

- Version of Electron (run `$ electron --version`): `v1.4.0`
- OS: `ubuntu 16.04 64bit`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by iBreaker** [comment]
图片好像都不显示

**Comment by bash-horatio** [comment]
你们说的是“表情包”？请看
[ 微信表情包“野萌君”系列无法加载](https://github.com/geeeeeeeeek/electronic-wechat/issues/304)

作者有提及原因

**Comment by ToQuery** [comment]
OK,已了解！

见[微信表情包“野萌君”系列无法加载](https://github.com/geeeeeeeeek/electronic-wechat/issues/304)
