### ISSUE TITLE
Stop creating sound-machine-config.json in home directory

### ISSUE THREAD

**Issue by cuihaoleo** [geeeeeeeeek/electronic-wechat#407]
It's a little annoying that electronic-wechat creates sound-machine-config.json in home directory on Linux.

As a convention, config files should be located inside $XDG_CONFIG_HOME (default to ~/.config), or at least be stored in a hidden file (which name starts with a dot).

Please consider to move it :)

**Comment by Rocket1184** [comment]
consider to use version 1.4.0 instead :-)
i think the settings panel is not completed yet

**Comment by Kulbear** [comment]
@cuihaoleo  It will be removed/moved to a hidden directory. Currently it's not a production version. Please use the production release at this moment.
