### ISSUE TITLE
可以增加闪烁提示吗？

### ISSUE THREAD

**Issue by iBreaker** [geeeeeeeeek/electronic-wechat#408]
#### Specifications

- Version of Electron (run `$ electron --version`): `v1.3`
- OS: `Linux  4.4.0-3-deepin-amd64 #1 SMP Deepin 4.4.30-2 (2016-12-01) x86_64 GNU/Linux`
- Stack trace from the error message (if any)

``` 
可以增加闪烁提示吗？
```

**Comment by iBreaker** [comment]
类似于qq那样的

**Comment by Rocket1184** [comment]
现在的版本已经有了小红点提示未读消息了，等待下一次更新，或者自己从源码打包一下就可以用
