### ISSUE TITLE
Stickers don't display

### ISSUE THREAD

**Issue by setek** [geeeeeeeeek/electronic-wechat#409]
#### Description

Only a broken image icon displays. Does it only work with old sticker packs?

<img width="479" alt="screen shot 2017-01-11 at 16 50 37" src="https://cloud.githubusercontent.com/assets/5126295/21837273/e79b6038-d81e-11e6-8c59-15470da69612.png">

#### Specifications

- Version of Electron (run `$ electron --version`): `v1.4.0`
- OS: `OS X El Capitan 10.11.6 (15G1212)`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by Acris** [comment]
Same issue on Ubuntu 16.04 with v1.4.0.

**Comment by bash-horatio** [comment]
@setek @Acris 
Similar to issue [微信表情包“野萌君”系列无法加载](https://github.com/geeeeeeeeek/electronic-wechat/issues/304)

It is restricted by Wechat API, so unfortunately this problem won't be fixed

**Comment by hexchain** [comment]
RFE: Please consider displaying a placeholder image or notice instead of leaving the broken icon as is.
