### ISSUE TITLE
我是iOS开发者，可以利用这项目里面的接口开发一个iOS 客服端吗

### ISSUE THREAD

**Issue by kensla** [geeeeeeeeek/electronic-wechat#412]
#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- OS: `<OS>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by kevinetc123** [comment]
这个项目只是对网页进行包装和一些hack而已。应该没有到分析API个程度。

**Comment by geeeeeeeeek** [comment]
@kensla 有一些分析微信 API 的项目，你 GitHub 上找找。理论可行，但是应该比较麻烦。
