### ISSUE TITLE
无法npm start

### ISSUE THREAD

**Issue by Ginger-z** [geeeeeeeeek/electronic-wechat#413]
npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/opt/node/bin/node" "/opt/node/bin/npm" "start"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! electronic-wechat@1.4.0 start: `electron src/main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electronic-wechat@1.4.0 start script 'electron src/main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electronic-wechat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron src/main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electronic-wechat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electronic-wechat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ginger/electronic-wechat/npm-debug.log

**Comment by Kulbear** [comment]
node版本太高了应该是
