### ISSUE TITLE
kde桌面无法在系统托盘弹出菜单

### ISSUE THREAD

**Issue by yswtrue** [geeeeeeeeek/electronic-wechat#416]
rt，我是arch，kde的，其他的大概正常，就是系统托盘无法打开菜单，然后我无法退出应用

**Comment by kun-zhou** [comment]
我也一样。 退出后wechat的icon还是在system tray.
![screenshot_20170125_233400](https://cloud.githubusercontent.com/assets/19158151/22320060/d237638e-e356-11e6-89fe-5084d65297f2.png)

**Comment by HelvinHan** [comment]
+1

**Comment by magicshield** [comment]
需要安装libappindicator-gtk3。

**Comment by Kulbear** [comment]
#438 参考这里
