### ISSUE TITLE
隐藏窗口时当前窗口的新消息没有小红点提示

### ISSUE THREAD

**Issue by wujysh** [geeeeeeeeek/electronic-wechat#417]
#### Description
当前聊天窗口有新消息时，托盘图标不会出现小红点。
窗口正常显示时应该如此，但窗口关闭隐藏后不应该。

**Comment by wujysh** [comment]
应该与微信网页版本身的机制有关，当前窗口是不会有`.icon.web_wechat_reddot_middle`的，所以获取不到。
可否隐藏是自动切换的`File Transfer`的聊天页，还原时再复原？
或者退到刚登陆网页版时没有选择任何聊天的状态？

**Comment by wujysh** [comment]
#418

**Comment by Kulbear** [comment]
#418 Merged
