### ISSUE TITLE
可以在状态栏显示icon及未读消息数

### ISSUE THREAD

**Issue by maxhis** [geeeeeeeeek/electronic-wechat#42]

**Comment by bubbless** [comment]
Archliux +Xfce4 状态栏无icon?

**Comment by maxhis** [comment]
@bubbless 不好意思，没说清楚，是Mac OS X。

**Comment by geeeeeeeeek** [comment]
谁发个pr？消息计数和electron的API都是现成的。

**Comment by alexzhang2015** [comment]
@maxhis 是 Mac上加menu bar icon吧

**Comment by maxhis** [comment]
@alexzhang2015 是的

**Comment by bubbless** [comment]
@maxhis Linux下无放状态栏Icon的计划吗

**Comment by geeeeeeeeek** [comment]
@bubbless electron的API应该做了跨平台(?)的支持，可以看下。

**Comment by iamcc** [comment]
已经pr

**Comment by geeeeeeeeek** [comment]
Fixed in #50. icon还需调整，颗粒感太强了。。

**Comment by alexzhang2015** [comment]
试了下 还不错，不知道 能做成灰色的不
