### ISSUE TITLE
ubuntu下npm安装不成功

### ISSUE THREAD

**Issue by yuxinvalo** [geeeeeeeeek/electronic-wechat#423]
#### Description
在ubuntu下安装了nodejs和nmp.. 但是按照提示安装build的时候,出毛病了

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- OS: `<Ubuntu LTS16>`
- Stack trace from the error message (if any)
错误信息:
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:354:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-43-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/tearsyu/WeChat Files/electronic-wechat/node_modules/nodejieba
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:nodejieba@2.2.4 nodejieba@2.2.4 install: `node-gyp rebuild`
npm WARN install:nodejieba@2.2.4 Exit status 1

``` 
<Stack trace here>
```
结果:
npm WARN eslint-config-airbnb@13.0.0 requires a peer of eslint-plugin-jsx-a11y@^2.2.3 but none was installed.
npm ERR! Linux 4.4.0-43-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! electron@1.4.15 postinstall: `node install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the electron@1.4.15 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tearsyu/WeChat Files/electronic-wechat/npm-debug.log

**Comment by zenozeng** [comment]
@yuxinvalo 试试：`sudo ln -s /usr/bin/nodejs /usr/bin/node`

**Comment by stlfatboy** [comment]
npm install 后卡在
loadDep:electron-localsho ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟

**Comment by bash-horatio** [comment]
关于手动build，之前有类似的问题，可以自行搜索issue
`/bin/sh: 1: node: not found`
这句错误很明显，在Debian系的要安装`node-legacy`这个包，实际原理和楼上说的类似
```
$ ls -l /usr/bin/node                                                                                                                                                  
lrwxrwxrwx 1 root root 6 Jan  6 08:25 /usr/bin/node -> nodejs
```

**Comment by yuxinShi02** [comment]
谢谢!

**Comment by whatisjava** [comment]
> nodejieba@2.2.5 install /home/whatisjava/Applications/electronic-wechat/node_modules/nodejieba
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/whatisjava/Applications/electronic-wechat/node_modules/nodejieba/build'
gyp ERR! System Linux 4.10.0-38-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/whatisjava/Applications/electronic-wechat/node_modules/nodejieba
gyp ERR! node -v v8.8.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

> electron@1.4.15 postinstall /home/whatisjava/Applications/electronic-wechat/node_modules/electron
> node install.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: nodejieba@2.2.5 (node_modules/nodejieba):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: nodejieba@2.2.5 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 8 packages in 60.562s

**Comment by whatisjava** [comment]
ubuntu16.04
