### ISSUE TITLE
npm WARN eslint-config-airbnb@13.0.0 requires a peer of eslint-plugin-jsx-a11y@^2.2.3 but none was installed.

### ISSUE THREAD

**Issue by linux0ne** [geeeeeeeeek/electronic-wechat#425]
今天刚刚下载的源码，到了npm install的步骤，提示“题目”的内容，这是咋地了？

**Comment by linux0ne** [comment]
朋友们，可否帮忙指点一下，即使没有答案，也告诉一下怎么个思路去找答案呗

**Comment by Rocket1184** [comment]
如果只有warn的话不影响构建的吧

**Comment by Kulbear** [comment]
Solved

**Comment by linux0ne** [comment]
@Kulbear 
呵呵 ，没明白，怎么就Solved了  ？

这个WANG直接忽略就可以呗？ 不影响？

**Comment by Kulbear** [comment]
Master branch 中已经加了 
：)
4天前就 commit 了
你不看 commit 我也没办法
