### ISSUE TITLE
AppConfig is not defined

### ISSUE THREAD

**Issue by lxcuso4** [geeeeeeeeek/electronic-wechat#428]
####  webwechat升级后，preload.js 文件中的 checkEmojiContent 这个函数中使用的AppConfig 未定义

- Version of Electron (run `$ electron --version`): `v1.4.0`
- OS: `<OS>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by Kulbear** [comment]
请问现在还有这个问题吗？
