### ISSUE TITLE
Version number in package.json not updated

### ISSUE THREAD

**Issue by hexchain** [geeeeeeeeek/electronic-wechat#430]
It's still `1.4.0`.

**Comment by Kulbear** [comment]
will be update in final release

**Comment by hexchain** [comment]
Oh, but there's already a tag called `v2.0`...

**Comment by Rocket1184** [comment]
just release-candidate

**Comment by hexchain** [comment]
Umm, not really: https://github.com/geeeeeeeeek/electronic-wechat/releases/tag/v2.0

Could be a mistake anyway.

**Comment by Kulbear** [comment]
@hexchain Silly me, forgot to delete the wrong release...
