### ISSUE TITLE
ESC关闭窗口问题

### ISSUE THREAD

**Issue by Vogen** [geeeeeeeeek/electronic-wechat#434]
我有个习惯是打字的时候喜欢按ESC，但是会关闭窗口。
希望能够在Preference中加入‘是否使用ESC关闭窗口’的选项

**Comment by Kulbear** [comment]
好的，加入2.0.1

**Comment by Kulbear** [comment]
@Vogen 我们认为换一个别的键可能更好 比如

    CtrlORCommnad + `

**Comment by wujysh** [comment]
干脆定义个全局隐藏/显示的热键吧，在配置里可以改的

2017年2月17日 下午12:14，"Ji Yang" <notifications@github.com>写道：

**Comment by wujysh** [comment]
linux上点新消息的通知没用，不能弹出聊天窗口，每次去右键那个图标很麻烦的。

2017年2月17日 下午12:19，"Jiaye Wu" <wujysh@gmail.com>写道：

**Comment by Kulbear** [comment]
@wujysh
通知不能谈窗口是electron自己的一个很古老的bug

**Comment by wujysh** [comment]
对呀我知道，但我觉得这个客户端的主要使用人群是linux的吧，其他平台都有官方客户端。应该想办法方便下linux的用户呀。
托盘图标点击也是没用的，只能右键。所以上次才会发全局隐藏显示的pr

2017年2月17日 下午1:05，"Ji Yang" <notifications@github.com>写道：

@wujysh <https://github.com/wujysh>
通知不能谈窗口是electron自己的一个很古老的bug

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/geeeeeeeeek/electronic-wechat/issues/434#issuecomment-280553734>,
or mute the thread

**Comment by Kulbear** [comment]
@wujysh 
目前有大概7，8种不同发行版的 Linux 相关 issue 实在没有精力每个都弄个虚拟机。。

**Comment by wujysh** [comment]
@Kulbear 
Ubuntu LTS版本总要支持吧:)
p.s. 你们认为全局热键哪里不好？影响别的软件工作？

**Comment by Kulbear** [comment]
嗯全局热键是。

**Comment by wujysh** [comment]
@Kulbear 托盘图标的菜单顺序最好调整下，show放到第一个，change icon应该不常用，放在那容易点错，可以放到设置里。

**Comment by xgdgsc** [comment]
我习惯了esc退出微信的图片展示，希望可以设置。

**Comment by wzxjohn** [comment]
好想知道这个功能是谁提出来的。。。ESC 键一般不都是用来退打开的图片展示么 QAQ。。。难过死了。。。

**Comment by Kulbear** [comment]
修改到常规的 `CommandOrControl + H` 了

**Comment by xgdgsc** [comment]
这个问题就值得一个新的release了吧，求新release。

**Comment by xgdgsc** [comment]
求新release

**Comment by Rocket1184** [comment]
@xgdgsc 你需要 Linux 版还是 Mac 版？我这边有打包的环境......

**Comment by Rocket1184** [comment]
刚打好的热乎的二进制包
[darwin](http://oo53f01ed.bkt.clouddn.com/ElectronicWeChat-darwin-x64-0660f34.tar.gz)
[linux64](http://oo53f01ed.bkt.clouddn.com/electronic-wechat-linux-x64-0660f34.tar.gz)

**Comment by xgdgsc** [comment]
谢谢，这个我倒不需要，从archlinuxcn源里可以直接装，只是觉得应该release下

**Comment by Mitnick5194** [comment]
请问在哪里下载的 我在https://github.com/geeeeeeeeek/electronic-wechat/releases这里下载了一个一百多兆的 但是解压出来的都时源码文件 没有安装文件 而且下载速度很慢 期望大家的解答 谢谢！！！

**Comment by Roller44** [comment]
直接执行“electronic-wechat”就可以了。

**Comment by alswl** [comment]
改了一下，直接去掉了隐藏功能。
https://github.com/alswl/electronic-wechat

**Comment by MoSunDay** [comment]
`Ubuntu` 以及衍生发行版一般是 `ctrl + w` 吧... `Slack` 和 `QQ` 以及 谷歌浏览器 都是用 `ctrl + w` 关闭的, 关闭 `electronic-wechat` 总觉得有点不习惯...
