### ISSUE TITLE
提个建议：没有官方最新的小黄脸表情，望添加。

### ISSUE THREAD

**Issue by yehon** [geeeeeeeeek/electronic-wechat#435]
如题…

再次感谢开发者的付出。

**Comment by Kulbear** [comment]
这个不一定能实现，我关注一下。

**Comment by yehon** [comment]
@Kulbear 我没上过网页版，但我的理解，从客户端抓出来，然后做成表情映射即可吧，因为微信的表情其实都是文字。比如：[捂脸]

**Comment by yehon** [comment]
看了下，网页版没有。…

**Comment by Kulbear** [comment]
hmm，我也很喜欢新的那几个表情 （捂脸）
我和朋友探讨一下，不能保证近期添加哈

**Comment by yehon** [comment]
@Kulbear 赞！👍

**Comment by ZizhengTai** [comment]
Seems the issue is resolved in the latest release. Could you please close this?

**Comment by WuShichao** [comment]
@ZizhengTai 哇，竟然在这里看见邰子正兄了
