### ISSUE TITLE
新 Issue 请务必遵循模版，避免导致优先级降低或直接关闭。

### ISSUE THREAD

**Issue by Kulbear** [geeeeeeeeek/electronic-wechat#437]
#### Description

First of all, thanks for your attention to open an issue for this project.
Please notice that if you are requesting a **feature**, then you should give a **brief description** of your request.
If you are reporting a **bug**, please **follow the template** below.
A bug report **without detailed information** required will have a **very low priority** and even be **ignored** (closed directly)!

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- OS: `<OS>`
- Stack trace from the error message (if any)

```
<Stack trace here>
```

**Comment by xgdgsc** [comment]
直接改报issue的模板为中文吧，估计英文很多人不太注意。
