### ISSUE TITLE
Windows下没有偏好设置菜单

### ISSUE THREAD

**Issue by jiangming1399** [geeeeeeeeek/electronic-wechat#440]
#### 描述
Windows下没有偏好设置菜单，似乎只做了osx的适配。手工修改菜单文件后发现设置菜单出现了万恶的滚动条（

![qq 20170220131350](https://cloud.githubusercontent.com/assets/6049028/23112871/ce604c9a-f76e-11e6-98a9-5a5decb626b7.png)

#### Specifications

- Version of Electron (run `$ electron --version`): `v1.4.15`
- OS: `Windows 10`
- Stack trace from the error message (if any)

```
<Stack trace here>
```

**Comment by Kulbear** [comment]
收到。

**Comment by JosephusZhou** [comment]
请教你是否尝试过在windows下编译Release版本，我尝试编译一直卡着不动，任务管理器显示Node占用了大量CPU、内存和磁盘读写，等了好久，然后就显示失败了.

**Comment by jiangming1399** [comment]
@JosephusZhou 似乎没有遇到你所说的问题

**Comment by Kulbear** [comment]
@jiangming1399 在改这个。。不过为啥 Windows 不用官方的呢。。 Just 好奇没有别的意思

**Comment by jiangming1399** [comment]
恩……看看会不会好用一点嘛2333

**Comment by Kulbear** [comment]
@jiangming1399 嗯我就是突然想起来，README里 
![image](https://cloud.githubusercontent.com/assets/14886380/24354791/d9711470-1325-11e7-958a-a6207e8a7a0e.png)

**Comment by geeeeeeeeek** [comment]
Windows 暂时没有维护的打算…

**Comment by jiangming1399** [comment]
噗（
