### ISSUE TITLE
Ubuntu16.04在仓库里npm start出错,nodejs和npm均为官方最新，资历不足望告知

### ISSUE THREAD

**Issue by SZooo** [geeeeeeeeek/electronic-wechat#441]
#### Description

0 info it worked if it ends with ok
1 verbose cli [ '/node-v7.5.0-linux-x64/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@4.2.0
3 info using node@v7.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle electronic-wechat@2.0.0~prestart: electronic-wechat@2.0.0
6 silly lifecycle electronic-wechat@2.0.0~prestart: no script for prestart, continuing
7 info lifecycle electronic-wechat@2.0.0~start: electronic-wechat@2.0.0
8 verbose lifecycle electronic-wechat@2.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle electronic-wechat@2.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/electronic-wechat/node_modules/.bin:/java/jdk1.8.0_101/bin:/java/Sdk/platform-tools/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:${JAVA_HOME}/bin:/java/Sdk/platform-tools/
10 verbose lifecycle electronic-wechat@2.0.0~start: CWD: /electronic-wechat
11 silly lifecycle electronic-wechat@2.0.0~start: Args: [ '-c', 'electron src/main.js' ]
12 silly lifecycle electronic-wechat@2.0.0~start: Returned: code: 1  signal: null
13 info lifecycle electronic-wechat@2.0.0~start: Failed to exec start script
14 verbose stack Error: electronic-wechat@2.0.0 start: `electron src/main.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:192:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:192:7)
14 verbose stack     at maybeClose (internal/child_process.js:890:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid electronic-wechat@2.0.0
16 verbose cwd /electronic-wechat
17 error Linux 4.4.0-63-generic
18 error argv "/node-v7.5.0-linux-x64/bin/node" "/usr/local/bin/npm" "start"
19 error node v7.5.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 1
23 error electronic-wechat@2.0.0 start: `electron src/main.js`
23 error Exit status 1
24 error Failed at the electronic-wechat@2.0.0 start script 'electron src/main.js'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the electronic-wechat package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     electron src/main.js
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs electronic-wechat
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls electronic-wechat
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by Kulbear** [comment]
换 node 6.9 试试

**Comment by Kulbear** [comment]
close [no response]

**Comment by zaihuishou** [comment]
问题同上，求解决办法

**Comment by zaihuishou** [comment]
npm ERR! Linux 4.8.0-39-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! path /home/zhiqiang/opt/electronic-wechat-linux-x64/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/zhiqiang/opt/electronic-wechat-linux-x64/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/home/zhiqiang/opt/electronic-wechat-linux-x64/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/zhiqiang/opt/electronic-wechat-linux-x64/npm-debug.log

**Comment by Kulbear** [comment]
这根本不是一个问题。。= 。 = 重新下载过吗 看起来是有个文件找不到了 没有遇到别的用户有这个情况的

**Comment by zaihuishou** [comment]
我下了几次了

**Comment by evilloop** [comment]
执行npm start的目录不对吧


发自网易邮箱大师
在2017年03月01日 15:50，tanzhiqiang 写道：

我下了几次了

**Comment by ezrealan** [comment]
一样的问题，=

**Comment by Kulbear** [comment]
@zaihuishou 这个明显是package.json找不到 这个文件就在最上层，master branch你也可以看到的。如果没有说明你目录错了。。
@ezrealan 和谁一样的？这上面几个人说的都不是一回事
