### ISSUE TITLE
我想把了解如何构造发图片部分功能,文本部分试着截包可以用js实现,发图片这个就弄不了,请问能只通过js做到发图片吗?

### ISSUE THREAD

**Issue by huangzi959** [geeeeeeeeek/electronic-wechat#443]
#### Description

First of all, thanks for your attention to open an issue for this project.
Please notice that if you are requesting a **feature**, then you should give a **brief description** of your request.
If you are reporting a **bug**, please **follow the template** below.
A bug report **without detailed information** required will have a **very low priority** and even be **ignored** (closed directly)!

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- OS: `<OS>`
- Stack trace from the error message (if any)

```
<Stack trace here>
```

**Comment by geeeeeeeeek** [comment]
没看懂
