### ISSUE TITLE
提个建议：能否添加关闭Esc一键退出的选项

### ISSUE THREAD

**Issue by halexan** [geeeeeeeeek/electronic-wechat#450]
#### Description

在打字的时候，习惯使用Esc键取消打错的字，但与此同时微信也退出了，很尴尬。。

#### Specifications

- Version of Electron (run `$ electron --version`): `v2.0`
- OS: `Ubuntu 14.04`
- Stack trace from the error message (if any)

```
<Stack trace here>
```

**Comment by Kulbear** [comment]
Dup #434
