### ISSUE TITLE
添加proxy控制

### ISSUE THREAD

**Issue by tydlwav** [geeeeeeeeek/electronic-wechat#452]
#### Description

希望能够在用electronic wechat时候控制是直接连接还是使用proxy。我习惯于把shadowsocks挂上不关，因此每次用electronic wechat时候都会极其慢，迫使我从firefox上选择no proxy，再在Firefox上使用微信。

#### Specifications

- Version of Electron (run `$ electron --version`): `v1.4.15`
- OS: `Arch Linux`
- Stack trace from the error message (if any)

```
<Stack trace here>
```

**Comment by coder30** [comment]
我也是这样的，但是我即使不走shadowsocks还是会很慢，有时图片甚至会挂掉

**Comment by geeeeeeeeek** [comment]
建议用第三方软件控制。
