### ISSUE TITLE
SELinux Confined User (staff_u) cannot start electronic-wechat

### ISSUE THREAD

**Issue by LanstonWu** [geeeeeeeeek/electronic-wechat#453]
#### Description

For security,I had configured SELinux Confined User (staff_u) following the guide from http://danwalsh.livejournal.com/66587.html ,after all have done,I reboot and login in,check it has successful;
```
$ id -Z
staff_u:staff_r:staff_t:s0:c0.c1023
```
but when I start electronic-wechat,I got this error;
```
$ ./electronic-wechat 
p11-kit: couldn't open and map file: /etc/pki/ca-trust/source/README: Permission denied
p11-kit: couldn't open and map file: /usr/share/pki/ca-trust-source/ca-bundle.neutral-trust.crt: Permission denied
p11-kit: couldn't open and map file: /usr/share/pki/ca-trust-source/ca-bundle.trust.crt: Permission denied
p11-kit: couldn't open and map file: /usr/share/pki/ca-trust-source/README: Permission denied
p11-kit: couldn't open and map file: /usr/share/pki/ca-trust-source/ca-bundle.supplement.p11-kit: Permission denied
Reconnect.
Reconnect.
Reconnect.
Reconnect.
Reconnect.
Reconnect.
Reconnect.
Reconnect.
```
I tried to change the permission of file and directory ,but nothing has changed.
I can start it with sudo role,but some other problem cased,for example,I cannot use sogou-pinyin, and I'm worried I don't know if some security happened in background ...
can anyone explain what had happened?how to resolve it ?

#### Specifications

- Version of Electron (run `$ electron --version`): `v1.4.15`
- OS: `Fedora 25`

**Comment by geeeeeeeeek** [comment]
@LanstonWu Should be related to Electron or your configuration itself. Open an issue in Electron's repo if you'd like to.
