### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

### ISSUE THREAD

**Issue by xuchendev** [geeeeeeeeek/electronic-wechat#454]
meet some problem in the build step

> electronic-wechat@2.0.0 build:linux /home/xuchen/Downloads/electronic-wechat
> ./scripts/build.sh linux x64

Start packaging for linux x64.
Packaging app for platform linux x64 using electron v1.4.15

<--- Last few GCs --->

  655057 ms: Mark-sweep 1396.9 (1458.1) -> 1396.6 (1458.1) MB, 120.3 / 1 ms (+ 1154.9 ms in 20 steps since start of marking, biggest step 792.0 ms) [allocation failure] [GC in old space requested].
  656204 ms: Mark-sweep 1396.6 (1458.1) -> 1396.4 (1458.1) MB, 1147.4 / 1 ms [last resort gc].
  657363 ms: Mark-sweep 1396.4 (1458.1) -> 1396.4 (1458.1) MB, 1159.4 / 1 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x57ba1eb4629 <JS Object>
    1: pipe [_stream_readable.js:~452] [pc=0x3a23abda73e4] (this=0xed740c1acf9 <a ReadStream with map 0x2613506c4ed9>,dest=0x27d2b15f2d79 <a WriteStream with map 0x2613506c4a61>,pipeOpts=0x57ba1e041b9 <undefined>)
    2: arguments adaptor frame: 1->2
    3: /* anonymous */ [/home/xuchen/Downloads/electronic-wechat/node_modules/.2.0.0@fs-extra/lib/copy/ncp.js:108] [pc=0x3a23a0382099] (this=0x27d2...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
./scripts/build.sh: line 30:  7969 Aborted                 electron-packager . "${APP_NAME}" --platform=$PLATFORM --arch=$ARCH --electronVersion=1.4.15 --app-version=1.4.0 --asar --icon=assets/icon.icns --overwrite --out=./dist --ignore=${ignore_list}

**Comment by geeeeeeeeek** [comment]
@xuchendev Looks like it's related to your own environment. What's its memory size? Can you reproduce it everytime?
