### ISSUE TITLE
windows下编译版本开始后，一直没动静？

### ISSUE THREAD

**Issue by JosephusZhou** [geeeeeeeeek/electronic-wechat#457]
#### Description

windows下编译版本很慢，请问有什么方法加速吗？
![image](https://cloud.githubusercontent.com/assets/5844075/24071291/921a3070-0c09-11e7-9fc0-3c156f73f509.png)

#### Specifications

- Version of Electron (run `$ electron --version`): `v2.0.0`
- OS: `Windows8.1 64位`
- Stack trace from the error message (if any)

```
<Stack trace here>
```

**Comment by Kulbear** [comment]
应该是卡在了下载Electron的步骤

**Comment by JosephusZhou** [comment]
我改成了electron-builder后，1分钟内打包完成，我觉得是packger的问题
