### ISSUE TITLE
A JavaScript error occurred in the main process (app_tray.js:34:31)

### ISSUE THREAD

**Issue by Love4Taylor** [geeeeeeeeek/electronic-wechat#459]
- Version of Electron (run `$ electron --version`): `v1.4.15`
- OS: `Deepin 15.4 RC`
- Stack trace from the error message (if any)

```
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected end of JSON input
    at AppTray.fs.readFile (/home/love4taylor/GitCode/electronic-wechat/dist/electronic-wechat-linux-x64/resources/app.asar/src/windows/controllers/app_tray.js:34:31)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
```
打开就爆这个错 这是个啥问题

**Comment by Love4Taylor** [comment]
还有就是无法完全退出 当网络重新连接后 弹出n多个Wechat扫码窗口 应该是我多次开启程序的问题 但是退出不了 只能killall
![image](http://ws3.sinaimg.cn/large/005GmrUUgy1fdwmhc2otvj30jg0f1dia.jpg)

**Comment by FeynmanDNA** [comment]
me too, mine Javascript error message is: 
Uncaught Exception:
Error: ENOENT: no such file or directory, open '/home/tanuki/.config/electronic-wechat/trayConfig.json'
    at Error (native)

**Comment by Kulbear** [comment]
@FeynmanDNA 

    rm /home/tanuki/.config/electronic-wechat/trayConfig.json

**Comment by FeynmanDNA** [comment]
@Kulbear Tried removing, the file doesn't exist. Created an empty file by that name, now I get this:

`SyntaxError: Unexpected end of JSON input
    at AppTray.fs.readFile (/home/tanuki/bin/electronic-wechat/src/windows/controllers/app_tray.js:34:31)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)`

The app starts fine after this error message. Hope it helps development.

**Comment by Kulbear** [comment]
Just remove it and you are ready to go.
The application should be able to re-generate a new one for you.

**Comment by Kulbear** [comment]
@Love4Taylor This is an in-discussion feature. Some may argue that they want to hold multiple instances simultaneously but some prefer a single instance mode.

**Comment by FeynmanDNA** [comment]
I've fixed my issue, I was running the debug version using `npm start` which doesn't have error messages disabled. 

To get rid of error messages, you have to run the built version in `dist/`. Hope it helps.
