### ISSUE TITLE
你好， Linux客户端的表情好像有问题

### ISSUE THREAD

**Issue by chewenkai** [geeeeeeeeek/electronic-wechat#460]
#### Description
你好，谢谢您开发和维护这个优秀的微信客户端项目。
我在使用的过程中遇到一个问题，表情贴纸无法显示，全部显示一个裂开的图。但发送图片可以正常显示。希望能得到您的帮助。非常感谢。

#### Specifications

- Version of Electron (run `$ electron --version`): `V2.0`
- OS: `<Ubuntu 16.04>`
- Brower:`Chrome Latest Version(57.0.2987.110 (64-bit))`
- Stack trace from the error message (if any)

**Comment by wanggaolin** [comment]
解决了，把这个问题关闭吧！

**Comment by chewenkai** [comment]
@wanggaolin 非常感谢！
