### ISSUE TITLE
linux 环境一直输出Reconnect.

### ISSUE THREAD

**Issue by wanggaolin** [geeeeeeeeek/electronic-wechat#461]
linux 环境普通用户运行应用一直卡在starting app,并且终端一直输出:Reconnect.
electronic-wechat-linux-x64$ ./electronic-wechat 
Reconnect.
Reconnect.
Reconnect.
Reconnect.
Reconnect.
Reconnect.
Reconnect.
Reconnect.
Reconnect.
Reconnect.
Reconnect.
Reconnect.
Reconnect.
Reconnect.
Reconnect.
Reconnect.
Reconnect.
Reconnect.

**Comment by wanggaolin** [comment]
root 用户运行没有问题

**Comment by copie** [comment]
我也遇到了      不知道是什么问题
