### ISSUE TITLE
有没有开发文档

### ISSUE THREAD

**Issue by wellsyu** [geeeeeeeeek/electronic-wechat#463]
有没有开发文档呢，我想基于你们的项目再次开发

**Comment by evolutionjay** [comment]
啊，快更新啊，我好喜欢每个周一一大早看到有软件更新的样子（然而并不关心你们更新了什么）

**Comment by Asura-one** [comment]
+1

**Comment by wellsyu** [comment]
I try to add some new features to fit my work,is there some Developer Guide ?

**Comment by wellsyu** [comment]
I try to add some new features to fit my work,is there some Developer Guide ?

**Comment by geeeeeeeeek** [comment]
I'm back. 开发文档 不存在的 因为没时间写.
