### ISSUE TITLE
是否有办法可以自定义字号?

### ISSUE THREAD

**Issue by toddleo** [geeeeeeeeek/electronic-wechat#47]
现在用的显示器并不算是"高分", 但是文字确实很小有点伤眼, 在哪里可以自己配置字号大小么?

**Comment by geeeeeeeeek** [comment]
理论上可以注入修改，但不打算直接加入这个弱需求的功能。等到我插件hub做出来就可以自定义了。

**Comment by toddleo** [comment]
其实和保存消息记录一样, 有个设置面板就可以自己配置了, 不一定非要做成插件 XD

**Comment by geeeeeeeeek** [comment]
但是也没办法把所有细节都做成设置项啊..
