### ISSUE TITLE
ESC直接关闭窗口的体验问题

### ISSUE THREAD

**Issue by kishimotoindb** [geeeeeeeeek/electronic-wechat#471]
您好,目前在使用中有一个体验不怎么好的地方想反馈一下.
1.按ESC键会直接关闭微信窗口.
说明:
在使用中文输入法时,当输入错误的时候,经常需要按ESC删除输入法弹框中的已输入字符,然后重新输入.然而在点击ESC后,聊天窗口也会一同消失.希望能够优化一下,使按esc时,不关闭聊天窗口.

**Comment by Kulbear** [comment]
已经若干重复 issue 关于这个了。请发 issue 之前先检查一下。
