### ISSUE TITLE
打包后，快捷键不能用，菜单栏不显示

### ISSUE THREAD

**Issue by jyanchen** [geeeeeeeeek/electronic-wechat#48]
#### Description
使用`npm start`运行打开，可以显示菜单栏，也可以使用快捷键。
但是，打包后，菜单栏不显示，快捷键也不能用

#### Specifications

- Version of Electron: v0.36.9
- Version of Node.js : v4.2.1
- OS: Linux Mint 17.2 Rafaela
- Architecture: x64

**Comment by geeeeeeeeek** [comment]
Linux下状态栏暂时隐藏了。你说的快捷键是复制粘贴？

**Comment by jyanchen** [comment]
@geeeeeeeeek 代码我自己修改过，打包前是一切正常，打包后就不行了，我指的是菜单栏的所有快捷键

**Comment by geeeeeeeeek** [comment]
打包前你看到的是electron的菜单栏，是否会影响到快捷键我需要再看一下，Ubuntu并不会，这和桌面环境有关

**Comment by jyanchen** [comment]
其实在我系统里，一直都没有显示自定义的菜单，一直都是显示系统默认的菜单。
翻看了[官方文档](http://electron.atom.io/docs/v0.36.8/api/menu/)，快捷键方式写法一共分2种：
````javascript
CmdOrCtrl+M //这种写法适用于我的系统
````
````javascript
Command+M
````
现在，我的快捷键都可以用了。
建议把快捷键方式做兼容。

**Comment by geeeeeeeeek** [comment]
@jyanchen  [b43c562](https://github.com/geeeeeeeeek/electronic-wechat/commit/b43c5626435aaa73b855dc2f7ff8f336d072bd76)修复了多个Linux下的显示问题，应该解决了这个issue。
