### ISSUE TITLE
关于截屏的请教

### ISSUE THREAD

**Issue by lihang1870719** [geeeeeeeeek/electronic-wechat#480]
关于electron的截屏，我的做法是利用desktopCapturer获取源数据，然后通过canvas绘制，但是考虑到截屏后需要全屏，调用electron的api中的窗口对象window.setFullScreen(true)时在mac下会闪屏，类似浏览器最大化、缩小的效果，不知道您有没有相关的优化建议

**Comment by Kulbear** [comment]
我实现过一个和你思路几乎一样的 但是效果太不好了。

**Comment by XanthusL** [comment]
我都是用gnome的screenShot截到剪切板，Ctrl  +  V

**Comment by geeeeeeeeek** [comment]
暂时不考虑做这个。macOS可以用截图软件保存到剪贴板里。

**Comment by Dear-Qiao** [comment]
@lihang1870719 你找到解决方法了么  我也没找到更好的方法

**Comment by lihang1870719** [comment]
@Dear-Qiao mac上你可以试试调用系统命令 `screencapture -w ` 然后把文件读到内存中处理
