### ISSUE TITLE
按esc最小化

### ISSUE THREAD

**Issue by GuihaiHU** [geeeeeeeeek/electronic-wechat#486]
#### Specifications

- Version of Electron (run `$ electron --version`): `v2.0`
- OS: `<deepin 15.4>`
- Stack trace from the error message (if any)

该版本按下esc键后默认最小化，这么设计不合理。因为打字的时候经常需要按esc来取消

**Comment by Kulbear** [comment]
这个Issue已经提了无数次并且已经改了。

**Comment by GuihaiHU** [comment]
我的系统上并没有生效。从深度商店上看，确实是v2.0版本没错

**Comment by Kulbear** [comment]
没有release 可以自己build
