### ISSUE TITLE
Request for Support Matrix update

### ISSUE THREAD

**Issue by Werror** [geeeeeeeeek/electronic-wechat#491]
#### Description
The operation of electronic-wechat have been confirmed on Ubuntu 16.04.1.
I would like to mention that the default `nodejs` package comes with the distro is too old. I would like to add link to official node site to indicate how to install the latest `nodejs` package, https://nodejs.org/en/download/package-manager/ .

**Comment by geeeeeeeeek** [comment]
Sure. You are welcome! I think the edit is open for all community members.
