### ISSUE TITLE
npm start errors

### ISSUE THREAD

**Issue by ifzm** [geeeeeeeeek/electronic-wechat#497]
我使用 npm start script 出现如下错误，关闭错误窗口后，程序可以正常使用
- Electron: `v1.4.15`
- OS: `Ubuntu 16.4 LTS`
 
![2017-05-14 23-44-30](https://cloud.githubusercontent.com/assets/12740295/26060044/780f76ce-39b6-11e7-8381-51fd84223b64.png)

**Comment by Rocket1184** [comment]
跟 #359 一样的，我在 #494 修复了，不过没合并过来

**Comment by Rocket1184** [comment]
如果你要直接使用的话，建议不要用 `npm start` ，可以用 `npm run build:linux` 打包为二进制包，然后把 `dist` 目录下的东西复制到别的地方用

**Comment by ifzm** [comment]
照你的方法试了，`npm run build:linux64`，但是运行时卡主
![2017-05-15 21-52-06](https://cloud.githubusercontent.com/assets/12740295/26061239/ea46622c-39b9-11e7-9312-ba04cc099f79.png)

**Comment by Rocket1184** [comment]
无法复现...
能不能在终端里面运行看一下有什么输出？

**Comment by ifzm** [comment]
run build 是正常的，但是运行`electronic-wechat`无反应
![2017-05-15 23-21-00](https://cloud.githubusercontent.com/assets/12740295/26065047/5a17f95c-39c5-11e7-8e70-2b0523e82dea.png)

**Comment by Rocket1184** [comment]
Ubuntu 里面要自己创建 `.desktop` 文件才能指定图标。详细可以看 https://github.com/geeeeeeeeek/electronic-wechat/issues/447#issuecomment-293555351

**Comment by ifzm** [comment]
thanks ) :+1:
