### ISSUE TITLE
点击关闭按钮后再次打开窗口需要重新登录

### ISSUE THREAD

**Issue by DIYgod** [geeeeeeeeek/electronic-wechat#5]
系统：OS X 10.11.3

具体步骤：
1. 点击关闭按钮
2. 点击 Dock 上的 Electronic WeChat 图标
3. 窗口再次打开，但是微信已经退出登录，需要重新扫码登录

**Comment by geeeeeeeeek** [comment]
@DIYgod 你Quit到再次打开之间隔了多久？

**Comment by DIYgod** [comment]
@geeeeeeeeek 马上打开也会退出登录

**Comment by geeeeeeeeek** [comment]
我这里无法复现。微信隔一段时间session过期确实会要求重新登录，但隔个几分钟一般不会。

**Comment by viko16** [comment]
+1，不管是否打包后的都是这样

**Comment by arrowrowe** [comment]
Ubuntu 14.04.1 没有发现问题.

**Comment by DIYgod** [comment]
补充：我这里未打包的客户端点击关闭按钮程序就退出了，打包好的客户端点击关闭按钮程序不会退出但是会退出登录。

**Comment by wenLiangcan** [comment]
我在 Linux 下使用独立安装的 electron 直接运行源码，关闭后立即在打开就会提示需要登录。

**Comment by maemual** [comment]
Mac OS X 10.11.3 
打包客户端
点击关闭按钮后，再立即打开，倒没有退出重新登录，而是经历了白屏、消息列表重新加载的一个过程。体验和重新登录一样，只是不需要我自己扫码。

**Comment by geeeeeeeeek** [comment]
@maemual 因为这是Web app，页面需要重新加载

**Comment by maemual** [comment]
@geeeeeeeeek 是这样啊。那这样的体验就很糟糕了，经常重新加载消息列表就加载的不完全。不如别人用 Fluid 封装的 Web APP 好用啊。

**Comment by geeeeeeeeek** [comment]
@maemual 是这样，我现在点击关闭按钮的逻辑是quit app，我试着修改一下，应该就不会重新加载了。

**Comment by ipfans** [comment]
@geeeeeeeeek 还是希望接管关闭窗口事件，只是隐藏窗口，禁用消息提示和声音，而不是真正关闭窗口或者退出程序。

用快捷键习惯 command＋W，过段时间再看就需要登陆了。。。

**Comment by yannisxu** [comment]
Mac OS X 关闭图片预览窗口，程序也会关闭

**Comment by geeeeeeeeek** [comment]
@yannisxu 无法复现

**Comment by ipfans** [comment]
@geeeeeeeeek 应该是⌘+W关闭的会有这种情况，esc关闭或者手动点击不会

**Comment by iamcc** [comment]
已经pr

**Comment by geeeeeeeeek** [comment]
Fixed in #50. 但是⌘+Q目前无法quit应用，需要修改。

**Comment by viko16** [comment]
@geeeeeeeeek http://stackoverflow.com/a/32950922  也许能参考？
