### ISSUE TITLE
Ubuntu1704？

### ISSUE THREAD

**Issue by OliverDH** [geeeeeeeeek/electronic-wechat#500]
Failed at the electronic-wechat@2.0.0 start script 'electron src/main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electronic-wechat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron src/main.js

**Comment by eumji025** [comment]
应该是npm的问题

**Comment by geeeeeeeeek** [comment]
npm 安装问题，自行解决。
