### ISSUE TITLE
mac上有BUG，撤回消息后被撤回那条还在界面显示

### ISSUE THREAD

**Issue by dxz0501** [geeeeeeeeek/electronic-wechat#501]
#### Description

微信群内好友发消息，好友撤回后被撤回的消息仍在消息窗内显示

#### Specifications

- Version of Electron (run `$ electron --version`): `v1.4.0`
- OS: `MacOS 10.12.4`
- Stack trace from the error message (if any)

```
<None>
```

**Comment by Rocket1184** [comment]
这是防撤回的 feature ...
看 README [这里第二条](https://github.com/geeeeeeeeek/electronic-wechat/blob/master/README_zh.md#应用特性-更新日志)

**Comment by geeeeeeeeek** [comment]
以后会加个开关。
