### ISSUE TITLE
大大，electron可以开发QQ吗？

### ISSUE THREAD

**Issue by tomoya92** [geeeeeeeeek/electronic-wechat#503]
linux 上没有qq。。造成了很多的不便

在github上搜了一下，有个https://github.com/arthurkiller/electronic-QQ

打包好了，运行，看上去就是在w.qq.com外面包了个窗口

没弄过qq，wechat的协议 ，所以先来问问大大可行不？谢谢了

**Comment by konvict** [comment]
http://phpcj.org/wineqq/ 
wineqq 大部分系统都能用。安装也简单

**Comment by tomoya92** [comment]
@konvict 不想用这个 :joy:

**Comment by Rocket1184** [comment]
趁早放弃吧，除非你想自己抓 QQ 客户端的网络请求，然后自己用 socket 实现。现在 Web QQ 基本上是残废的，除了收发文字消息以外基本没有什么功能，甚至连发图都不行。
但，开发还是可以开发的，只是功能非常有限，没什么用处就是了。

**Comment by tomoya92** [comment]
这个。。

linux上用qq真麻烦呀。。算了不折腾了

**Comment by kendling** [comment]
我现在是 wine+最新版QQ 用起来没太大问题。

**Comment by tomoya92** [comment]
@kendling 你是直接装的wine, 然后下载qq.exe 也是直接装的吗？没有装其它的东西就可以用？
