### ISSUE TITLE
如何禁用electronic-wechat内置chromium的硬件加速

### ISSUE THREAD

**Issue by UKeyboard** [geeeeeeeeek/electronic-wechat#504]
Electronic wechat刚开始使用正常，后来偶尔出现应用界面局部花屏的问题，其他应用正常。
这个问题之前chromium浏览器也出现过，后来通过禁用硬件加速解决了。
![image](https://cloud.githubusercontent.com/assets/8756402/26478096/73903982-41fc-11e7-8e93-3508f6db9a8d.png)

Electronic WeChat好像内建了chromium吧，那如何禁用硬件加速来解决花屏问题呢？
我的本本比较老，集显性能差

**Comment by Rocket1184** [comment]
在 https://github.com/geeeeeeeeek/electronic-wechat/blob/master/src/main.js#L15 之前，加上一句 
```js
app.disableHardwareAcceleration()
```
然后重新打包运行，似乎就可以了…
或者可以自己解包 app.asar ，把里面 src/main.js 代码改掉，然后重新打包成 asar

Electron 文档参见
https://electron.atom.io/docs/api/app/#appdisablehardwareacceleration

asar 文档参见
https://github.com/electron/asar
