### ISSUE TITLE
这个安全吗？

### ISSUE THREAD

**Issue by AllenVork** [geeeeeeeeek/electronic-wechat#506]
聊天记录等会不会泄漏？

**Comment by geeeeeeeeek** [comment]
？？？

技术上当然可以看到你的聊天记录了，至于我有没有这么做可以看代码（微笑

**Comment by AllenVork** [comment]
哈哈

发自我的 iPhone

> 在 2017年5月27日，上午11:08，Zhongyi Tong <notifications@github.com> 写道：
> 
> ？？？ 
> 
> 技术上当然可以看到你的聊天记录了，至于我有没有这么做可以看代码（微笑 
>
