### ISSUE TITLE
支持视频聊天吗？

### ISSUE THREAD

**Issue by JUSDJTIN** [geeeeeeeeek/electronic-wechat#510]
#### Description

First of all, thanks for your attention to open an issue for this project.
Please notice that if you are requesting a **feature**, then you should give a **brief description** of your request.
If you are reporting a **bug**, please **follow the template** below.
A bug report **without detailed information** required will have a **very low priority** and even be **ignored** (closed directly)!

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- OS: `<OS>`
- Stack trace from the error message (if any)

```
<Stack trace here>
```

**Comment by geeeeeeeeek** [comment]
@JUSDJTIN 不支持
