### ISSUE TITLE
Linux Manjaro KDE5 字体显示异常

### ISSUE THREAD

**Issue by juanxincai0526** [geeeeeeeeek/electronic-wechat#517]
### Description
更换过一次字体后就变成了这样：
![screenshot_20170616_230948](https://user-images.githubusercontent.com/16558006/27232535-0862af4c-527c-11e7-83f3-352ed617a7d2.png)
换回原来的字体后问题依然存在。
### Specifications
-  OS：Manjaro 17.0.1
- Version of Electron：`v1.4.6`
- Desktop：KDE5

**Comment by Rocket1184** [comment]
看一下自己的 fontconfig
https://wiki.archlinux.org/index.php/Font_configuration

大概是默认 fallback 字体改坏了

**Comment by geeeeeeeeek** [comment]
这个不是 app 的问题吧。没有改过 Web WeChat 的字体行为。

**Comment by juanxincai0526** [comment]
安装wps的字体后会出现这种情况（archlinuxcn/ttf-wps-fonts）

**Comment by Rocket1184** [comment]
@juanxincai0526 我也装了这个包，并不会这样呀

还是看一下自己的字体配置吧
