### ISSUE TITLE
Ubuntu 17.04 无后台图标

### ISSUE THREAD

**Issue by porson** [geeeeeeeeek/electronic-wechat#520]
- 2.0包在ubuntu17.04 无状态栏图标

**Comment by YanJa** [comment]
我的16.04也没有状态栏图标了

**Comment by niyanchun** [comment]
我的16.04也木有

**Comment by Rocket1184** [comment]
请尝试安装 `libappindicator1` 或 `libappindicator3-1`

**Comment by niyanchun** [comment]
@Rocket1184 我装了`python-appindicator`之后好了

**Comment by Rocket1184** [comment]
@niyanchun 

那是因为 [`python-appindicator`](https://packages.debian.org/stretch/python-appindicator) 依赖 `libappindicator1` （

**Comment by porson** [comment]
谢谢

**Comment by whirlwind110** [comment]
17.04下还有问题的。
https://github.com/geeeeeeeeek/electronic-wechat/issues/169
感谢 @ferstar


下面是17.04下解决方法。
Run the application with env XDG_CURRENT_DESKTOP=Unity to get the AppIndicator working.

`[Desktop Entry]
Version=2.0
Name=WeChat
Comment=WeChat
Keywords=wechat;chat;talk;im;message;
Exec=env XDG_CURRENT_DESKTOP=Unity /home/shawn/Tools/electronic-wechat-linux-x64/electronic-wechat
Icon=/home/shawn/Tools/electronic-wechat-linux-x64/icon/desktop_icon.png
Categories=InstantMessaging;Network;
Terminal=false
StartupNotify=true
Type=Application`

https://askubuntu.com/questions/905858/appindicators-not-working-for-electron-applications-skype-for-linux-discord-et

@Rocket1184
