### ISSUE TITLE
请问如何将界面由英文修改为中文？

### ISSUE THREAD

**Issue by Zyx-A** [geeeeeeeeek/electronic-wechat#521]
请问如何将V2.0界面由英文修改为中文？
我看到locales目录下有一个zh-CN.pak，但不知道如何指定。
系统为CentOS 7.3
我是在这里下载的：https://github.com/geeeeeeeeek/electronic-wechat/releases/download/V2.0/linux-x64.tar.gz
解压后，直接运行electronic-wechat

**Comment by Roller44** [comment]
在 reference 窗口里就能修改，你可以尝试点击 Alt 键以显示。
