### ISSUE TITLE
为啥没有windows版本

### ISSUE THREAD

**Issue by mosesyou** [geeeeeeeeek/electronic-wechat#544]
有准备开发windows版本么，我有这个意向

**Comment by sjtutyx** [comment]
同问 我觉得linux下一般不会用微信。。

**Comment by Roller44** [comment]
这本来就是为了解决 Linux 和 Mac 下无法使用微信而生的，Windows 下有原生的客户端为什么不用呢？On Jan 14, 2018 14:18, Yuxin <notifications@github.com> wrote:同问 我觉得linux下一般不会用微信。。
