### ISSUE TITLE
gnome图标显示不对

### ISSUE THREAD

**Issue by jilen** [geeeeeeeeek/electronic-wechat#55]
![screenshot from 2016-03-03 19-30-53](https://cloud.githubusercontent.com/assets/546573/13493058/a4d090ce-e176-11e5-87fa-1f7d45903130.png)

**Comment by yzsatgithub** [comment]
@jilen  我是在`/usr/share/applications/`目录下创建创建一个`wechat.desktop`文件．里边的内容如下：
![wechatdesktopss](https://cloud.githubusercontent.com/assets/10882352/13493419/f34caf92-e178-11e5-9d6b-1fdb2c904e6c.png)
你把里边的内容根据自己的需要修改以下就行了．

**Comment by jilen** [comment]
@yzsatgithub  这样做只在App 列表有用。一旦运行，就变成我所说的样子

**Comment by GodJobs** [comment]
我是这样弄的：

1.  首先去除文件路径中的空格，使文件路径中不包含空格。
2.  然后执行目录下的可执行文件（文件名也没有包含空格），运行之后，右键点击Launcher上的图标，最开始就是你看到的问号。
这样执行之后，在~/.local/share/applications/目录下会生成对应的.desktop文件。
大体如下，然后我自己手动修改了Icon，然后注销，再进来图标更新了，也能从Launcher点击图标启动了，就搞定了。

```
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
Name=Electronic WeChat
Icon=/home/lizhi/Pictures/icons/wechat.png
Path=/home/lizhi/Tools/Electronic-WeChat
Exec=/home/lizhi/Tools/Electronic-WeChat/ElectronicWeChat
StartupNotify=false
StartupWMClass=electronic-wechat
OnlyShowIn=Unity;
X-UnityGenerated=true
```

我的操作系统是**Ubuntu14.04**


![image](https://cloud.githubusercontent.com/assets/3899178/13516294/cf08d9e6-e1f3-11e5-8250-8d1180194565.png)

你可以看看上面的效果

**Comment by izuolan** [comment]
@GodJobs 这个Exec=/home/马赛克/Tools/Electronic-WeChat/ElectronicWeChat里面是什么？默认是npm start启动的诶

**Comment by GodJobs** [comment]
@izuolan 你们都是下载源码自己跑的啊？我是下载的编译好的Release版本，没有自己编译，我用的是V1.0.1里面的linux-x64.tar.gz

**Comment by jilen** [comment]
@GodJobs 所以说Gnome和Unity是不一样的

**Comment by GodJobs** [comment]
@jilen 嗯，不错

**Comment by yzsatgithub** [comment]
@jilen  我的系统是**12.04LTS**, 按照上边说的简单写好.desktop文件后（主要是Icon和Exec），在终端运行`./Eletronic\ Wechat`后将图标锁定在启动器上就可以了．　
![qq 20160304140814](https://cloud.githubusercontent.com/assets/10882352/13519401/96123a0a-e212-11e5-9559-2225446667a0.png)
你没有`StartupWMClass=electronic-wechat`这一句就不行吗？你的**系统版本**是啥?

**Comment by jilen** [comment]
@yzsatgithub Archlinux Gnome 3.18. 跟Ubuntu Unitfy不太一样

**Comment by yzsatgithub** [comment]
@jilen 搜噶．看起来很炫酷～

**Comment by xxxifan** [comment]
求楼主图标包=v=

**Comment by geeeeeeeeek** [comment]
@xxxifan 新发布的版本已经修正这个问题了

**Comment by jilen** [comment]
@xxxifan https://github.com/numixproject/numix-icon-theme-circle
