### ISSUE TITLE
Ubuntu上docker的下拉菜单为空

### ISSUE THREAD

**Issue by yzsatgithub** [geeeeeeeeek/electronic-wechat#56]
#### Description
系统是Ubuntu12.04．点击右上角的docker后，只会出现一个内容为空的菜单项，点击之后可以打开微信窗口．设计的时候应该估计至少有打开和关闭两个菜单项．　我这是特殊情况吗？
由于鼠标焦点在docker上时，各种截图方法都不能用，这里就不上图了．
@geeeeeeeeek 

#### Specifications

- Version of Electron (run `$ electron --version`): unknown
- Version of Node.js (run `$ node --version`): `v0.10.37`
- OS: `Ubuntu 12.04 LTS`
- Architecture `x86_64`
- Stack trace from the error message (if any)

**Comment by geeeeeeeeek** [comment]
![image](https://cloud.githubusercontent.com/assets/7262715/13519872/757ca998-e216-11e5-947f-d48516b223f5.png)

![image](https://cloud.githubusercontent.com/assets/7262715/13519878/7d6cfcb6-e216-11e5-9adf-fd1b161cacc1.png)

OSX下是这样的，Ubuntu你截个图呗，理解不能。

**Comment by gzzhanghao** [comment]
@geeeeeeeeek 

![image](https://cloud.githubusercontent.com/assets/5051221/13525920/61ffe88e-e23f-11e5-8fee-4508b712f618.png)

点击空白的菜单项能打开browserWindow，给Tray设置一个菜单能解决这个问题。

**Comment by yzsatgithub** [comment]
@geeeeeeeeek 对，就像@gzzhanghao的图那样．我这边截不了图，不知为何．

**Comment by geeeeeeeeek** [comment]
明白了

**Comment by geeeeeeeeek** [comment]
@gzzhanghao @yzsatgithub commit [b43c562](https://github.com/geeeeeeeeek/electronic-wechat/commit/b43c5626435aaa73b855dc2f7ff8f336d072bd76)在Linux下增加了两个菜单项Show和Quit，应该解决了这个issue。
