### ISSUE TITLE
ArchLinux打开报错A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by noahziheng** [geeeeeeeeek/electronic-wechat#57]
打开提示：
Uncaught Exception:
TypeError: Error processing argument -1.
    at TypeError (native)
    at createTray (/usr/share/electronic-wechat/src/main.js:124:13)
    at EventEmitter.createWindow (/usr/share/electronic-wechat/src/main.js:94:3)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)

系统ArchLinux衍生版Manjaro，已滚至最新
安装自AUR electronic-wechat-git

**Comment by imlonghao** [comment]
相同问题
Archlinux 滚到最新，AUR 安装的 `electronic-wechat-git`

```
imlonghao@imlonghao ~$ electron --version                                      
v0.36.7
imlonghao@imlonghao ~$ node --version                                          
v5.7.1
imlonghao@imlonghao ~$ npm --version                                           
3.7.5
```

**Comment by wenLiangcan** [comment]
@noahziheng @imlonghao 很抱歉，我是打包者。这是由于我打包的问题，现在最新的 PKGBUILD 已经修复了。

**Comment by geeeeeeeeek** [comment]
@wenLiangcan 没有明白你的意思，是这个项目的问题吗

**Comment by wenLiangcan** [comment]
@geeeeeeeeek 不是。通过打包，可以让下游的 Linux 用户自动化地安装卸载某个软件。因为最近 electronic-wechat 加入了托盘图标的功能，我之前的旧的打包脚本没有包含那个图标的图片，导致程序启动时会出错。

如果上面两位使用新的打包脚本后没有问题（我不能百分百保证是这个问题，所以具体要看他们的反馈）应该就可以关闭这个 issue 了。

**Comment by geeeeeeeeek** [comment]
@wenLiangcan `https://aur.archlinux.org/packages/electronic-wechat-git/`我看到了

**Comment by imlonghao** [comment]
@wenLiangcan `yaourt -Syua` 之后更新了一下，已经没问题了。
(昨晚用邮件回复这个 issue 似乎没有成功...
