### ISSUE TITLE
WeChat-darwin-x64 Mac下手机扫描后卡在登录界面

### ISSUE THREAD

**Issue by dongz1007** [geeeeeeeeek/electronic-wechat#58]
First, make sure your issue is strictly related to the ***Electronic WeChat*** project. If it's a question or feature request, you can remove the template below.

#### Description

Pack成APP后，WeChat手机端扫描Mac端的二维码，手机端确认，Mac端没有反应，进入不了聊天页面。请看下图：
![screen shot 2016-03-03 at 3 32 48 pm](https://cloud.githubusercontent.com/assets/7764245/13508783/7342d5c8-e156-11e5-95bb-d29879865cce.png)

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.36.9`
- Version of Node.js (run `$ node --version`): `v4.3.2`
- OS: `Mac OSX 10.11.3`
- Architecture `x64`

**Comment by geeeeeeeeek** [comment]
你是通过npm安装的吗？master上的代码应该已经修复了这个问题。

**Comment by dongz1007** [comment]
我是通过npm安装的，我刚刚又尝试了一次，还是手机端点登录后Mac客户端登录不进去。能否给点建议我应该干点啥？

**Comment by iven** [comment]
Arch Linux 上也是同样问题，同事的 OS X 也是这样。通过 npm 安装的，commit 是 19896def02497b90b6ac2b7f477e393d2e31c6cf。

Specifications

* Version of Electron (run `$ electron --version`): `v0.36.7`
* Version of Node.js (run `$ node --version`): `v5.7.1`
* OS: Arch Linux
* Architecture: x64

**Comment by geeeeeeeeek** [comment]
只在极少数情况下遇到无法跳转的情况，需要更多信息。其他用户如果复现欢迎调试并跟进这个issue，一段时间后没有其他用户复现issue将被关闭。
