### ISSUE TITLE
这个mac版的和官方的客户端有什么区别呢

### ISSUE THREAD

**Issue by yswheye** [geeeeeeeeek/electronic-wechat#59]
First, make sure your issue is strictly related to the ***Electronic WeChat*** project. If it's a question or feature request, you can remove the template below.

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- Version of Node.js (run `$ node --version`): `v0.0.0`
- OS: `<OS>`
- Architecture `<ARCH>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by geeeeeeeeek** [comment]
Electron封装的Web WeChat. 详细区别请见README.
