### ISSUE TITLE
快捷键Ctrl+w的问题

### ISSUE THREAD

**Issue by czzhengkw** [geeeeeeeeek/electronic-wechat#60]
平时习惯了Ctrl+w隐藏窗口，让程序在后台执行，但是在Electronic-wechat上这个操作会导致下次打开的时候又需要重新扫描登录，希望这点能改进一下。

谢谢

**Comment by bazingaterry** [comment]
我也有这个需求，希望作者能加上这个功能！

谢谢！

**Comment by xuhaoyang** [comment]
@czzhengkw @bazingaterry 21小时前就提交 fix=。=，你们自己查下

**Comment by geeeeeeeeek** [comment]
Duplicate of #5.
