### ISSUE TITLE
打开 electronic-wechat 自动切换聊天对象

### ISSUE THREAD

**Issue by MoSunDay** [geeeeeeeeek/electronic-wechat#623]
### Description
当我点开 ` electronic-wechat` 与列表中第一个好友聊天时, 聊天窗可能会跳到第二个好友, 手快的话可能会把本来发给第一个好友的消息错发给第二个好友....

### Specifications
Version of Electron (run $ electron --version):  `release 2.0`
OS: Xubuntu

-  Xubuntu `16.04` LTS
- `4.13.0-32-generic`
- `x86_64`

Stack trace from the error message ( Null )

**Comment by wangleeyom** [comment]
我也有这个问题，请问最终是怎么解决的呢？
