### ISSUE TITLE
nam install fail

### ISSUE THREAD

**Issue by xincc** [geeeeeeeeek/electronic-wechat#63]
First, make sure your issue is strictly related to the ***Electronic WeChat*** project. If it's a question or feature request, you can remove the template below.

#### Description

$ npm install && npm start
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
 
> electron-prebuilt@0.36.9 postinstall /Users/baidu/Documents/MyProj/electronic-wechat/node_modules/electron-prebuilt
> node install.js

Downloading electron-v0.36.9-darwin-x64.zip
Error: connect ETIMEDOUT 54.231.2.225:443

/Users/baidu/Documents/MyProj/electronic-wechat/node_modules/electron-prebuilt/install.js:22
  throw err
  ^
Error: connect ETIMEDOUT 54.231.2.225:443
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/4.2.1/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@0.36.9 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-prebuilt@0.36.9 postinstall script 'node install.js'.
npm ERR! This is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/baidu/Documents/MyProj/electronic-wechat/npm-debug.log

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- Version of Node.js (run `$ node --version`): `v0.0.0`
- OS: `<OS>`
- Architecture `<ARCH>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by geeeeeeeeek** [comment]
`This is most likely a problem with the electron-prebuilt package.`

Clean your cache and try again.

**Comment by linux0ne** [comment]
@geeeeeeeeek 
Clean your cache and try again.

怎么清除？？
