### ISSUE TITLE
Could not close video if it opened

### ISSUE THREAD

**Issue by valord577** [geeeeeeeeek/electronic-wechat#638]
- Version: `v2.0`
- OS: `ubuntu 16.04 LTS`

点开小视频后无法关闭它

**Comment by Roller44** [comment]
将窗口拽大些，就能看见关闭按钮。On Apr 16, 2018 14:37, valord577 <notifications@github.com> wrote:Version: v2.0OS: ubuntu 16.04 LTS
点开小视频后无法关闭它

**Comment by valord577** [comment]
Thanks
