### ISSUE TITLE
Ubuntu 18.04 LTS使用lectronic-wechat状态栏无法显示问题

### ISSUE THREAD

**Issue by vic-feng** [geeeeeeeeek/electronic-wechat#652]
Ubuntu 18.04 LTS使用lectronic-wechat存在问题，就是状态栏无法显示。
Ubuntu 16.04.4 LTS 中还存在一个问题，就是聊天记录无法使用右键，但可以使用Ctrl+C。
希望作者能修复这些问题，谢谢

**Comment by kooritea** [comment]
可以试一下我的分支嘛？(←疯狂安利自己的分支)
针对ubuntu1804修bug的
托盘图标是有了，右键复制的问题还没解决
https://github.com/kooritea/electronic-wechat/releases

**Comment by vic-feng** [comment]
非常感谢这么短的时间内解决了问题。
有问题继续反馈下：
1.点击了窗口的关闭按钮，想要继续使用的时候还得重新启动程序才行；希望在点击了窗口的关闭按钮之后转入后台运行，想要再次使用的时候直通过状态栏右键或直接点击呼出窗口。
