### ISSUE TITLE
聊天面板的列表滑动时卡顿

### ISSUE THREAD

**Issue by leyayun** [geeeeeeeeek/electronic-wechat#66]
####问题描述
聊天面板下的那个list，上下滑动卡成狗

####环境
- OS: `osx 10.11.2`

**Comment by 0x5e** [comment]
+1 好像是个别消息特别卡，滑过那个消息就正常了
osx 10.11.3

**Comment by geeeeeeeeek** [comment]
确实存在滚动性能问题，尝试修复。
![image](https://cloud.githubusercontent.com/assets/7262715/13532126/c95f297a-e264-11e5-8047-a83969f8b19c.png)

**Comment by geeeeeeeeek** [comment]
检测未读消息计数使用的DOM SubTree Modified导致，修改实现方式为1.5秒轮询一次，解决性能问题。

**Comment by leyayun** [comment]
@geeeeeeeeek 刚刚试了下，性能的确得到了显著提升。手动给大神点个赞.
