### ISSUE TITLE
Receiving support? 

### ISSUE THREAD

**Issue by Francolpm** [geeeeeeeeek/electronic-wechat#67]
Hi there! This isn't a issue but I didn't know where to ask!
Are you accepting donations or supports? Because may you get some extra support for wechat, but there is no donate button o something like that.
I don't trying to spam you, but I want to invite you to beerpay.io, a simple platform to monetize open source projects, like electronic-wechat. 
I know that the open source is free, but it's okay if someone want to contribute in other way.

Thanks for this work!

**Comment by geeeeeeeeek** [comment]
@Francolpm I'm sure you wouldn't have Alipay and WeChat pay integrated. So your service does not really help. -.-
