### ISSUE TITLE
点击右上角的X按钮，并不是真正的退出，可以收到信息，但是唤不醒界面

### ISSUE THREAD

**Issue by HarryHq** [geeeeeeeeek/electronic-wechat#687]
#### 不小心按了X按键，就直接关闭了并不是真正的退出，可以收到信息，但是唤不醒界面

* 问题一
![image](https://user-images.githubusercontent.com/33572465/47725504-a5841480-dc93-11e8-9b13-c1d213a012e6.png)
是不是应该给一个友好提示，在点到这个按钮之后，

* 问题二
当不小心点了上面的X按键之后，wechat并没有真正的退出，但是客户端界面消失了，只能通过后台杀死进程，然后重新启动，这个是不是应该在想真正退出的时候边后台进程也一同杀死了呢

#### Specifications

- Version of Electron (run `$ electron --version`): `v2.0`
- OS: `Ubuntu 18.04`
- Stack trace from the error message (if any)

```
<Stack trace here>
```

**Comment by QingNeng** [comment]
同样的问题

**Comment by kooritea** [comment]
因为右上角的关闭按钮是缩小到托盘
但是因为electron版本和ubuntu gnome的问题没有正常显示托盘图标

这个分支可以解决问题
https://github.com/kooritea/electronic-wechat

**Comment by fenghoer** [comment]
附议，聊天记录总是被清空

**Comment by HarryHq** [comment]
> 因为右上角的关闭按钮是缩小到托盘
> 但是因为electron版本和ubuntu gnome的问题没有正常显示托盘图标
> 
> 这个分支可以解决问题
> https://github.com/kooritea/electronic-wechat

这个分支优化的不错，解决了很多问题了
