### ISSUE TITLE
启动超慢

### ISSUE THREAD

**Issue by Unknwon** [geeeeeeeeek/electronic-wechat#69]
#### Description

Mac OS X 10.11.3 启动应用后要 1 分钟界面才有反应，有时直接反应需要重启多次。然后二维码要 2-3 分钟才能刷出来，坐标美帝，不知道有没有影响？

直接从  https://github.com/geeeeeeeeek/electronic-wechat/releases/tag/v1.0.1 下载的版本。

**Comment by geeeeeeeeek** [comment]
建议对比一下wx.qq. com网页版微信，我ssh到美国加载也会很慢。

国内一般秒开。

**Comment by Unknwon** [comment]
网页微信秒开。。

**Comment by geeeeeeeeek** [comment]
@Unknwon 可能是因为缓存原因，我研究下。
