### ISSUE TITLE
ArchLinux Gnome3 环境无法正常使用

### ISSUE THREAD

**Issue by noahziheng** [geeeeeeeeek/electronic-wechat#71]
扫码后卡在”正在获取最近聊天“
Gnome3托盘只能双击打开窗口，无法用于彻底退出
综上导致无法正常使用且无法退出，只能kill
环境：Archlinux衍生版Manjaro 15.12 +Gnome3

**Comment by geeeeeeeeek** [comment]
@noahziheng [b43c562](https://github.com/geeeeeeeeek/electronic-wechat/commit/b43c5626435aaa73b855dc2f7ff8f336d072bd76)增加了Linux的托盘菜单，提供了Quit选项，应该解决了这个issue。
