### ISSUE TITLE
该程序是nodejs 程序吗

### ISSUE THREAD

**Issue by tianshaokai** [geeeeeeeeek/electronic-wechat#73]
今天把程序下载下来安装到了ubuntu 非常不错，哈哈就是有个小问题，在ubuntu里打开聊天记录的时候，不能显示到底，最后一条消息总显示一半，向下滑动鼠标时聊天页面里面就闪

**Comment by geeeeeeeeek** [comment]
electron显然是个node程序。那个问题我也注意到了，应该是表情注入时引入的一个bug，寻找fix中。

**Comment by tianshaokai** [comment]
恩恩，文字也是不显示最后一条，倒数第二条聊天信息显示一半，ubuntu 里没法截图，只能用文字描述了

**Comment by tianshaokai** [comment]
要是能加入几个常用的快捷键就好了，比如类似qq的截图方式可以 截取想截取的地方
