### ISSUE TITLE
目前校园网封锁严重，挂VPN仍然无法下载

### ISSUE THREAD

**Issue by Carter-Pro** [geeeeeeeeek/electronic-wechat#74]
目前校园网封锁严重，挂VPN仍然无法下载完整APP，请求可用下载链接如百度云等

**Comment by Xuanwo** [comment]
你可以尝试本地编译，下载不了只是因为github用的是S3

**Comment by geeeeeeeeek** [comment]
对的，因为GitHub用的AWS。release是CI自动发布的，不知道有没有好用的Mac应用托管平台。
