### ISSUE TITLE
Unable to log in if client left opened for too long

### ISSUE THREAD

**Issue by maddie** [geeeeeeeeek/electronic-wechat#75]
#### Description
Using version: git HEAD
After leaving the client open overnight, I came back and try to scan the QR code.
No response on the Electronic WeChat side, and an error message is shown: "暂时无法登录,请重新尝试登录" on the WeChat mobile application.
A toast message (I'm using Android) showing "查找失败(4,-1)" after scanning the QR code.
After quitting the client completely (from Dock, right click -> Quit. `Cmd + Q` seems to be overridden by the application as minimize) and re-open it, then it works right away.

Could it be the QR code being shown was already expired and not being refreshed?

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.36.9`
- Version of Node.js (run `$ node --version`): `v5.7.0`
- OS: `OS X El Capitan 10.11.3`
- Architecture `amd64`
- Stack trace from the error message (if any)

``` 
n/a
```

**Comment by maddie** [comment]
Sorry, I just noticed there a commit 28e114a looks like a fix to this. Will test and report. Thanks!

**Comment by geeeeeeeeek** [comment]
Session certainly will timeout in a while. You can refresh the app by `Cmd+R` and reload the QR code.

**Comment by maddie** [comment]
Got it. Thanks!
