### ISSUE TITLE
视频不能播放播放

### ISSUE THREAD

**Issue by cielpy** [geeeeeeeeek/electronic-wechat#79]
First, make sure your issue is strictly related to the ***Electronic WeChat*** project. If it's a question or feature request, you can remove the template below.

#### Description

![image](https://cloud.githubusercontent.com/assets/3138493/13563257/3a67e84c-e47b-11e5-8fae-9f65446b3301.png)

点击播放后出现以上界面，没有开始播放

#### Specifications

- Version of Electron (run `$ electron --version`): `未知`
WeChat 是用 https://github.com/geeeeeeeeek/electronic-wechat/commit/b43c5626435aaa73b855dc2f7ff8f336d072bd76 编译的版本
- Version of Node.js (run `$ node --version`): `v5.7.1`
- OS: `OS X`
- Architecture `64`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by geeeeeeeeek** [comment]
无法复现。
