### ISSUE TITLE
连续收到多个贴图表情时，滚动有问题

### ISSUE THREAD

**Issue by TooBug** [geeeeeeeeek/electronic-wechat#80]
![bug](https://cloud.githubusercontent.com/assets/1243593/13566836/9639f7ca-e492-11e5-9ae5-43a95c844dbc.gif)

#### Description

如题，连续收到多个贴图表情时，无法滚动到最下面，见图片。

#### Specifications

下载的v1.0.1二进制包。

- OS: `Mac OS X 10.11.3`
- Architecture `Intel Core i5`

**Comment by yzsatgithub** [comment]
got the same  problem even there isn't much emoticons.

**Comment by viko16** [comment]
+1

**Comment by luoyhang003** [comment]
+1

**Comment by geeeeeeeeek** [comment]
@all `release/1.1`中已经修复了这个问题。修改了贴纸大小注入的实现方式，修复了滚动时内容闪烁不跟手的bug，修复了切换聊天后滚动条有时不在最底部的bug。

等这两天把bug都修了之后并入`master`，然后发一个release。
