### ISSUE TITLE
npm rebuild , npm run build : different electron version.........

### ISSUE THREAD

**Issue by mmfei** [geeeeeeeeek/electronic-wechat#81]
First, make sure your issue is strictly related to the ***Electronic WeChat*** project. If it's a question or feature request, you can remove the template below.

#### Description

npm rebuild:(master)
Downloading electron-v0.36.10-darwin-x64.zip

npm run build:osx
Downloading electron-v0.36.9-darwin-x64.zip  (electron version)

...........

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- Version of Node.js (run `$ node --version`): `v0.0.0`
- OS: `<OS>` osx
- Architecture `<ARCH>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by geeeeeeeeek** [comment]
无法复现…使用npm install吧
