### ISSUE TITLE
加上 Electron 镜像

### ISSUE THREAD

**Issue by chuyik** [geeeeeeeeek/electronic-wechat#82]
#### Description
`electron-prebuilt`需要下载 Electron.app，但国内 下载  速度太慢了。
建议使用淘宝镜像，在 README.md 中加上：
```bash
export ELECTRON_MIRROR=https://npm.taobao.org/mirrors/electron/
```

**Comment by geeeeeeeeek** [comment]
Release分支README加上了cnpm的广告。
