### ISSUE TITLE
在输入框粘贴文本后，文本上下会有好多空行

### ISSUE THREAD

**Issue by change2hao** [geeeeeeeeek/electronic-wechat#86]
First, make sure your issue is strictly related to the ***Electronic WeChat*** project. If it's a question or feature request, you can remove the template below.

#### Description

在聊天输入框里粘贴文本后，文本的上下会自动产生好多空行。

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.36.11`
- Version of Node.js (run `$ node --version`): `v5.1.0`
- OS: `<OSX EI Capitan>`
- Architecture `<ARCH>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by bazingaterry** [comment]
我也遇到这个问题，也是 OS X El Capitan。

**Comment by geeeeeeeeek** [comment]
是否是富文本，本身就包含多个空行。你尝试`Cmd + Shift + V`粘贴还会复现吗？

**Comment by bazingaterry** [comment]
@geeeeeeeeek 是富文本。例如在本页面，随便复制一个字粘贴，就会出现这个现象，而纯文本则不会。另外不知道是否个人问题，在这个微信里无法进行 `Cmd + Shift + V` 粘贴。

**Comment by geeeeeeeeek** [comment]
@bazingaterry 快捷键确实用不了…粘贴到输入框时文本会自动reformat，我这里无法复现这个问题

**Comment by bazingaterry** [comment]
@geeeeeeeeek 我也感觉不像是这个 App 的问题。然后我去 Google Chrome 测试了一下，也会出现这个问题，所以估计是 Web 版微信的问题。

**Comment by change2hao** [comment]
就这个bug有点烦人，有好几次发出去又连忙取消了，空行太多了，其他方面比Mac官方版好太多了，赞～
