### ISSUE TITLE
linux 扫码登录后闪退回登录界面，手机上仍显示网页微信已登录

### ISSUE THREAD

**Issue by hxer** [geeeeeeeeek/electronic-wechat#87]
First, make sure your issue is strictly related to the ***Electronic WeChat*** project. If it's a question or feature request, you can remove the template below.

#### Description

linux 扫码登录后闪退回登录界面，手机上仍显示网页微信已登录

安装方式为README文件中的npm方式安装，而不是release版本

详细操作系统版本信息如下：

Linux kali 4.4.0-kali1-amd64 #1 SMP Debian 4.4.4-2kali2 (2016-03-11) x86_64 GNU/Linux

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.36.11`
- Version of Node.js (run `$ node --version`): `v4.4.0`
- OS: `linux`
- Architecture `x64`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by geeeeeeeeek** [comment]
Fixed.
