### ISSUE TITLE
请问有没有办法通过命令行传参之类的进行调用？

### ISSUE THREAD

**Issue by Xuanwo** [geeeeeeeeek/electronic-wechat#90]
Hello，我想要了解一下能不能通过命令行传递参数？
或者有没有什么接口暴露出来，可以让我进行二次开发？
现在有一个需求是想在多个微信群中发送相同的信息，不知道有没有优雅一些的解决方案= =

**Comment by geeeeeeeeek** [comment]
暂时没有，你可以参考这两个项目：

https://github.com/sjdy521/Mojo-Weixin
https://github.com/Urinx/WeixinBot

**Comment by Xuanwo** [comment]
Thanks.
