### ISSUE TITLE
通知不显示详情设置

### ISSUE THREAD

**Issue by MenghanInChina** [geeeeeeeeek/electronic-wechat#92]
First, make sure your issue is strictly related to the ***Electronic WeChat*** project. If it's a question or feature request, you can remove the template below.

#### Description

能否有办法提供通知是否显示详情设置呢?

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- Version of Node.js (run `$ node --version`): `v0.0.0`
- OS: `<OS>`
- Architecture `<ARCH>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by geeeeeeeeek** [comment]
通知是微信App直接调的API，很难拦截修改，暂时无法提供这个功能。
