### ISSUE TITLE
添加中国区下载地址

### ISSUE THREAD

**Issue by jzp113** [geeeeeeeeek/electronic-wechat#93]
github的下载好慢。可以加个中国区的下载地址吗？

**Comment by geeeeeeeeek** [comment]
Release是CI自动发布的，你知道有什么国内的托管平台支持web hook发布的吗？

**Comment by jzp113** [comment]
coding？

**Comment by jzp113** [comment]
我感觉可以加个呼出的快捷键

**Comment by geeeeeeeeek** [comment]
维护一个国内的镜像仓库太麻烦了，而且翻墙是程序员的必备技能吧…等我找到支持CI web hook的平台再说…

全局各种快捷键正在考虑中
