### ISSUE TITLE
rpm package

### ISSUE THREAD

**Issue by 1dot75cm** [geeeeeeeeek/electronic-wechat#96]
I just build rpm package for Fedora. This project is very nice.

[wechat-1.0.1-1.gitb43c562.fc23.noarch.rpm](https://repo.fdzh.org/FZUG/free/23/x86_64/wechat-1.0.1-1.gitb43c562.fc23.noarch.rpm)

I hope Release page can provide RPM/DEB packages.  Thanks.

**Comment by geeeeeeeeek** [comment]
@1dot75cm I added your link to the release note. However, It would be inefficient to add manually for each release. Can you automate the workflow?
