### ISSUE TITLE
最小化到托盘的功能

### ISSUE THREAD

**Issue by chndzcl** [geeeeeeeeek/electronic-wechat#98]
赞一个~非常感谢啊， 我来建议一个，是不是可以考虑把程序关闭到托盘呢，这个功能也是常用的，当然得再配合一下全局呼出快捷键。

First, make sure your issue is strictly related to the ***Electronic WeChat*** project. If it's a question or feature request, you can remove the template below.

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- Version of Node.js (run `$ node --version`): `v0.0.0`
- OS: `<OS>`
- Architecture `<ARCH>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by geeeeeeeeek** [comment]
现在点击关闭或者`Cmd+W`就是隐藏到托盘啊。

**Comment by geeyan** [comment]
@geeeeeeeeek 能否有一个 cmd+ctrl+w 来 toggle 显示的快速处理办法？这种场景用的多一点，非常感谢。

**Comment by geeeeeeeeek** [comment]
@geeyan 正在考虑加入快捷键

**Comment by geeyan** [comment]
有合适的钩子的话，我也可以帮忙写写 PR

**Comment by wuhantao** [comment]
恩阅读那一直不更新。。。没有接收到公众号的阅读消息。

**Comment by geeeeeeeeek** [comment]
@wuhantao 什么意思

**Comment by chndzcl** [comment]
确实确实，我原来下的版本低了点，没有那功能，现在折腾半天从github下了 
1.1.1就有这功能了，多谢～虽然那个图标是黑色的:-[ 跟ubuntu的黑色主题有点 
冲突了， 能选择黑白色就完美了:-)

在 2016年03月24日 11:35, Zhongyi Tong 写道:

**Comment by wuhantao** [comment]
就是订阅号阅读文章哪里。你哪里标题是阅读。没有动态的更新公众号的文章吧。

**Comment by geeeeeeeeek** [comment]
@chndzcl 我只考虑了OS X下tray icon的颜色是会随系统dark/light主题自动切换的，Linux下我单独处理一下。
